import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useWorkspace } from '@/app/providers/WorkspaceProvider'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { Select } from '@/components/ui/Select'
import { StatusBadge } from '@/components/ui/StatusBadge'
import { deleteFinishedEvent, finalizeEvent, getEvent, getEventBannerUrl, updateEventSettings, updateEventStatus, updatePublicPanelAppearance, uploadEventBanner } from './eventService'
import { eventStatusLabel, eventStatusTone, formatEventDate } from './eventUtils'
import type { EventSettings, EventStatus, EventWithSettings } from '@/types/database'
import {EventOperationalHealthCard} from '@/features/operations/EventOperationalHealthCard'
import {DEFAULT_PUBLIC_PANEL_APPEARANCE,normalizePublicPanelAppearance,PUBLIC_PANEL_ANIMATION_INTENSITIES,PUBLIC_PANEL_ANIMATION_INTENSITY_LABELS,PUBLIC_PANEL_BALL_ANIMATIONS,PUBLIC_PANEL_BALL_ANIMATION_LABELS,PUBLIC_PANEL_BOARD_STYLES,PUBLIC_PANEL_BOARD_STYLE_LABELS,PUBLIC_PANEL_COLOR_KEYS,PUBLIC_PANEL_COLOR_LABELS,PUBLIC_PANEL_THEMES,PUBLIC_PANEL_THEME_DESCRIPTIONS,PUBLIC_PANEL_THEME_LABELS,PUBLIC_PANEL_THEME_PALETTES,PUBLIC_PANEL_VICTORY_ANIMATIONS,PUBLIC_PANEL_VICTORY_ANIMATION_LABELS,type PublicPanelAppearance,type PublicPanelColorKey} from '@/domain/draw/publicPanelAppearance'
const manualStatuses: EventStatus[] = ['draft','sales_open','sales_paused','ready','canceled']

export function EventDetailPage(){
  const {eventId}=useParams(); const navigate=useNavigate(); const {currentWorkspace}=useWorkspace()
  const [event,setEvent]=useState<EventWithSettings|null>(null); const [bannerUrl,setBannerUrl]=useState<string|null>(null)
  const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null)
  const load=useCallback(async()=>{if(!currentWorkspace||!eventId)return;setLoading(true);setError(null);try{const value=await getEvent(currentWorkspace.id,eventId);setEvent(value);if(value.banner_path){try{setBannerUrl(await getEventBannerUrl(value.banner_path))}catch{setBannerUrl(null)}}else setBannerUrl(null)}catch{setError('Evento não encontrado ou você não possui acesso.')}finally{setLoading(false)}},[currentWorkspace,eventId])
  useEffect(()=>{void load()},[load])

  async function changeStatus(status:EventStatus){if(!currentWorkspace||!eventId)return;setSaving(true);setError(null);try{await updateEventStatus(currentWorkspace.id,eventId,status);setNotice('Status atualizado.');await load()}catch{setError('Não foi possível atualizar o status.')}finally{setSaving(false)}}
  async function saveSettings(patch:Partial<EventSettings>){if(!currentWorkspace||!eventId)return;setSaving(true);setError(null);try{await updateEventSettings(currentWorkspace.id,eventId,patch);setNotice('Configurações salvas.');await load()}catch{setError('Não foi possível salvar as configurações.')}finally{setSaving(false)}}
  async function savePanelAppearance(patch:Partial<PublicPanelAppearance>){if(!currentWorkspace||!eventId||!event)return;setSaving(true);setError(null);try{const current=normalizePublicPanelAppearance((event.settings.settings as Record<string,unknown>|undefined)?.public_panel_appearance);const next={...current,...patch};await updatePublicPanelAppearance(currentWorkspace.id,eventId,next);setEvent(prev=>prev?{...prev,settings:{...prev.settings,settings:{...(prev.settings.settings??{}),public_panel_appearance:next}}}:prev);setNotice('Visual da TV salvo.')}catch{setError('Não foi possível salvar o visual da TV.')}finally{setSaving(false)}}
  async function finishEvent(){if(!eventId||!event)return;if(!confirm(`Finalizar o evento "${event.name}"? Depois disso ele ficará bloqueado para operação e poderá ser excluído permanentemente.`))return;setSaving(true);setError(null);setNotice(null);try{await finalizeEvent(eventId);setNotice('Evento finalizado. Agora ele pode ser excluído permanentemente.');await load()}catch(err){setError(err instanceof Error?err.message:'Não foi possível finalizar o evento.')}finally{setSaving(false)}}
  async function removeEvent(){if(!currentWorkspace||!eventId||!event||event.status!=='finished')return;const typed=prompt(`Esta ação apaga permanentemente o evento, cartelas, vendas, sorteios e histórico operacional vinculados. Para confirmar, digite exatamente o nome do evento:

${event.name}`);if(typed!==event.name){if(typed!==null)setError('Exclusão cancelada: o nome informado não confere.');return}setSaving(true);setError(null);setNotice(null);try{const result=await deleteFinishedEvent(currentWorkspace.id,eventId);navigate('/eventos',{replace:true,state:{notice:result.storageCleaned?'Evento excluído permanentemente.':'Evento excluído. Alguns arquivos do Storage podem exigir limpeza posterior.'}})}catch(err){setError(err instanceof Error?err.message:'Não foi possível excluir o evento.')}finally{setSaving(false)}}
  async function banner(file?:File){if(!file||!currentWorkspace||!eventId)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('Use JPG, PNG ou WEBP de até 5 MB.');return}setSaving(true);try{await uploadEventBanner(currentWorkspace.id,eventId,file);setNotice('Banner atualizado.');await load()}catch{setError('Não foi possível enviar o banner.')}finally{setSaving(false)}}

  if(loading)return <Card>Carregando evento…</Card>
  if(error&&!event)return <div className="space-y-4"><div className="rounded-2xl bg-red-50 p-4 text-red-700">{error}</div><Link to="/eventos"><Button variant="secondary">Voltar</Button></Link></div>
  if(!event)return null

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-emerald-700">Evento</p><StatusBadge tone={eventStatusTone(event.status)}>{eventStatusLabel[event.status]}</StatusBadge></div><h1 className="mt-2 text-3xl font-black tracking-tight">{event.name}</h1><p className="mt-2 text-sm text-slate-600">{formatEventDate(event.starts_at)} · Código público {event.public_code}</p></div><div className="flex flex-wrap gap-2"><Link to="/eventos"><Button variant="secondary">Voltar</Button></Link><Link to={`/eventos/${event.id}/editar`}><Button>Editar</Button></Link></div></div>
    {notice&&<div className="rounded-2xl bg-emerald-50 p-4 text-sm font-medium text-emerald-800">{notice}</div>}{error&&<div className="rounded-2xl bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}
    <div className="grid gap-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(320px,.7fr)]">
      <div className="space-y-5">
        <Card><h2 className="text-lg font-black">Visão geral</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Info label="Local" value={event.location_name||'Não definido'}/><Info label="Endereço" value={event.address||'Não definido'}/><Info label="Início" value={formatEventDate(event.starts_at)}/><Info label="Término" value={formatEventDate(event.ends_at)}/><Info label="Abertura das vendas" value={formatEventDate(event.sales_open_at)}/><Info label="Fechamento das vendas" value={formatEventDate(event.sales_close_at)}/></div>{event.description&&<p className="mt-5 whitespace-pre-wrap text-sm text-slate-600">{event.description}</p>}</Card>
        <Card><h2 className="text-lg font-black">Banner do evento</h2><p className="mt-1 text-sm text-slate-600">Este banner identifica o evento. A arte de fundo das cartelas é configurada separadamente em Layouts das cartelas.</p>{bannerUrl?<img src={bannerUrl} alt="Banner do evento" className="mt-4 max-h-64 w-full rounded-2xl border border-slate-200 object-contain bg-slate-50"/>:<div className="mt-4 grid min-h-40 place-items-center rounded-2xl border border-dashed border-slate-300 text-sm text-slate-500">Nenhum banner enviado</div>}<label className="mt-4 inline-flex cursor-pointer items-center rounded-2xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold hover:bg-slate-50"><input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" disabled={saving} onChange={e=>void banner(e.target.files?.[0])}/>Selecionar banner</label><div className="mt-3"><Link to={`/eventos/${event.id}/cartelas/configuracao?aba=layouts`}><Button variant="secondary">Configurar arte das cartelas →</Button></Link></div></Card>
        <Card><h2 className="text-lg font-black">Ações do evento</h2><p className="mt-2 text-sm text-slate-600">Acesse diretamente o que precisa fazer agora. Nenhuma área depende de seguir uma sequência visual de etapas.</p><div className="mt-4 grid gap-2 sm:grid-cols-2"><Link to={`/eventos/${event.id}/cartelas/gerar`}><Button className="w-full">Criar cartelas</Button></Link><Link to={`/eventos/${event.id}/cartelas`}><Button variant="secondary" className="w-full">Gerenciar cartelas</Button></Link><Link to={`/eventos/${event.id}/vendas`}><Button variant="secondary" className="w-full">Vendas</Button></Link><Link to={`/eventos/${event.id}/sorteio`}><Button variant="secondary" className="w-full">Sorteio</Button></Link></div></Card>
        <EventOperationalHealthCard eventId={event.id}/>
      </div>
      <div className="space-y-5">
        <Card><h2 className="text-lg font-black">Operação</h2><label className="mt-4 block text-sm font-semibold text-slate-700">Status do evento<Select className="mt-1" value={event.status} disabled={saving||event.status==='archived'||event.status==='drawing'||event.status==='paused'||event.status==='finished'} onChange={e=>void changeStatus(e.target.value as EventStatus)}>{!manualStatuses.includes(event.status)&&<option value={event.status}>{eventStatusLabel[event.status]}</option>}{manualStatuses.map(s=><option key={s} value={s}>{eventStatusLabel[s]}</option>)}</Select></label><p className="mt-3 text-xs text-slate-500">Durante sorteio, pausa e encerramento, o status é controlado automaticamente para evitar estados inválidos. Para continuar um evento finalizado, use a tela Sorteio.</p></Card>
        <Card className="border-red-900/60"><h2 className="text-lg font-black">Encerrar evento</h2>{event.status!=='finished'?<><p className="mt-2 text-sm text-slate-600">Quando o evento terminar, finalize-o para bloquear a operação e liberar a exclusão permanente.</p><Button className="mt-4 w-full" variant="secondary" disabled={saving||event.status==='drawing'||event.status==='paused'||event.status==='archived'} onClick={()=>void finishEvent()}>Finalizar evento</Button>{(event.status==='drawing'||event.status==='paused')&&<p className="mt-2 text-xs text-amber-600">Há um sorteio em andamento. Encerre a rodada na tela Sorteio antes de finalizar o evento.</p>}</>:<><div className="mt-3 rounded-xl border border-emerald-800/50 bg-emerald-950/20 p-3 text-sm text-emerald-200">Evento finalizado. A exclusão permanente está liberada.</div><p className="mt-3 text-xs text-slate-500">Excluir remove definitivamente cartelas, lotes, vendas, sorteios e demais dados vinculados. Esta ação não pode ser desfeita.</p><Button className="mt-4 w-full" disabled={saving} onClick={()=>void removeEvent()}>Excluir evento permanentemente</Button></>}</Card>
        <Card><h2 className="text-lg font-black">Venda e compradores</h2><Toggle label="Exigir nome do comprador" checked={event.settings.require_buyer_name} disabled={saving} onChange={v=>void saveSettings({require_buyer_name:v})}/><Toggle label="Exigir telefone" checked={event.settings.require_buyer_phone} disabled={saving} onChange={v=>void saveSettings({require_buyer_phone:v})}/><Toggle label="Exigir e-mail" checked={event.settings.require_buyer_email} disabled={saving} onChange={v=>void saveSettings({require_buyer_email:v})}/><Toggle label="Permitir reservas" checked={event.settings.allow_reservations} disabled={saving} onChange={v=>void saveSettings({allow_reservations:v})}/></Card>
        <PublicPanelSettingsCard event={event} saving={saving} saveSettings={saveSettings} saveAppearance={savePanelAppearance}/>
      </div>
    </div>
  </div>
}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-medium text-slate-800">{value}</p></div>}
function Toggle({label,checked,onChange,disabled}:{label:string;checked:boolean;onChange:(v:boolean)=>void;disabled:boolean}){return <label className="mt-3 flex items-center justify-between gap-4 rounded-2xl border border-slate-200 p-3 text-sm font-medium"><span>{label}</span><input type="checkbox" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/></label>}

function PublicPanelSettingsCard({event,saving,saveSettings,saveAppearance}:{event:EventWithSettings;saving:boolean;saveSettings:(patch:Partial<EventSettings>)=>Promise<void>;saveAppearance:(patch:Partial<PublicPanelAppearance>)=>Promise<void>}){
  const appearance=normalizePublicPanelAppearance((event.settings.settings as Record<string,unknown>|undefined)?.public_panel_appearance??DEFAULT_PUBLIC_PANEL_APPEARANCE)
  const updateColor=(key:PublicPanelColorKey,value:string)=>void saveAppearance({custom_colors:{...appearance.custom_colors,[key]:value}})
  return <Card><h2 className="text-lg font-black">Painel público / TV</h2><p className="mt-1 text-xs text-slate-500">O tema define a estrutura visual. As cores podem ser personalizadas separadamente sem alterar o sorteio.</p>
    <div className="mt-4 grid gap-3 sm:grid-cols-2">
      <PanelSelect label="Tema / estrutura" value={appearance.theme} disabled={saving} onChange={v=>void saveAppearance({theme:v as PublicPanelAppearance['theme']})}>{PUBLIC_PANEL_THEMES.map(v=><option key={v} value={v}>{PUBLIC_PANEL_THEME_LABELS[v]}</option>)}</PanelSelect>
      <PanelSelect label="Estilo dos números" value={appearance.board_style} disabled={saving} onChange={v=>void saveAppearance({board_style:v as PublicPanelAppearance['board_style']})}>{PUBLIC_PANEL_BOARD_STYLES.map(v=><option key={v} value={v}>{PUBLIC_PANEL_BOARD_STYLE_LABELS[v]}</option>)}</PanelSelect>
      <PanelSelect label="Animação da bola" value={appearance.ball_animation} disabled={saving} onChange={v=>void saveAppearance({ball_animation:v as PublicPanelAppearance['ball_animation']})}>{PUBLIC_PANEL_BALL_ANIMATIONS.map(v=><option key={v} value={v}>{PUBLIC_PANEL_BALL_ANIMATION_LABELS[v]}</option>)}</PanelSelect>
      <PanelSelect label="Animação da vitória" value={appearance.victory_animation} disabled={saving} onChange={v=>void saveAppearance({victory_animation:v as PublicPanelAppearance['victory_animation']})}>{PUBLIC_PANEL_VICTORY_ANIMATIONS.map(v=><option key={v} value={v}>{PUBLIC_PANEL_VICTORY_ANIMATION_LABELS[v]}</option>)}</PanelSelect>
      <PanelSelect label="Intensidade" value={appearance.animation_intensity} disabled={saving} onChange={v=>void saveAppearance({animation_intensity:v as PublicPanelAppearance['animation_intensity']})}>{PUBLIC_PANEL_ANIMATION_INTENSITIES.map(v=><option key={v} value={v}>{PUBLIC_PANEL_ANIMATION_INTENSITY_LABELS[v]}</option>)}</PanelSelect>
    </div>
    <div className="mt-3 rounded-2xl border border-slate-200 bg-slate-50 p-3 text-xs text-slate-600"><strong className="text-slate-800">{PUBLIC_PANEL_THEME_LABELS[appearance.theme]}:</strong> {PUBLIC_PANEL_THEME_DESCRIPTIONS[appearance.theme]}</div>
    <label className="mt-4 block text-sm font-semibold text-slate-700">Contato do evento na TV<input type="text" value={appearance.event_contact} disabled={saving} maxLength={80} placeholder="Ex.: WhatsApp (11) 99999-9999" onChange={e=>void saveAppearance({event_contact:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-500"/><span className="mt-1 block text-xs font-normal text-slate-500">A TV exibirá claramente “Contato do evento” para não confundir com o suporte do BINGOUP.</span></label>
    <div className="mt-4 rounded-2xl border border-slate-200 p-3">
      <Toggle label="Personalizar cores do painel" checked={appearance.use_custom_colors} disabled={saving} onChange={v=>void saveAppearance({use_custom_colors:v})}/>
      {appearance.use_custom_colors&&<><div className="mt-3 grid gap-3 sm:grid-cols-2">{PUBLIC_PANEL_COLOR_KEYS.map(key=><ColorField key={key} label={PUBLIC_PANEL_COLOR_LABELS[key]} value={appearance.custom_colors[key]??PUBLIC_PANEL_THEME_PALETTES[appearance.theme][key]} disabled={saving} onChange={value=>updateColor(key,value)}/>)}</div><Button className="mt-3 w-full" variant="secondary" disabled={saving} onClick={()=>void saveAppearance({use_custom_colors:false,custom_colors:{}})}>Restaurar cores do tema</Button></>}
    </div>
    <div className="mt-4"><Toggle label="Mostrar último número" checked={event.settings.public_panel_show_last_number} disabled={saving} onChange={v=>void saveSettings({public_panel_show_last_number:v})}/><Toggle label="Mostrar números sorteados" checked={event.settings.public_panel_show_called_numbers} disabled={saving} onChange={v=>void saveSettings({public_panel_show_called_numbers:v})}/><Toggle label="Mostrar andamento" checked={event.settings.public_panel_show_progress} disabled={saving} onChange={v=>void saveSettings({public_panel_show_progress:v})}/><Toggle label="Mostrar jogos próximos" checked={event.settings.public_panel_show_near_winners} disabled={saving} onChange={v=>void saveSettings({public_panel_show_near_winners:v})}/><Toggle label="Mostrar nome da rodada" checked={appearance.show_round_name} disabled={saving} onChange={v=>void saveAppearance({show_round_name:v})}/><Toggle label="Mostrar prêmio atual" checked={appearance.show_prize} disabled={saving} onChange={v=>void saveAppearance({show_prize:v})}/><Toggle label="Mostrar últimas bolas" checked={appearance.show_recent_numbers} disabled={saving} onChange={v=>void saveAppearance({show_recent_numbers:v})}/><Toggle label="Mostrar contadores" checked={appearance.show_counters} disabled={saving} onChange={v=>void saveAppearance({show_counters:v})}/><Toggle label="Moldura animada" checked={appearance.animated_frame} disabled={saving} onChange={v=>void saveAppearance({animated_frame:v})}/></div>
  </Card>
}
function ColorField({label,value,onChange,disabled}:{label:string;value:string;onChange:(value:string)=>void;disabled:boolean}){return <label className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 p-2 text-xs font-semibold text-slate-700"><span>{label}</span><span className="flex items-center gap-2"><input type="color" value={value} disabled={disabled} onChange={e=>onChange(e.target.value)} className="h-9 w-11 cursor-pointer rounded border border-slate-300 bg-white p-1"/><code className="w-[72px] text-[11px] font-semibold uppercase text-slate-500">{value}</code></span></label>}
function PanelSelect({label,value,onChange,disabled,children}:{label:string;value:string;onChange:(value:string)=>void;disabled:boolean;children:React.ReactNode}){return <label className="block text-sm font-semibold text-slate-700">{label}<Select className="mt-1" value={value} disabled={disabled} onChange={e=>onChange(e.target.value)}>{children}</Select></label>}
