import {supabase} from '@/services/supabase/client'
import type {SymbolItem} from '@/domain/game-modes/themes'

export type RaffleConfig={event_id:string;workspace_id:string;total_numbers:number;ticket_price:number;animation_seconds:number;prize_description:string|null}
export type RaffleTicket={id:string;number:number;status:'available'|'reserved'|'sold';buyer_name:string|null;buyer_phone:string|null;sold_price:number|null}
export type SymbolConfig={event_id:string;workspace_id:string;theme_name:string;grid_size:number;animation_seconds:number;free_center:boolean}
export type StoredSymbolItem=SymbolItem&{id:string;position:number}
export async function getRaffle(eventId:string){const [{data:config,error:a},{data:tickets,error:b},{data:draws,error:c}]=await Promise.all([supabase.from('raffle_configs').select('*').eq('event_id',eventId).maybeSingle(),supabase.from('raffle_tickets').select('*').eq('event_id',eventId).order('number'),supabase.from('raffle_draws').select('*,raffle_tickets(number,buyer_name)').eq('event_id',eventId).order('draw_order',{ascending:false})]);if(a||b||c)throw a||b||c;return{config:config as RaffleConfig,tickets:(tickets??[]) as RaffleTicket[],draws:draws??[]}}
export async function configureRaffle(eventId:string,total:number,price:number,seconds:number,prize:string){const{error}=await supabase.rpc('configure_raffle',{target_event_id:eventId,target_total_numbers:total,target_ticket_price:price,target_animation_seconds:seconds,target_prize:prize});if(error)throw error}
export async function updateTicket(ticket:RaffleTicket,status:RaffleTicket['status'],buyerName='',buyerPhone='',price=0){const patch=status==='available'?{status,buyer_name:null,buyer_phone:null,sold_price:null,sold_at:null}:{status,buyer_name:buyerName.trim()||null,buyer_phone:buyerPhone.trim()||null,sold_price:price,sold_at:status==='sold'?new Date().toISOString():null};const{error}=await supabase.from('raffle_tickets').update(patch).eq('id',ticket.id);if(error)throw error}
export async function drawRaffle(eventId:string){const{data,error}=await supabase.rpc('draw_raffle_winner',{target_event_id:eventId});if(error)throw error;return data as RaffleTicket}
export async function getSymbolBingo(eventId:string){const [{data:config,error:a},{data:items,error:b},{data:draws,error:c}]=await Promise.all([supabase.from('symbol_bingo_configs').select('*').eq('event_id',eventId).maybeSingle(),supabase.from('symbol_bingo_items').select('*').eq('event_id',eventId).order('position'),supabase.from('symbol_bingo_draws').select('*,symbol_bingo_items(*)').eq('event_id',eventId).order('draw_order',{ascending:false})]);if(a||b||c)throw a||b||c;return{config:config as SymbolConfig|null,items:(items??[]) as StoredSymbolItem[],draws:draws??[]}}
export async function configureSymbolBingo(eventId:string,theme:string,grid:number,seconds:number,free:boolean,items:SymbolItem[]){const{error}=await supabase.rpc('configure_symbol_bingo',{target_event_id:eventId,target_theme_name:theme,target_grid_size:grid,target_animation_seconds:seconds,target_free_center:free,target_items:items});if(error)throw error}
export async function drawSymbol(eventId:string){const{data,error}=await supabase.rpc('draw_next_symbol',{target_event_id:eventId});if(error)throw error;return data as StoredSymbolItem}
