import{useCallback,useEffect,useMemo,useState}from'react'
import{Link,useParams}from'react-router-dom'
import{Button}from'@/components/ui/Button';import{Card}from'@/components/ui/Card';import{Input}from'@/components/ui/Input';import{Select}from'@/components/ui/Select';import{getErrorMessage}from'@/lib/errors'
import{configureRaffle,configureRafflePrizes,getRaffle,setRafflePrizeDelivered,updateTicket,type RaffleTicket}from'./gameModeService'

export function RafflePage(){const{eventId=''}=useParams();const[data,setData]=useState<Awaited<ReturnType<typeof getRaffle>>|null>(null);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const[selected,setSelected]=useState<RaffleTicket|null>(null);const[query,setQuery]=useState('');const[prizes,setPrizes]=useState<Array<{name:string;description:string}>>([{name:'Prêmio principal',description:''}]);const[generating,setGenerating]=useState(false)
 const load=useCallback(async()=>{try{const value=await getRaffle(eventId);setData(value);if(value.prizes.length)setPrizes(value.prizes.map(p=>({name:p.name,description:p.description??''})));setError('')}catch(e){setError(getErrorMessage(e,'Não foi possível carregar a rifa.'))}},[eventId]);useEffect(()=>{void load()},[load])
 const filtered=useMemo(()=>data?.tickets.filter(t=>!query||String(t.number).includes(query)||t.buyer_name?.toLowerCase().includes(query.toLowerCase()))??[],[data,query]);const sold=data?.tickets.filter(t=>t.status==='sold').length??0;const drawingStarted=Boolean(data?.draws.length)
 async function saveConfig(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await configureRaffle(eventId,Number(f.get('total')),Number(f.get('price')),Number(f.get('seconds')),prizes.map(p=>p.name).join('; '));await configureRafflePrizes(eventId,prizes.map(p=>({name:p.name.trim(),description:p.description.trim()})));setNotice('Configuração, números e prêmios salvos.');await load()}catch(x){setError(getErrorMessage(x,'Não foi possível configurar a rifa.'))}finally{setBusy(false)}}
 async function saveTicket(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await updateTicket(selected,String(f.get('status'))as RaffleTicket['status'],String(f.get('name')??''),String(f.get('phone')??''),String(f.get('email')??''),Number(f.get('price')));setSelected(null);setNotice('Número atualizado.');await load()}catch(e){setError(getErrorMessage(e,'Não foi possível atualizar este número.'))}finally{setBusy(false)}}
 async function delivery(id:string,current:boolean){setBusy(true);try{await setRafflePrizeDelivered(id,!current);await load()}catch(e){setError(getErrorMessage(e,'Não foi possível atualizar a entrega.'))}finally{setBusy(false)}}
 async function shareNumbersImage(){if(!data?.config||!data.tickets.length)return;setGenerating(true);setError('');try{
  const tickets=data.tickets,columns=tickets.length<=100?10:tickets.length<=400?15:20,cell=52,gap=8,padding=48,header=250,rows=Math.ceil(tickets.length/columns),width=Math.max(1080,padding*2+columns*cell+(columns-1)*gap),height=header+padding+rows*cell+(rows-1)*gap
  const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Seu navegador não conseguiu criar a imagem.')
  ctx.fillStyle='#f8fafc';ctx.fillRect(0,0,width,height);ctx.textAlign='center';ctx.fillStyle='#0f172a';ctx.font='900 46px system-ui,sans-serif';ctx.fillText('NÚMEROS DA RIFA',width/2,64);ctx.font='600 24px system-ui,sans-serif';ctx.fillStyle='#475569';ctx.fillText(`R$ ${Number(data.config.ticket_price).toFixed(2).replace('.',',')} por número · Atualizado em ${new Date().toLocaleString('pt-BR')}`,width/2,105)
  const available=tickets.filter(t=>t.status==='available').length,reserved=tickets.filter(t=>t.status==='reserved').length,soldCount=tickets.filter(t=>t.status==='sold').length
  const legend=[['#ffffff','#334155',`Disponíveis: ${available}`],['#fef3c7','#92400e',`Reservados: ${reserved}`],['#d1fae5','#065f46',`Vendidos: ${soldCount}`]] as const;ctx.font='700 22px system-ui,sans-serif';let legendX=width/2-330;legend.forEach(([bg,color,label])=>{ctx.fillStyle=bg;ctx.strokeStyle=color;ctx.lineWidth=2;roundRect(ctx,legendX,140,28,28,7);ctx.fill();ctx.stroke();ctx.fillStyle='#334155';ctx.textAlign='left';ctx.fillText(label,legendX+40,163);legendX+=220})
  const gridWidth=columns*cell+(columns-1)*gap,startX=(width-gridWidth)/2;ctx.textAlign='center';ctx.textBaseline='middle';tickets.forEach((ticket,index)=>{const x=startX+(index%columns)*(cell+gap),y=header+Math.floor(index/columns)*(cell+gap),colors:[string,string,string]=ticket.status==='sold'?['#d1fae5','#065f46','#047857']:ticket.status==='reserved'?['#fef3c7','#92400e','#d97706']:['#ffffff','#0f172a','#94a3b8'];ctx.fillStyle=colors[0];ctx.strokeStyle=colors[2];ctx.lineWidth=2;roundRect(ctx,x,y,cell,cell,9);ctx.fill();ctx.stroke();ctx.fillStyle=colors[1];ctx.font='800 20px system-ui,sans-serif';ctx.fillText(String(ticket.number),x+cell/2,y+cell/2)})
  const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Não foi possível finalizar a imagem.')),'image/png'));const file=new File([blob],`numeros-rifa-${new Date().toISOString().slice(0,10)}.png`,{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'Números disponíveis da rifa'});else{const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=file.name;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Imagem gerada e baixada. Agora você pode enviá-la para as pessoas.')}
 }catch(e){if((e as DOMException)?.name!=='AbortError')setError(getErrorMessage(e,'Não foi possível gerar a imagem.'))}finally{setGenerating(false)}}

 function addPrize(){setPrizes(v=>[...v,{name:`Prêmio ${v.length+1}`,description:''}])}function removePrize(index:number){setPrizes(v=>v.filter((_,i)=>i!==index))}function editPrize(index:number,key:'name'|'description',value:string){setPrizes(v=>v.map((p,i)=>i===index?{...p,[key]:value}:p))}const drawnPrizeIds=new Set(data?.draws.map(d=>d.prize_id)??[])
 if(!data)return <Card>{error||'Carregando rifa…'}</Card>
 return <div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold text-amber-700">Modo rifa</p><h1 className="text-3xl font-black">Configuração e vendas</h1><p className="mt-1 text-sm text-slate-600">Configure os números e prêmios, depois venda e acompanhe os ganhadores.</p></div><div className="flex flex-wrap gap-2"><Link to={`/eventos/${eventId}/rifa/sorteio`}><Button>Ir para o sorteio</Button></Link><Link to={`/eventos/${eventId}`}><Button variant="secondary">Voltar</Button></Link></div></header>{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}{notice&&<p role="status" className="rounded-xl bg-emerald-50 p-3 text-emerald-800">{notice}</p>}
 <Card><h2 className="text-lg font-black">1. Configure a rifa</h2><p className="mt-1 text-sm text-slate-600">O preço salvo será preenchido automaticamente em cada venda.</p><form onSubmit={saveConfig} className="mt-4 space-y-5"><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">Quantidade de números<Input name="total" type="number" min={2} max={10000} required defaultValue={data.config?.total_numbers??100}/></label><label className="text-sm font-semibold">Preço por número<Input name="price" type="number" min={0} step=".01" required defaultValue={data.config?.ticket_price??0}/></label><label className="text-sm font-semibold">Tempo de suspense<Select name="seconds" defaultValue={data.config?.animation_seconds??8}>{[3,5,8,10,15,20,30,45,60].map(v=><option key={v} value={v}>{v} segundos</option>)}</Select></label></div><div><div className="flex items-center justify-between gap-3"><h3 className="font-black">Prêmios em ordem</h3><Button type="button" variant="secondary" onClick={addPrize}>Adicionar prêmio</Button></div><div className="mt-3 space-y-3">{prizes.map((p,i)=><div key={i} className="grid gap-2 rounded-xl border border-slate-200 p-3 sm:grid-cols-[52px_1fr_1.4fr_auto]"><span className="grid size-11 place-items-center rounded-xl bg-amber-100 font-black text-amber-900">{i+1}º</span><Input aria-label={`Nome do prêmio ${i+1}`} required maxLength={160} value={p.name} disabled={Boolean(data.prizes[i]&&drawnPrizeIds.has(data.prizes[i].id))} onChange={e=>editPrize(i,'name',e.target.value)}/><Input aria-label={`Descrição do prêmio ${i+1}`} maxLength={500} placeholder="Descrição opcional" value={p.description} disabled={Boolean(data.prizes[i]&&drawnPrizeIds.has(data.prizes[i].id))} onChange={e=>editPrize(i,'description',e.target.value)}/><Button type="button" variant="secondary" disabled={Boolean(data.prizes[i]&&drawnPrizeIds.has(data.prizes[i].id))||prizes.length===1} onClick={()=>removePrize(i)}>Remover</Button></div>)}</div>{drawingStarted&&<p className="mt-2 text-xs text-amber-700">Prêmios já sorteados ficam bloqueados; você ainda pode adicionar os próximos.</p>}</div><Button disabled={busy}>{busy?'Salvando…':'Salvar e gerar números'}</Button></form></Card>
 {data.config&&<><div className="grid gap-3 sm:grid-cols-3"><Metric label="Disponíveis" value={data.tickets.filter(t=>t.status==='available').length}/><Metric label="Reservados" value={data.tickets.filter(t=>t.status==='reserved').length}/><Metric label="Vendidos" value={sold}/></div><Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black">2. Venda e gerencie os números</h2><p className="text-xs text-slate-500">Selecione um número para vender, reservar ou liberar.</p></div><div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row"><Button type="button" variant="secondary" disabled={generating} onClick={()=>void shareNumbersImage()}>{generating?'Gerando imagem…':'Gerar imagem para compartilhar'}</Button><Input className="sm:max-w-xs" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar número ou comprador"/></div></div><div className="mt-4 grid grid-cols-5 gap-2 sm:grid-cols-10 lg:grid-cols-15">{filtered.map(t=><button type="button" key={t.id} onClick={()=>setSelected(t)} aria-label={`Número ${t.number}, ${t.status}`} className={`min-h-11 rounded-xl border text-sm font-black ${t.status==='sold'?'border-emerald-700 bg-emerald-100 text-emerald-900':t.status==='reserved'?'border-amber-600 bg-amber-100 text-amber-900':'border-slate-300 bg-white text-slate-800 hover:border-slate-500'}`}>{t.number}</button>)}</div></Card>
 <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black">3. Ganhadores por prêmio</h2><p className="text-sm text-slate-600">Registro permanente dos resultados desta rifa.</p></div><Link to={`/eventos/${eventId}/rifa/sorteio`}><Button>Abrir sorteio</Button></Link></div>{data.draws.length?<div className="mt-4 space-y-3">{data.draws.map(d=><div key={d.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-3"><div><p className="font-black">{d.raffle_prizes?.name??`Prêmio ${d.draw_order}`}</p><p className="text-sm text-slate-600">Número <strong>{d.raffle_tickets?.number}</strong> · {d.raffle_tickets?.buyer_name||'Comprador não informado'} · {new Date(d.drawn_at).toLocaleString('pt-BR')}</p></div>{d.raffle_prizes&&<Button variant="secondary" disabled={busy} onClick={()=>void delivery(d.raffle_prizes!.id,Boolean(d.raffle_prizes!.delivered_at))}>{d.raffle_prizes.delivered_at?'Marcar como pendente':'Confirmar entrega'}</Button>}</div>)}</div>:<p className="mt-4 text-sm text-slate-500">Nenhum prêmio sorteado ainda.</p>}</Card></>}
 {selected&&<div className="fixed inset-0 z-[130] grid place-items-center overflow-y-auto bg-black/70 p-4" role="dialog" aria-modal="true"><Card className="w-full max-w-md"><h2 className="text-xl font-black">Número {selected.number}</h2><form onSubmit={saveTicket} className="mt-4 space-y-3"><label className="block text-sm font-semibold">Situação<Select name="status" defaultValue={selected.status}><option value="available">Disponível</option><option value="reserved">Reservado</option><option value="sold">Vendido</option></Select></label><label className="block text-sm font-semibold">Comprador<Input name="name" maxLength={160} defaultValue={selected.buyer_name??''}/></label><label className="block text-sm font-semibold">Telefone<Input name="phone" maxLength={40} defaultValue={selected.buyer_phone??''}/></label><label className="block text-sm font-semibold">E-mail da área do comprador<Input name="email" type="email" maxLength={160} defaultValue={selected.buyer_email??''}/></label><label className="block text-sm font-semibold">Valor<Input name="price" type="number" min={0} step=".01" defaultValue={selected.sold_price??data.config?.ticket_price??0}/></label><div className="flex gap-2"><Button disabled={busy}>Salvar</Button><Button type="button" variant="secondary" onClick={()=>setSelected(null)}>Cancelar</Button></div></form></Card></div>}</div>}
function Metric({label,value}:{label:string;value:number}){return <Card><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></Card>}

function roundRect(ctx:CanvasRenderingContext2D,x:number,y:number,width:number,height:number,radius:number){ctx.beginPath();ctx.roundRect(x,y,width,height,radius)}
