import {useCallback,useEffect,useState} from 'react'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {getErrorMessage} from '@/lib/errors'
import {drawRaffle,drawSymbol,getRaffle,getSymbolBingo,type RaffleTicket,type StoredSymbolItem} from './gameModeService'

export function SpecialModeOperatorPage({eventId,mode}:{eventId:string;mode:'raffle'|'symbol_bingo'}){
 const[data,setData]=useState<Awaited<ReturnType<typeof getRaffle>>|Awaited<ReturnType<typeof getSymbolBingo>>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[countdown,setCountdown]=useState(0),[result,setResult]=useState<RaffleTicket|StoredSymbolItem|null>(null),[revealed,setRevealed]=useState(false)
 const load=useCallback(async()=>{try{setData(mode==='raffle'?await getRaffle(eventId):await getSymbolBingo(eventId));setError('')}catch(e){setError(getErrorMessage(e,'Não foi possível carregar o sorteio.'))}},[eventId,mode]);useEffect(()=>{void load()},[load])
 async function draw(){if(!data?.config)return;setBusy(true);setError('');setResult(null);setRevealed(false);try{const next=mode==='raffle'?await drawRaffle(eventId):await drawSymbol(eventId);setCountdown(data.config.animation_seconds);const timer=window.setInterval(()=>setCountdown(v=>{if(v<=1){window.clearInterval(timer);setResult(next);setBusy(false);void load();return 0}return v-1}),1000)}catch(e){setError(getErrorMessage(e,'Não foi possível sortear.'));setBusy(false)}}
 const history=data?.draws.length??0
 return <div className="space-y-5">{error&&<p role="alert" className="rounded-xl border border-red-900 bg-red-950/30 p-3 text-red-300">{error}</p>}<Card className="text-center"><p className="text-xs font-black uppercase tracking-[.16em] text-red-400">{mode==='raffle'?'Sorteio da rifa':'Bingo de símbolos e charadas'}</p><h2 className="mt-2 text-2xl font-black text-white">{mode==='raffle'?'Sortear somente números vendidos':'Sortear a próxima charada'}</h2>{countdown>0?<div className="my-8" role="status"><p className="text-sm font-bold uppercase tracking-widest text-amber-300">Sorteio em andamento</p><p className="mt-2 text-7xl font-black tabular-nums text-white">{countdown}</p></div>:result?<Result result={result} mode={mode} revealed={revealed} onReveal={()=>setRevealed(true)}/>:<p className="my-8 text-slate-400">{history?`${history} resultado(s) no histórico.`:'Pronto para iniciar.'}</p>}<Button disabled={busy||!data?.config} onClick={()=>void draw()}>{busy?'Aguarde…':history?'Sortear próximo':'Iniciar sorteio'}</Button>{!data?.config&&<p className="mt-3 text-sm text-amber-300">O organizador ainda não configurou este modo.</p>}</Card></div>
}
function Result({result,mode,revealed,onReveal}:{result:RaffleTicket|StoredSymbolItem;mode:'raffle'|'symbol_bingo';revealed:boolean;onReveal:()=>void}){if(mode==='raffle'&&'number'in result)return <div className="my-7 rounded-3xl bg-emerald-950 p-6 text-white"><p className="text-sm font-black uppercase text-emerald-300">Número sorteado</p><p className="text-8xl font-black">{result.number}</p><p>{result.buyer_name}</p></div>;const item=result as StoredSymbolItem;return <div className="my-7 rounded-3xl bg-violet-950 p-6 text-white"><p className="text-sm font-black uppercase text-violet-300">Charada</p><p className="mx-auto mt-3 max-w-2xl text-2xl font-bold">{item.riddle}</p>{revealed?<><p className="mt-5 text-7xl">{item.symbol}</p><p className="text-3xl font-black">{item.label}</p></>:<Button className="mt-5" onClick={onReveal}>Revelar resposta</Button>}</div>}
