import {useCallback,useEffect,useMemo,useState} from 'react'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {Input} from '@/components/ui/Input'
import {Select} from '@/components/ui/Select'
import {getRaffle,getSymbolCards,updateSymbolCard,updateTicket,type RaffleTicket,type SymbolCard} from './gameModeService'

type SaleItem=RaffleTicket|SymbolCard
export function SpecialModeSalesPage({eventId,mode}:{eventId:string;mode:'raffle'|'symbol_bingo'}){
 const[items,setItems]=useState<SaleItem[]>([]),[selected,setSelected]=useState<SaleItem|null>(null),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{try{setItems(mode==='raffle'?(await getRaffle(eventId)).tickets:await getSymbolCards(eventId));setError('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a disponibilidade.')}},[eventId,mode])
 useEffect(()=>{void load()},[load])
 const filtered=useMemo(()=>items.filter(i=>{const label='number'in i?String(i.number):i.code;return !query||label.toLowerCase().includes(query.toLowerCase())||i.buyer_name?.toLowerCase().includes(query.toLowerCase())}),[items,query])
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget),status=String(f.get('status'))as 'available'|'reserved'|'sold';setBusy(true);try{const args=[status,String(f.get('name')??''),String(f.get('phone')??''),String(f.get('email')??''),Number(f.get('price')??0)]as const;if('number'in selected)await updateTicket(selected,...args);else await updateSymbolCard(selected,...args);setSelected(null);await load()}catch(x){setError(x instanceof Error?x.message:'Não foi possível registrar a venda.')}finally{setBusy(false)}}
 const noun=mode==='raffle'?'número':'cartela'
 return <div className="space-y-5">{error&&<p role="alert" className="rounded-xl border border-red-900 bg-red-950/30 p-3 text-red-300">{error}</p>}<div className="grid gap-3 sm:grid-cols-3"><Metric label="Disponíveis" value={items.filter(i=>i.status==='available').length}/><Metric label="Reservados" value={items.filter(i=>i.status==='reserved').length}/><Metric label="Vendidos" value={items.filter(i=>i.status==='sold').length}/></div><Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black text-white">{mode==='raffle'?'Números da rifa':'Cartelas temáticas'}</h2><p className="text-sm text-slate-400">Selecione um {noun} disponível para reservar ou vender.</p></div><Input className="max-w-xs" value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar ${noun} ou comprador`}/></div><div className={`mt-4 grid gap-2 ${mode==='raffle'?'grid-cols-5 sm:grid-cols-10':'sm:grid-cols-2 lg:grid-cols-3'}`}>{filtered.map(i=><button type="button" key={i.id} onClick={()=>setSelected(i)} className={`min-h-12 rounded-xl border p-2 font-black ${i.status==='sold'?'border-emerald-700 bg-emerald-950 text-emerald-200':i.status==='reserved'?'border-amber-700 bg-amber-950 text-amber-200':'border-slate-700 bg-slate-950 text-white hover:border-slate-400'}`}>{'number'in i?i.number:i.code}</button>)}</div>{!items.length&&<p className="mt-4 text-sm text-slate-400">O organizador ainda não gerou {mode==='raffle'?'os números':'as cartelas'}.</p>}</Card>{selected&&<div className="fixed inset-0 z-[130] grid place-items-center bg-black/75 p-4" role="dialog" aria-modal="true"><Card className="w-full max-w-md"><h2 className="text-xl font-black text-white">{'number'in selected?`Número ${selected.number}`:`Cartela ${selected.code}`}</h2><form onSubmit={save} className="mt-4 space-y-3"><label className="block text-sm font-semibold text-slate-200">Situação<Select name="status" defaultValue={selected.status}><option value="available">Disponível</option><option value="reserved">Reservado</option><option value="sold">Vendido</option></Select></label><Field name="name" label="Comprador" defaultValue={selected.buyer_name}/><Field name="phone" label="Telefone" defaultValue={selected.buyer_phone}/><Field name="email" label="E-mail para área do comprador" type="email" defaultValue={selected.buyer_email}/><Field name="price" label="Valor" type="number" defaultValue={selected.sold_price}/><div className="flex gap-2"><Button disabled={busy}>{busy?'Salvando…':'Confirmar'}</Button><Button type="button" variant="secondary" onClick={()=>setSelected(null)}>Cancelar</Button></div></form></Card></div>}</div>
}
function Field({name,label,type='text',defaultValue}:{name:string;label:string;type?:string;defaultValue:string|number|null}){return <label className="block text-sm font-semibold text-slate-200">{label}<Input name={name} type={type} min={type==='number'?0:undefined} step={type==='number'?'.01':undefined} maxLength={type==='number'?undefined:160} defaultValue={defaultValue??''}/></label>}
function Metric({label,value}:{label:string;value:number}){return <Card><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-3xl font-black text-white">{value}</p></Card>}
