import { useEffect, useMemo, useState, type ChangeEvent } from 'react'
import { useAuth } from '@/app/providers/AuthProvider'
import { usePlatformBrand } from '@/components/brand/PlatformBrandProvider'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { Input } from '@/components/ui/Input'
import { Select } from '@/components/ui/Select'
import { getMasterDashboard, getPlatformBranding, listMasterWorkspaces, updatePlatformBranding, updateWorkspaceAccess, uploadPlatformLogo, type MasterDashboard, type MasterWorkspaceRow, type PlatformBranding } from './masterService'

const emptyDashboard: MasterDashboard = { workspaces_total: 0, workspaces_active: 0, events_total: 0, users_total: 0, cards_sold: 0, sales_amount: 0 }

export function MasterPage() {
  const { signOut } = useAuth(); const { refreshBranding } = usePlatformBrand()
  const [dashboard, setDashboard] = useState<MasterDashboard>(emptyDashboard)
  const [workspaces, setWorkspaces] = useState<MasterWorkspaceRow[]>([])
  const [branding, setBranding] = useState<PlatformBranding>({ app_name: 'BINGOUP', main_logo_path: null, auth_logo_path: null, compact_logo_path: null, public_panel_logo_path: null })
  const [query, setQuery] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  async function load() { setError(null); try { const [d, w, b] = await Promise.all([getMasterDashboard(), listMasterWorkspaces(), getPlatformBranding()]); setDashboard(d); setWorkspaces(w); setBranding(b) } catch { setError('Não foi possível carregar o painel Master.') } }
  useEffect(() => { void load() }, [])
  const filtered = useMemo(() => workspaces.filter(w => `${w.name} ${w.slug} ${w.owner_email ?? ''}`.toLowerCase().includes(query.toLowerCase())), [workspaces, query])
  async function saveLicense(row: MasterWorkspaceRow, patch: Partial<MasterWorkspaceRow>) { setBusy(true); setNotice(null); setError(null); const next = { ...row, ...patch }; try { await updateWorkspaceAccess({ workspaceId: row.workspace_id, accessStatus: next.access_status, eventLimit: next.event_limit, validUntil: next.valid_until, notes: next.notes }); setNotice(`Acesso de ${row.name} atualizado.`); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível atualizar o acesso.') } finally { setBusy(false) } }
  async function chooseLogo(kind: 'main' | 'auth' | 'compact' | 'public-panel', event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setBusy(true); setError(null); try { const path = await uploadPlatformLogo(kind, file); const next = { ...branding, ...(kind === 'main' ? { main_logo_path: path } : kind === 'auth' ? { auth_logo_path: path } : kind === 'compact' ? { compact_logo_path: path } : { public_panel_logo_path: path }) }; await updatePlatformBranding(next); setBranding(next); await refreshBranding(); setNotice('Logo atualizada em todo o BINGOUP.') } catch { setError('Não foi possível enviar a logo.') } finally { setBusy(false); event.target.value = '' } }
  async function saveBrandName() { setBusy(true); try { await updatePlatformBranding(branding); await refreshBranding(); setNotice('Identidade global atualizada.') } catch { setError('Não foi possível salvar a identidade.') } finally { setBusy(false) } }
  return <main className="bingoup-app min-h-dvh bg-slate-950 p-4 text-slate-100 md:p-6">
    <div className="mx-auto max-w-[1500px] space-y-6">
      <header className="flex flex-col gap-4 rounded-3xl border border-red-900/40 bg-slate-900/80 p-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.24em] text-red-400">BINGOUP MASTER</p><h1 className="mt-1 text-3xl font-black">Controle da plataforma</h1><p className="mt-1 text-sm text-slate-400">Licenças, organizadores, limites, suspensão geral e identidade visual.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={() => void load()}>Atualizar</Button><Button variant="secondary" onClick={() => void signOut()}>Sair</Button></div></header>
      {notice && <div className="rounded-2xl border border-emerald-800 bg-emerald-950/30 p-3 text-sm text-emerald-300">{notice}</div>}{error && <div className="rounded-2xl border border-red-800 bg-red-950/30 p-3 text-sm text-red-300">{error}</div>}
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Organizadores" value={dashboard.workspaces_total}/><Metric label="Ativos" value={dashboard.workspaces_active}/><Metric label="Eventos" value={dashboard.events_total}/><Metric label="Usuários" value={dashboard.users_total}/><Metric label="Cartelas vendidas" value={dashboard.cards_sold}/><Metric label="Volume registrado" value={money(dashboard.sales_amount)}/></section>
      <Card className="p-5"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h2 className="text-xl font-black text-white">Acessos e licenças</h2><p className="text-sm text-slate-400">Venda 1 evento, um pacote de eventos ou acesso ilimitado. Suspender aqui bloqueia o workspace sem apagar dados.</p></div><Input className="md:max-w-sm" placeholder="Buscar organizador ou e-mail" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="mt-4 space-y-3">{filtered.map(row => <WorkspaceLicenseCard key={row.workspace_id} row={row} busy={busy} onSave={saveLicense}/>)}</div></Card>
      <Card className="p-5"><h2 className="text-xl font-black text-white">Identidade global</h2><p className="mt-1 text-sm text-slate-400">Controle as logos usadas no login, menu, ícone compacto e painel público. Alterações valem para toda a plataforma.</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><label className="text-sm font-bold">Nome do aplicativo<Input className="mt-1" value={branding.app_name} onChange={e => setBranding(v => ({ ...v, app_name: e.target.value }))}/></label><div className="flex items-end"><Button disabled={busy} onClick={() => void saveBrandName()}>Salvar identidade</Button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><LogoUpload label="Logo principal" disabled={busy} onChange={e => void chooseLogo('main', e)}/><LogoUpload label="Logo do login" disabled={busy} onChange={e => void chooseLogo('auth', e)}/><LogoUpload label="Ícone compacto" disabled={busy} onChange={e => void chooseLogo('compact', e)}/><LogoUpload label="Logo da TV pública" disabled={busy} onChange={e => void chooseLogo('public-panel', e)}/></div></Card>
      <div className="rounded-2xl border border-amber-800/50 bg-amber-950/20 p-4 text-sm text-amber-200"><strong>Segurança:</strong> esta área só responde para uma conta cadastrada como <code>platform_owner</code> no Supabase. Ser organizador, administrador, vendedor ou operador não concede acesso Master.</div>
    </div>
  </main>
}

function WorkspaceLicenseCard({ row, busy, onSave }: { row: MasterWorkspaceRow; busy: boolean; onSave: (row: MasterWorkspaceRow, patch: Partial<MasterWorkspaceRow>) => Promise<void> }) {
  const [status, setStatus] = useState(row.access_status); const [limit, setLimit] = useState(row.event_limit === null ? 'unlimited' : String(row.event_limit)); const [validUntil, setValidUntil] = useState(row.valid_until ? row.valid_until.slice(0, 10) : ''); const [notes, setNotes] = useState(row.notes ?? '')
  useEffect(() => { setStatus(row.access_status); setLimit(row.event_limit === null ? 'unlimited' : String(row.event_limit)); setValidUntil(row.valid_until ? row.valid_until.slice(0, 10) : ''); setNotes(row.notes ?? '') }, [row])
  const parsedLimit = limit === 'unlimited' ? null : Math.max(0, Number.parseInt(limit, 10) || 0)
  return <div className="rounded-2xl border border-slate-700 bg-slate-950/40 p-4"><div className="grid gap-4 xl:grid-cols-[1.3fr_.7fr_.7fr_.8fr_1fr_auto] xl:items-end"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-white">{row.name}</strong><span className={`rounded-full px-2 py-0.5 text-[11px] font-black ${row.access_status === 'active' ? 'bg-emerald-950 text-emerald-300' : 'bg-red-950 text-red-300'}`}>{row.access_status}</span></div><p className="mt-1 text-xs text-slate-500">{row.owner_email ?? 'sem e-mail'} · {row.slug}</p><p className="mt-2 text-xs text-slate-400">{row.events_total} evento(s) · {row.members_total} usuário(s) · {row.cards_sold} cartelas vendidas</p></div><label className="text-xs font-bold text-slate-300">Status<Select className="mt-1" value={status} onChange={e => setStatus(e.target.value as typeof status)}><option value="active">Ativo</option><option value="suspended">Suspenso</option><option value="expired">Expirado</option></Select></label><label className="text-xs font-bold text-slate-300">Limite de eventos<Input className="mt-1" type="number" min="0" placeholder="Vazio = ilimitado" value={limit === 'unlimited' ? '' : limit} onChange={e => setLimit(e.target.value === '' ? 'unlimited' : e.target.value)}/></label><label className="text-xs font-bold text-slate-300">Validade<Input className="mt-1" type="date" value={validUntil} onChange={e => setValidUntil(e.target.value)}/></label><label className="text-xs font-bold text-slate-300">Observação<Input className="mt-1" value={notes} onChange={e => setNotes(e.target.value)} placeholder="Ex.: pacote 3 eventos"/></label><Button disabled={busy} onClick={() => void onSave(row, { access_status: status, event_limit: parsedLimit, valid_until: validUntil ? new Date(`${validUntil}T23:59:59`).toISOString() : null, notes: notes || null })}>Salvar</Button></div></div>
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-white">{value}</p></div> }
function LogoUpload({ label, disabled, onChange }: { label: string; disabled: boolean; onChange: (event: ChangeEvent<HTMLInputElement>) => void }) { return <label className="cursor-pointer rounded-2xl border border-dashed border-slate-700 bg-slate-950/40 p-4 text-center text-sm font-bold text-slate-300 hover:border-red-600">{label}<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" disabled={disabled} onChange={onChange}/><span className="mt-2 block text-xs font-normal text-slate-500">Clique para substituir</span></label> }
function money(v: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(v || 0)) }
