import {useCallback,useEffect,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {supabase} from '@/services/supabase/client'

type SessionDiagnostic={session_id:string;workspace_name:string;event_name:string;event_status:string;session_name:string;session_number:number;session_status:string;called_numbers:number[];pending_candidates:Array<{id:string;card_code:string|null;game_position:number|null;detected_at:string}>}
async function loadDiagnostic(sessionId:string){const {data,error}=await supabase.rpc('master_get_draw_session_diagnostic',{target_session_id:sessionId});if(error)throw error;return data as SessionDiagnostic}
export function MasterDrawSessionPage(){const {sessionId}=useParams();const [data,setData]=useState<SessionDiagnostic|null>(null);const [error,setError]=useState<string|null>(null);const load=useCallback(async()=>{if(!sessionId)return;setError(null);try{setData(await loadDiagnostic(sessionId))}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a sessão.')}},[sessionId]);useEffect(()=>{void load()},[load]);return <div className="bingoup-app min-h-dvh bg-slate-950 p-4 text-white sm:p-6"><div className="mx-auto max-w-5xl space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="bingoup-eyebrow">BINGOUP MASTER</p><h1 className="text-2xl font-black">Diagnóstico da sessão</h1><p className="mt-1 text-sm text-slate-400">Sessão aberta localizada sem depender do organizador selecionado.</p></div><Link to="/master"><Button variant="secondary">Voltar ao Master</Button></Link></div>{error&&<div className="rounded-xl border border-red-800 bg-red-950/30 p-4 text-red-300">{error}</div>}{!data&&!error?<Card>Carregando…</Card>:data?<><Card><p className="text-xs font-bold uppercase text-slate-500">{data.workspace_name}</p><h2 className="mt-1 text-xl font-black">{data.event_name} · {data.session_name}</h2><p className="mt-1 text-sm text-slate-400">Evento {data.event_status} · sessão {data.session_status} · {data.called_numbers.length} bolas chamadas</p></Card><Card><h2 className="text-lg font-black">Conferências pendentes desta sessão</h2><div className="mt-3 space-y-2">{data.pending_candidates.length===0?<p className="text-sm text-slate-500">Nenhuma conferência pendente nesta sessão.</p>:data.pending_candidates.map(c=><div key={c.id} className="flex flex-col gap-2 rounded-xl border border-slate-800 bg-slate-950/40 p-3 sm:flex-row sm:items-center sm:justify-between"><div><b>{c.card_code??'Cartela'} · Jogo {c.game_position??'—'}</b><p className="mt-1 text-xs text-slate-500">Detectado em {new Date(c.detected_at).toLocaleString('pt-BR')}</p></div><Link to={`/master/conferencia/${c.id}`}><Button variant="secondary">Abrir conferência</Button></Link></div>)}</div></Card></>:null}</div></div>}
