import {useCallback,useEffect,useMemo,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {supabase} from '@/services/supabase/client'

export type WinnerRegistryRow={winner_id:string;session_id:string;session_number:number;round_name:string;prize_name:string;confirmed_at:string;confirmation_note:string|null;card_id:string;card_code:string;card_public_token:string;game_position:number;buyer_name:string|null;buyer_phone:string|null;buyer_email:string|null;buyer_notes:string|null;delivered:boolean;delivered_at:string|null;delivery_note:string|null}
type WinnerRegistry={event:{id:string;name:string;status:string};winners:WinnerRegistryRow[]}

async function getRegistry(eventId:string){const {data,error}=await supabase.rpc('get_event_winner_registry',{target_event_id:eventId});if(error)throw error;return data as WinnerRegistry}
async function setDelivery(winnerId:string,delivered:boolean,note?:string){const {error}=await supabase.rpc('set_winner_prize_delivery',{target_winner_id:winnerId,target_delivered:delivered,target_note:note?.trim()||null});if(error)throw error}

export function WinnerRegistryPage({operatorMode=false,eventIdOverride}:{operatorMode?:boolean;eventIdOverride?:string}={}){
  const params=useParams();const eventId=eventIdOverride??params.eventId??'';const [data,setData]=useState<WinnerRegistry|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState<string|null>(null);const [onlyPending,setOnlyPending]=useState(false)
  const load=useCallback(async()=>{if(!eventId)return;setLoading(true);setError('');try{setData(await getRegistry(eventId))}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar os ganhadores.')}finally{setLoading(false)}},[eventId]);useEffect(()=>{void load()},[load])
  const rows=useMemo(()=>onlyPending?(data?.winners??[]).filter(w=>!w.delivered):(data?.winners??[]),[data,onlyPending]);const delivered=(data?.winners??[]).filter(w=>w.delivered).length
  async function toggle(row:WinnerRegistryRow){const note=prompt(row.delivered?'Observação ao reabrir a entrega (opcional):':'Observação da entrega do prêmio (opcional):',row.delivery_note??'');if(note===null)return;setBusy(row.winner_id);setError('');try{await setDelivery(row.winner_id,!row.delivered,note);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar a entrega.')}finally{setBusy(null)}}
  if(loading)return <Card>Carregando ganhadores…</Card>
  return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold text-red-500">Premiação</p><h1 className="mt-1 text-3xl font-black">Ganhadores do evento</h1><p className="mt-2 text-sm text-slate-500">Veja quem ganhou cada prêmio, os dados de contato e acompanhe se o prêmio já foi entregue.</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>void load()}>Atualizar</Button><Link to={operatorMode?`/operador/${eventId}/sorteio`:`/eventos/${eventId}`}><Button variant="secondary">Voltar</Button></Link></div></div>{error&&<div className="rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
    <div className="grid gap-3 sm:grid-cols-3"><Stat label="Ganhadores confirmados" value={data?.winners.length??0}/><Stat label="Prêmios entregues" value={delivered}/><Stat label="A entregar" value={(data?.winners.length??0)-delivered}/></div>
    <Card><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black">{data?.event.name??'Evento'}</h2><p className="text-sm text-slate-500">Cada linha representa um jogo/cartela confirmado como ganhador.</p></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={onlyPending} onChange={e=>setOnlyPending(e.target.checked)}/> Mostrar somente prêmios a entregar</label></div></Card>
    <div className="space-y-3">{rows.map(row=><Card key={row.winner_id} className={row.delivered?'border-emerald-500/30':'border-amber-500/30'}><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-black ${row.delivered?'bg-emerald-100 text-emerald-800':'bg-amber-100 text-amber-800'}`}>{row.delivered?'PRÊMIO ENTREGUE':'A ENTREGAR'}</span><span className="text-xs font-bold text-slate-500">Rodada {row.session_number}</span></div><h3 className="mt-2 text-xl font-black">{row.buyer_name||'Comprador sem nome informado'}</h3><p className="mt-1 text-sm font-semibold text-red-500">{row.prize_name} · {row.round_name}</p><div className="mt-4 grid gap-x-6 gap-y-3 sm:grid-cols-2 xl:grid-cols-3"><Info label="Cartela" value={`${row.card_code} · Jogo ${row.game_position}`}/><Info label="Telefone" value={row.buyer_phone||'Não informado'}/><Info label="E-mail" value={row.buyer_email||'Não informado'}/><Info label="Confirmado em" value={date(row.confirmed_at)}/><Info label="Entregue em" value={row.delivered_at?date(row.delivered_at):'Ainda não entregue'}/><Info label="Observação" value={row.delivery_note||row.confirmation_note||'—'}/></div>{row.buyer_notes&&<p className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-600">Dados da venda: {row.buyer_notes}</p>}</div><div className="grid shrink-0 gap-2 sm:grid-cols-2 lg:w-52 lg:grid-cols-1"><a href={`/c/${row.card_public_token}`} target="_blank" rel="noreferrer"><Button variant="secondary" className="w-full">Abrir cartela</Button></a>{row.buyer_phone&&<a href={`https://wa.me/${row.buyer_phone.replace(/\D/g,'')}`} target="_blank" rel="noreferrer"><Button variant="secondary" className="w-full">Chamar no WhatsApp</Button></a>}<Button disabled={busy===row.winner_id} onClick={()=>void toggle(row)}>{row.delivered?'Marcar como não entregue':'Marcar prêmio entregue'}</Button></div></div></Card>)}{rows.length===0&&<Card><p className="py-6 text-center text-sm text-slate-500">{onlyPending?'Nenhum prêmio pendente de entrega.':'Nenhum ganhador confirmado neste evento.'}</p></Card>}</div>
  </div>
}
function Stat({label,value}:{label:string;value:number}){return <Card><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></Card>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-[11px] font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-semibold">{value}</p></div>}
function date(value:string){return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value))}
