import { useCallback,useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { useWorkspace } from '@/app/providers/WorkspaceProvider'
import { getWorkspaceDashboard,type WorkspaceDashboard } from '@/features/history/historyService'

export function DashboardPage(){
  const {currentWorkspace}=useWorkspace();const [data,setData]=useState<WorkspaceDashboard|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  const load=useCallback(async()=>{if(!currentWorkspace)return;setLoading(true);setError('');try{setData(await getWorkspaceDashboard(currentWorkspace.id))}catch(e:any){setError(e?.message??'Não foi possível carregar o painel.')}finally{setLoading(false)}},[currentWorkspace])
  useEffect(()=>{void load()},[load])
  return <div className="space-y-6"><section className="bingoup-page-head"><div><p className="bingoup-eyebrow">Organizador ativo</p><h1>Olá, {currentWorkspace?.name}! <span aria-hidden="true">👋</span></h1><p>Bem-vindo ao seu painel de controle. Aqui você acompanha toda a operação do bingo.</p></div><div className="flex flex-wrap gap-3"><Link to="/historico"><Button variant="secondary">Histórico</Button></Link><Link to="/eventos/novo"><Button>+ Novo evento</Button></Link></div></section>
  {loading?<Card><p>Atualizando indicadores...</p></Card>:error?<Card><p className="font-semibold text-red-400">{error}</p><Button className="mt-4" onClick={()=>void load()}>Tentar novamente</Button></Card>:data&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon="calendar" title="Eventos ativos" value={data.events_active} note={`${data.events_total} no total`}/><Stat icon="grid" title="Cartelas vendidas" value={data.cards_sold} note={`${data.cards_issued} emitidas`}/><Stat icon="money" title="Total vendido" value={money(data.sales_amount)} note={`${data.sales_completed} vendas concluídas`}/><Stat icon="trophy" title="Vencedores" value={data.winners} note={`${data.draw_sessions} sessão(ões) de sorteio`}/></div><div className="grid gap-5 xl:grid-cols-[1.2fr_.9fr]"><Card className="bingoup-panel"><div className="flex items-center justify-between gap-3"><div><h2>Eventos recentes</h2><p>Acesse rapidamente a operação ou o relatório de cada evento.</p></div><Link to="/eventos" className="bingoup-link">Ver todos →</Link></div><div className="mt-5 grid gap-3">{data.recent_events.map(e=><div key={e.id} className="bingoup-event-row"><div><strong>{e.name}</strong><p>{e.cards_sold}/{e.cards_issued} vendidas · {money(e.sales_amount)}</p></div><div className="flex flex-wrap gap-2"><Link to={`/eventos/${e.id}`}><Button variant="secondary">Abrir</Button></Link><Link to={`/eventos/${e.id}/historico`}><Button variant="secondary">Relatório</Button></Link></div></div>)}{data.recent_events.length===0&&<div className="bingoup-empty"><div className="bingoup-empty-icon">+</div><strong>Você ainda não criou nenhum evento.</strong><p>Crie seu primeiro evento para começar.</p><Link to="/eventos/novo"><Button className="mt-4">+ Criar primeiro evento</Button></Link></div>}</div></Card><Card className="bingoup-panel"><h2>Acesso rápido</h2><p>Atalhos para as ações mais usadas no dia do evento.</p><div className="mt-4 divide-y divide-slate-700/60"><Quick to="/eventos/novo" title="Novo evento" note="Crie e configure um novo evento de bingo"/><Quick to="/cartelas" title="Gerar cartelas" note="Acesse as cartelas e lotes do evento"/><Quick to="/vendas" title="Registrar venda" note="Venda cartelas e registre compradores"/><Quick to="/sorteio" title="Iniciar sorteio" note="Realize sorteios e acompanhe ao vivo"/></div></Card></div><div className="bingoup-trust"><div><strong>Sistema seguro e auditável</strong><p>Operações, vendas e sorteios ficam registrados para conferência.</p></div><img src="/brand/bingoup-icon.png" alt=""/></div></>}</div>
}
function Stat({icon,title,value,note}:{icon:string;title:string;value:string|number;note:string}){return <Card className="bingoup-stat"><div className="bingoup-stat-icon">{icon==='money'?'$':icon==='trophy'?'★':icon==='calendar'?'▦':'▦'}</div><div><p>{title}</p><strong>{value}</strong><small>{note}</small></div></Card>}
function Quick({to,title,note}:{to:string;title:string;note:string}){return <Link to={to} className="bingoup-quick"><span><strong>{title}</strong><small>{note}</small></span><b>›</b></Link>}
function money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value||0))}
