import { useCallback,useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { useWorkspace } from '@/app/providers/WorkspaceProvider'
import { getWorkspaceDashboard,type WorkspaceDashboard } from '@/features/history/historyService'

export function DashboardPage(){
  const {currentWorkspace}=useWorkspace();const [data,setData]=useState<WorkspaceDashboard|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
  const load=useCallback(async()=>{if(!currentWorkspace)return;setLoading(true);setError('');try{setData(await getWorkspaceDashboard(currentWorkspace.id))}catch(e:any){setError(e?.message??'Não foi possível carregar o painel.')}finally{setLoading(false)}},[currentWorkspace])
  useEffect(()=>{void load()},[load])
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-emerald-700">Organizador ativo</p><h1 className="mt-1 text-3xl font-black tracking-tight">{currentWorkspace?.name}</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">Visão operacional com dados reais de eventos, cartelas, vendas, sorteios e vencedores.</p></div><div className="flex gap-2"><Link to="/historico"><Button variant="secondary">Histórico</Button></Link><Link to="/eventos/novo"><Button>Novo evento</Button></Link></div></div>
  {loading?<Card><p className="text-sm text-slate-600">Atualizando indicadores...</p></Card>:error?<Card><p className="font-semibold text-red-700">{error}</p><Button className="mt-4" onClick={()=>void load()}>Tentar novamente</Button></Card>:data&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Eventos ativos" value={data.events_active} note={`${data.events_total} no total`}/><Stat title="Cartelas vendidas" value={data.cards_sold} note={`${data.cards_issued} emitidas`}/><Stat title="Total vendido" value={money(data.sales_amount)} note={`${data.sales_completed} vendas concluídas`}/><Stat title="Vencedores" value={data.winners} note={`${data.draw_sessions} sessão(ões) de sorteio`}/></div><Card><div className="flex items-center justify-between"><div><h2 className="font-bold">Eventos recentes</h2><p className="text-sm text-slate-500">Acesse rapidamente a operação ou o relatório de cada evento.</p></div><Link to="/eventos" className="text-sm font-semibold text-emerald-700">Ver todos</Link></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{data.recent_events.map(e=><div key={e.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{e.name}</p><p className="mt-1 text-xs text-slate-500">{e.cards_sold}/{e.cards_issued} vendidas · {money(e.sales_amount)}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{e.status}</span></div><div className="mt-4 flex gap-2"><Link to={`/eventos/${e.id}`}><Button variant="secondary">Abrir</Button></Link><Link to={`/eventos/${e.id}/historico`}><Button variant="secondary">Relatório</Button></Link></div></div>)}{data.recent_events.length===0&&<p className="text-sm text-slate-500">Crie o primeiro evento para começar.</p>}</div></Card></>}</div>
}
function Stat({title,value,note}:{title:string;value:string|number;note:string}){return <Card><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-3xl font-black">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></Card>}
function money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value||0))}
