import type { CSSProperties } from 'react'
import type { BingoRuleSet, CardTemplate } from '@/types/database'
import { getCardLayoutPreset } from '@/domain/cards/layouts'
import { DEFAULT_GAME_STYLE, parseCardTemplateOptions, type CardGameStyleOptions, type CardTemplateOptions, type CardWildcardOptions } from '@/domain/cards/templateOptions'
import { getCardAssetUrl } from '@/features/card-config/cardConfigService'
import { WildcardSymbol } from './WildcardSymbol'

type Props={format:1|2|3;layoutKey:string;eventName?:string;seriesCode?:string;sequenceNumber?:number;codePadding?:number;rule?:BingoRuleSet|null;template?:CardTemplate;previewOptions?:CardTemplateOptions;localArtworkUrl?:string|null;localWildcardUrl?:string|null}
export function CardTemplatePreview({format,layoutKey,rule,template,previewOptions,localArtworkUrl,localWildcardUrl}:Props){
 const preset=getCardLayoutPreset(layoutKey,format);const options=previewOptions??parseCardTemplateOptions(template?.options);const art=options.artwork;const artworkUrl=localArtworkUrl??getCardAssetUrl(art?.path);const wildcard=options.wildcard??{kind:'star',scale:1};const style=options.gameStyle??DEFAULT_GAME_STYLE;const wildcardUrl=localWildcardUrl??(wildcard.kind==='custom'?getCardAssetUrl(wildcard.path):null)
 return <div className="rounded-3xl border border-slate-700 bg-slate-950/65 p-3"><div className="mx-auto max-w-md"><div className="relative aspect-[210/297] overflow-hidden rounded-xl border border-slate-300 bg-white shadow-2xl">
   {artworkUrl&&<img src={artworkUrl} alt="Arte da cartela" className="absolute inset-0 h-full w-full max-w-none" style={{objectFit:art?.fit??'cover',transform:`translate(${art?.offsetX??0}%,${art?.offsetY??0}%) scale(${art?.zoom??1})`,transformOrigin:'center'}}/>}
   {!artworkUrl&&<div className="absolute inset-0 grid place-items-center bg-[linear-gradient(135deg,#fff_0%,#f8fafc_100%)] px-8 text-center text-xs font-semibold text-slate-400">Importe uma arte criada a partir do gabarito. O BINGOUP colocará apenas os jogos por cima.</div>}
   {preset?.gameAreas.map((area,index)=><div key={index} className="absolute flex items-center justify-center" style={{left:`${area.x}%`,top:`${area.y}%`,width:`${area.width}%`,height:`${area.height}%`}}><div style={{width:`${style.widthScale*100}%`,height:`${style.heightScale*100}%`}}><MiniGame rule={rule} wildcard={wildcard} wildcardUrl={wildcardUrl} style={style}/></div></div>)}
 </div></div><div className="mt-3 text-center text-xs text-slate-400">{preset?.name??layoutKey} · {format} em 1 · proporção A4</div></div>
}
function MiniGame({rule,wildcard,wildcardUrl,style}:{rule?:BingoRuleSet|null;wildcard:CardWildcardOptions;wildcardUrl:string|null;style:CardGameStyleOptions}){const rows=rule?.grid_rows??5,cols=rule?.grid_columns??5,labels=rule?.column_definitions?.length===cols?rule.column_definitions.map(c=>c.label):['B','I','N','G','O'].slice(0,cols),cells=buildPreviewCells(rule,rows,cols);const common:CSSProperties={borderColor:style.gridColor,borderWidth:style.gridLineWidth,fontFamily:fontFamily(style.numberFont)};return <div className="h-full overflow-hidden" style={{border:`${style.gridLineWidth}px solid ${style.gridColor}`,borderRadius:`${style.cornerRadius}px`,background:style.cellBackground}}><div className="grid h-full text-center" style={{gridTemplateColumns:`repeat(${cols},minmax(0,1fr))`,gridTemplateRows:`${style.headerHeight}% repeat(${rows},minmax(0,1fr))`,gap:`${style.cellGap}px`,background:style.gridColor}}>{labels.map(l=><b key={l} className="grid min-h-0 place-items-center" style={{...common,background:style.headerBackground,color:style.headerTextColor,fontFamily:fontFamily(style.headerFont),fontWeight:style.headerBold?800:400,fontSize:`clamp(5px,${.7*style.headerScale}vw,${9*style.headerScale}px)`}}>{l}</b>)}{cells.map((v,i)=><span key={i} className="grid min-h-0 place-items-center" style={{...common,background:style.cellBackground,color:style.numberColor,fontWeight:style.numberBold?800:400,fontSize:`clamp(5px,${.72*style.numberScale}vw,${10*style.numberScale}px)`}}>{v===null?(wildcardUrl?<img src={wildcardUrl} className="max-h-[80%] max-w-[80%] object-contain" alt=""/>:<WildcardSymbol config={wildcard}/>):String(v).padStart(2,'0')}</span>)}</div></div>}
function fontFamily(font:CardGameStyleOptions['numberFont']){return font==='times'?'"Times New Roman", Times, serif':font==='courier'?'"Courier New", Courier, monospace':'Arial, Helvetica, sans-serif'}
function buildPreviewCells(rule:BingoRuleSet|null|undefined,rows:number,cols:number){const total=rows*cols,center=rule?.free_center?Math.floor(total/2):-1,result:Array<number|null>=[];for(let i=0;i<total;i++){if(i===center){result.push(null);continue}const c=i%cols,r=Math.floor(i/cols),d=rule?.column_definitions?.[c];result.push(d?d.min+((r*3+c)%Math.max(1,d.max-d.min+1)):((i*7)%Math.max(1,rule?.total_balls??75))+1)}return result}
export function previewPropsFromTemplate(template:CardTemplate|undefined){return template?{template}: {}}
