import type { CSSProperties } from 'react'
import type { EventWithSettings } from '@/types/database'
import type { PhysicalCardView } from '@/features/cards/cardService'
import { getCardLayoutPreset } from '@/domain/cards/layouts'
import { DEFAULT_GAME_STYLE, parseCardTemplateOptions, type CardGameStyleOptions } from '@/domain/cards/templateOptions'
import { getCardAssetUrl } from '@/features/card-config/cardConfigService'
import { WildcardSymbol } from './WildcardSymbol'

type Props={card:PhysicalCardView;event:EventWithSettings}
export function PrintableCard({card}:Props){const template=card.template,options=parseCardTemplateOptions(template.options),preset=getCardLayoutPreset(template.layout_key,Math.min(3,card.physical_format) as 1|2|3),art=options.artwork,wildcard=options.wildcard??{kind:'star',scale:1},style=options.gameStyle??DEFAULT_GAME_STYLE,artUrl=getCardAssetUrl(art?.path)
 return <article className="print-card print-art-card">
  {artUrl&&<img className="print-artwork" src={artUrl} alt="" style={{objectFit:art?.fit??'cover',transform:`translate(${art?.offsetX??0}%,${art?.offsetY??0}%) scale(${art?.zoom??1})`,transformOrigin:'center'}}/>}
  {preset?.gameAreas.map((area,index)=>{const game=card.games[index];if(!game)return null;const left=area.x+area.width*(1-style.widthScale)/2,top=area.y+area.height*(1-style.heightScale)/2;return <div key={game.position} className="print-game-zone" style={{left:`${left}%`,top:`${top}%`,width:`${area.width*style.widthScale}%`,height:`${area.height*style.heightScale}%`}}><Game game={game.definition} cols={card.rule.grid_columns} labels={card.rule.column_definitions.map(c=>c.label)} wildcard={wildcard} style={style}/></div>})}
 </article>}
function Game({game,cols,labels,wildcard,style}:{game:PhysicalCardView['games'][number]['definition'];cols:number;labels:string[];wildcard:ReturnType<typeof parseCardTemplateOptions>['wildcard'];style:CardGameStyleOptions}){const safeWildcard=wildcard??{kind:'star',scale:1};const rows=Math.ceil(game.cells.length/cols);const common:CSSProperties={borderColor:style.gridColor,borderWidth:style.gridLineWidth};return <section className="print-game" style={{borderRadius:`${style.cornerRadius}px`,overflow:'hidden',border:`${style.gridLineWidth}px solid ${style.gridColor}`}}><div className="print-grid" style={{gridTemplateColumns:`repeat(${cols},minmax(0,1fr))`,gridTemplateRows:`${style.headerHeight}% repeat(${rows},minmax(0,1fr))`,gap:`${style.cellGap}px`,background:'transparent'}}>{labels.length===cols&&labels.map(l=><b key={l} className="print-head" style={{...common,background:style.headerBackground,color:style.headerTextColor,fontFamily:fontFamily(style.headerFont),fontWeight:style.headerBold?800:400,fontSize:`clamp(${7*style.headerScale}px,${1.18*style.headerScale}vw,${18*style.headerScale}px)`}}>{l}</b>)}{game.cells.map((n,i)=><span key={i} className="print-cell" style={{...common,background:withOpacity(style.cellBackground,style.cellBackgroundOpacity),color:style.numberColor,fontFamily:fontFamily(style.numberFont),fontWeight:style.numberBold?800:400,fontSize:`clamp(${7*style.numberScale}px,${1.18*style.numberScale}vw,${18*style.numberScale}px)`}}>{n===null?<WildcardSymbol config={safeWildcard}/>:String(n).padStart(2,'0')}</span>)}</div></section>}
function fontFamily(font:CardGameStyleOptions['numberFont']){return font==='times'?'"Times New Roman", Times, serif':font==='courier'?'"Courier New", Courier, monospace':'Arial, Helvetica, sans-serif'}

function withOpacity(hex:string,opacity:number){const v=hex.replace('#','');const n=parseInt(v,16);const r=(n>>16)&255,g=(n>>8)&255,b=n&255;return `rgba(${r},${g},${b},${Math.max(0,Math.min(1,opacity))})`}
