import {useCallback,useEffect,useMemo,useState,type Dispatch,type SetStateAction} from 'react'
import {useWorkspace} from '@/app/providers/WorkspaceProvider'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {Input} from '@/components/ui/Input'
import {StatusBadge} from '@/components/ui/StatusBadge'
import {createOperatorInvitation,listOperatorTeam,listOperatorWorkspaceEvents,setOperatorAssignments,setOperatorStatus,type OperatorEventOption,type OperatorTeamRow} from './operatorService'

export function OperatorsPage(){
  const {currentWorkspace}=useWorkspace();const [events,setEvents]=useState<OperatorEventOption[]>([]);const [operators,setOperators]=useState<OperatorTeamRow[]>([]);const [email,setEmail]=useState('');const [selectedEvents,setSelectedEvents]=useState<string[]>([]);const [editing,setEditing]=useState<string|null>(null);const [editEvents,setEditEvents]=useState<string[]>([]);const [notice,setNotice]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false)
  const canManage=currentWorkspace?.membership.role==='organizer_owner'||currentWorkspace?.membership.role==='organizer_admin'
  const load=useCallback(async()=>{if(!currentWorkspace||!canManage)return;setError(null);try{const [ev,team]=await Promise.all([listOperatorWorkspaceEvents(currentWorkspace.id),listOperatorTeam(currentWorkspace.id)]);setEvents(ev);setOperators(team)}catch(e:any){setError(e?.message||'Não foi possível carregar os operadores.')}},[currentWorkspace,canManage])
  useEffect(()=>{void load()},[load])
  const activeCount=useMemo(()=>operators.filter(item=>item.status==='active').length,[operators])
  const toggle=(id:string,setter:Dispatch<SetStateAction<string[]>>)=>setter(value=>value.includes(id)?value.filter(x=>x!==id):[...value,id])
  async function invite(){if(!currentWorkspace||!email.trim()||selectedEvents.length===0)return;setBusy(true);setError(null);setNotice(null);try{const token=await createOperatorInvitation(currentWorkspace.id,email,selectedEvents);const link=`${window.location.origin}/convites/operador/${token}`;await navigator.clipboard.writeText(link).catch(()=>undefined);setNotice(`Convite criado e copiado. Envie este link ao operador: ${link}`);setEmail('');setSelectedEvents([])}catch(e:any){setError(e?.message||'Não foi possível criar o convite.')}finally{setBusy(false)}}
  async function copyOperatorCenter(){const link=`${window.location.origin}/operador`;try{await navigator.clipboard.writeText(link);setNotice(`Link da Central do operador copiado: ${link}`)}catch{setNotice(`Central do operador: ${link}`)}}
  async function saveAssignments(userId:string){if(!currentWorkspace)return;setBusy(true);try{await setOperatorAssignments(currentWorkspace.id,userId,editEvents);setEditing(null);setNotice('Eventos do operador atualizados.');await load()}catch(e:any){setError(e?.message||'Não foi possível atualizar os eventos.')}finally{setBusy(false)}}
  async function changeStatus(userId:string,status:'active'|'suspended'|'revoked'){if(!currentWorkspace)return;const label=status==='active'?'reativar':status==='suspended'?'suspender':'revogar';if(!confirm(`Deseja ${label} este operador?`))return;setBusy(true);try{await setOperatorStatus(currentWorkspace.id,userId,status);await load()}catch(e:any){setError(e?.message||'Não foi possível alterar o operador.')}finally{setBusy(false)}}
  if(!currentWorkspace)return null
  if(!canManage)return <Card><h1 className="text-xl font-black text-white">Operadores de sorteio</h1><p className="mt-2 text-sm text-slate-400">Somente proprietário ou administrador pode gerenciar operadores.</p></Card>
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-red-400">Equipe do sorteio</p><h1 className="mt-1 text-3xl font-black text-white">Operadores de sorteio</h1><p className="mt-2 max-w-3xl text-sm text-slate-400">O operador recebe somente os eventos escolhidos e pode operar sorteio, conferência, premiação da rodada e aparência da TV. Ele não recebe acesso a vendas, criação de cartelas, exclusão de evento ou administração.</p></div>{notice&&<div className="rounded-2xl border border-emerald-800/60 bg-emerald-950/30 p-4 text-sm text-emerald-300">{notice}</div>}{error&&<div className="rounded-2xl border border-red-900/60 bg-red-950/30 p-4 text-sm text-red-300">{error}</div>}
  <div className="grid gap-4 sm:grid-cols-2"><Metric label="Operadores" value={operators.length}/><Metric label="Ativos" value={activeCount}/></div>
  <Card><h2 className="text-lg font-black text-white">Convidar operador</h2><p className="mt-1 text-sm text-slate-400">Selecione pelo menos um evento. O link funciona com a conta do mesmo e-mail informado.</p><div className="mt-4 grid gap-4 lg:grid-cols-[minmax(260px,.7fr)_1.3fr]"><label className="text-sm font-semibold text-slate-200">E-mail<Input className="mt-1" type="email" value={email} placeholder="operador@email.com" onChange={e=>setEmail(e.target.value)}/></label><div><p className="text-sm font-semibold text-slate-200">Eventos autorizados</p><div className="mt-2 flex flex-wrap gap-2">{events.map(ev=><label key={ev.id} className={`cursor-pointer rounded-xl border px-3 py-2 text-sm ${selectedEvents.includes(ev.id)?'border-red-500 bg-red-950/30 text-white':'border-slate-700 text-slate-300'}`}><input className="mr-2" type="checkbox" checked={selectedEvents.includes(ev.id)} onChange={()=>toggle(ev.id,setSelectedEvents)}/>{ev.name}</label>)}{events.length===0&&<span className="text-sm text-slate-500">Nenhum evento disponível.</span>}</div></div></div><div className="mt-4 flex flex-wrap gap-2"><Button disabled={busy||!email.trim()||selectedEvents.length===0} onClick={()=>void invite()}>Criar convite e copiar link</Button><Button variant="secondary" onClick={()=>void copyOperatorCenter()}>Copiar link da área do operador</Button></div><p className="mt-3 text-xs text-slate-500">Use o link do convite na primeira entrada. Depois que o convite for aceito, o operador pode entrar sempre por <strong>/operador</strong> e verá somente os eventos liberados para ele.</p></Card>
  <Card><div className="flex items-end justify-between gap-3"><div><h2 className="text-lg font-black text-white">Operadores cadastrados</h2><p className="text-sm text-slate-400">O acesso é revogável e sempre limitado aos eventos marcados.</p></div><Button variant="secondary" onClick={()=>void load()}>Atualizar</Button></div><div className="mt-4 space-y-3">{operators.map(item=><div key={item.user_id} className="rounded-2xl border border-slate-700 bg-slate-950/30 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-white">{item.display_name||item.email||'Operador'}</strong><StatusBadge tone={item.status==='active'?'success':item.status==='suspended'?'warning':'neutral'}>{item.status==='active'?'Ativo':item.status==='suspended'?'Suspenso':'Revogado'}</StatusBadge></div><p className="mt-1 text-xs text-slate-500">{item.email}</p><p className="mt-2 text-xs text-slate-500">Eventos: {item.event_ids.length?item.event_ids.map(id=>events.find(ev=>ev.id===id)?.name||'Evento').join(', '):'nenhum'}</p></div><div className="flex flex-wrap gap-2">{item.status==='active'?<Button variant="secondary" onClick={()=>void changeStatus(item.user_id,'suspended')}>Suspender</Button>:<Button variant="secondary" onClick={()=>void changeStatus(item.user_id,'active')}>Reativar</Button>}<Button variant="secondary" onClick={()=>{setEditing(item.user_id);setEditEvents(item.event_ids)}}>Eventos</Button>{item.status!=='revoked'&&<Button variant="secondary" onClick={()=>void changeStatus(item.user_id,'revoked')}>Revogar</Button>}</div></div>{editing===item.user_id&&<div className="mt-4 border-t border-slate-800 pt-4"><p className="text-sm font-bold text-slate-200">Eventos autorizados</p><div className="mt-2 flex flex-wrap gap-2">{events.map(ev=><label key={ev.id} className={`cursor-pointer rounded-xl border px-3 py-2 text-sm ${editEvents.includes(ev.id)?'border-red-500 bg-red-950/30 text-white':'border-slate-700 text-slate-300'}`}><input className="mr-2" type="checkbox" checked={editEvents.includes(ev.id)} onChange={()=>toggle(ev.id,setEditEvents)}/>{ev.name}</label>)}</div><div className="mt-3 flex gap-2"><Button disabled={busy||editEvents.length===0} onClick={()=>void saveAssignments(item.user_id)}>Salvar eventos</Button><Button variant="secondary" onClick={()=>setEditing(null)}>Cancelar</Button></div></div>}</div>)}{operators.length===0&&<p className="rounded-xl border border-slate-800 p-4 text-sm text-slate-500">Nenhum operador cadastrado ainda.</p>}</div></Card></div>
}
function Metric({label,value}:{label:string;value:number}){return <Card><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-white">{value}</p></Card>}
