import {useCallback,useEffect,useState,type ReactNode} from 'react'
import {Link,useParams} from 'react-router-dom'
import {useWorkspace} from '@/app/providers/WorkspaceProvider'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {Select} from '@/components/ui/Select'
import {DEFAULT_PUBLIC_PANEL_APPEARANCE,normalizePublicPanelAppearance,PUBLIC_PANEL_ANIMATION_INTENSITIES,PUBLIC_PANEL_ANIMATION_INTENSITY_LABELS,PUBLIC_PANEL_BALL_ANIMATIONS,PUBLIC_PANEL_BALL_ANIMATION_LABELS,PUBLIC_PANEL_BOARD_STYLES,PUBLIC_PANEL_BOARD_STYLE_LABELS,PUBLIC_PANEL_COLOR_KEYS,PUBLIC_PANEL_COLOR_LABELS,PUBLIC_PANEL_THEMES,PUBLIC_PANEL_THEME_DESCRIPTIONS,PUBLIC_PANEL_THEME_LABELS,PUBLIC_PANEL_THEME_PALETTES,PUBLIC_PANEL_VICTORY_ANIMATIONS,PUBLIC_PANEL_VICTORY_ANIMATION_LABELS,type PublicPanelAppearance} from '@/domain/draw/publicPanelAppearance'
import type {EventSettings} from '@/types/database'
import {getOperatorPanelEvent,updateOperatorPublicPanel} from './operatorService'

export function OperatorPanelSettingsPage(){
  const {eventId=''}=useParams();const {currentWorkspace}=useWorkspace();const [eventName,setEventName]=useState('');const [settings,setSettings]=useState<EventSettings|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState<string|null>(null);const [error,setError]=useState<string|null>(null)
  const load=useCallback(async()=>{if(!currentWorkspace||!eventId)return;setLoading(true);setError(null);try{const value=await getOperatorPanelEvent(currentWorkspace.id,eventId);setEventName(value.event.name);setSettings(value.settings)}catch(e:any){setError(e?.message||'Você não possui acesso a este painel.')}finally{setLoading(false)}},[currentWorkspace,eventId])
  useEffect(()=>{void load()},[load])
  const appearance=normalizePublicPanelAppearance((settings?.settings as Record<string,unknown>|undefined)?.public_panel_appearance??DEFAULT_PUBLIC_PANEL_APPEARANCE)
  async function saveSettings(patch:Partial<EventSettings>){if(!settings)return;setBusy(true);setError(null);try{await updateOperatorPublicPanel(eventId,patch);setSettings(prev=>prev?{...prev,...patch}:prev);setNotice('Configuração da TV salva.')}catch(e:any){setError(e?.message||'Não foi possível salvar.')}finally{setBusy(false)}}
  async function saveAppearance(patch:Partial<PublicPanelAppearance>){if(!settings)return;setBusy(true);setError(null);try{const next={...appearance,...patch};await updateOperatorPublicPanel(eventId,{appearance:next});setSettings(prev=>prev?{...prev,settings:{...(prev.settings??{}),public_panel_appearance:next}}:prev);setNotice('Visual da TV salvo.')}catch(e:any){setError(e?.message||'Não foi possível salvar o visual.')}finally{setBusy(false)}}
  if(loading)return <Card>Carregando painel…</Card>
  if(!settings)return <div className="space-y-4"><div className="rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error||'Painel indisponível.'}</div><Link to="/sorteio"><Button variant="secondary">Voltar aos sorteios</Button></Link></div>
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-red-500">Operação da TV</p><h1 className="mt-1 text-3xl font-black">Painel público</h1><p className="mt-2 text-sm text-slate-500">{eventName} · somente aparência e informações exibidas na TV.</p></div><div className="flex gap-2"><Link to={`/eventos/${eventId}/sorteio`}><Button>Voltar ao sorteio</Button></Link><Link to="/sorteio"><Button variant="secondary">Eventos</Button></Link></div></div>{notice&&<div className="rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</div>}{error&&<div className="rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <Card><h2 className="text-lg font-black">O que aparece na TV</h2><label className="mt-4 block text-sm font-semibold">Contato do evento<input type="text" value={appearance.event_contact} disabled={busy} maxLength={80} placeholder="Ex.: WhatsApp (11) 99999-9999" onChange={e=>void saveAppearance({event_contact:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"/><span className="mt-1 block text-xs font-normal text-slate-500">Aparece identificado como contato do evento, separado da marca BINGOUP.</span></label><div className="mt-4 grid gap-2 sm:grid-cols-2"><Toggle label="Mostrar último número" checked={settings.public_panel_show_last_number} disabled={busy} onChange={v=>void saveSettings({public_panel_show_last_number:v})}/><Toggle label="Mostrar números sorteados" checked={settings.public_panel_show_called_numbers} disabled={busy} onChange={v=>void saveSettings({public_panel_show_called_numbers:v})}/><Toggle label="Mostrar andamento" checked={settings.public_panel_show_progress} disabled={busy} onChange={v=>void saveSettings({public_panel_show_progress:v})}/><Toggle label="Mostrar jogos próximos" checked={settings.public_panel_show_near_winners} disabled={busy} onChange={v=>void saveSettings({public_panel_show_near_winners:v})}/><Toggle label="Mostrar nome da rodada" checked={appearance.show_round_name} disabled={busy} onChange={v=>void saveAppearance({show_round_name:v})}/><Toggle label="Mostrar prêmio atual" checked={appearance.show_prize} disabled={busy} onChange={v=>void saveAppearance({show_prize:v})}/><Toggle label="Mostrar últimas bolas" checked={appearance.show_recent_numbers} disabled={busy} onChange={v=>void saveAppearance({show_recent_numbers:v})}/><Toggle label="Mostrar contadores" checked={appearance.show_counters} disabled={busy} onChange={v=>void saveAppearance({show_counters:v})}/></div></Card>
  <Card><h2 className="text-lg font-black">Tema e comportamento</h2><p className="mt-1 text-sm text-slate-500">Trocar o visual não altera nenhuma regra do sorteio.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Tema"><Select value={appearance.theme} disabled={busy} onChange={e=>void saveAppearance({theme:e.target.value as PublicPanelAppearance['theme']})}>{PUBLIC_PANEL_THEMES.map(v=><option key={v} value={v}>{PUBLIC_PANEL_THEME_LABELS[v]}</option>)}</Select><small className="text-slate-500">{PUBLIC_PANEL_THEME_DESCRIPTIONS[appearance.theme]}</small></Field><Field label="Estilo do quadro"><Select value={appearance.board_style} disabled={busy} onChange={e=>void saveAppearance({board_style:e.target.value as PublicPanelAppearance['board_style']})}>{PUBLIC_PANEL_BOARD_STYLES.map(v=><option key={v} value={v}>{PUBLIC_PANEL_BOARD_STYLE_LABELS[v]}</option>)}</Select></Field><Field label="Animação da bola"><Select value={appearance.ball_animation} disabled={busy} onChange={e=>void saveAppearance({ball_animation:e.target.value as PublicPanelAppearance['ball_animation']})}>{PUBLIC_PANEL_BALL_ANIMATIONS.map(v=><option key={v} value={v}>{PUBLIC_PANEL_BALL_ANIMATION_LABELS[v]}</option>)}</Select></Field><Field label="Animação da vitória"><Select value={appearance.victory_animation} disabled={busy} onChange={e=>void saveAppearance({victory_animation:e.target.value as PublicPanelAppearance['victory_animation']})}>{PUBLIC_PANEL_VICTORY_ANIMATIONS.map(v=><option key={v} value={v}>{PUBLIC_PANEL_VICTORY_ANIMATION_LABELS[v]}</option>)}</Select></Field><Field label="Intensidade"><Select value={appearance.animation_intensity} disabled={busy} onChange={e=>void saveAppearance({animation_intensity:e.target.value as PublicPanelAppearance['animation_intensity']})}>{PUBLIC_PANEL_ANIMATION_INTENSITIES.map(v=><option key={v} value={v}>{PUBLIC_PANEL_ANIMATION_INTENSITY_LABELS[v]}</option>)}</Select></Field><div className="flex items-end"><Toggle label="Moldura animada" checked={appearance.animated_frame} disabled={busy} onChange={v=>void saveAppearance({animated_frame:v})}/></div></div></Card>
  <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black">Cores personalizadas</h2><p className="text-sm text-slate-500">As cores são independentes do formato do tema.</p></div><Toggle label="Personalizar cores" checked={appearance.use_custom_colors} disabled={busy} onChange={v=>void saveAppearance({use_custom_colors:v})}/></div>{appearance.use_custom_colors&&<><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{PUBLIC_PANEL_COLOR_KEYS.map(key=><ColorControl key={key} label={PUBLIC_PANEL_COLOR_LABELS[key]} value={(appearance.custom_colors[key]??PUBLIC_PANEL_THEME_PALETTES[appearance.theme][key])} onChange={value=>void saveAppearance({custom_colors:{...appearance.custom_colors,[key]:value}})} disabled={busy}/>)}</div><Button className="mt-4" variant="secondary" disabled={busy} onClick={()=>void saveAppearance({custom_colors:{}})}>Restaurar cores do tema</Button></>}</Card></div>
}
function Toggle({label,checked,onChange,disabled}:{label:string;checked:boolean;onChange:(value:boolean)=>void;disabled?:boolean}){return <label className="flex cursor-pointer items-center justify-between gap-4 rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm font-semibold"><span>{label}</span><input type="checkbox" className="size-4" checked={checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/></label>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-1 text-sm font-semibold">{label}{children}</label>}
function ColorControl({label,value,onChange,disabled}:{label:string;value:string;onChange:(value:string)=>void;disabled?:boolean}){return <label className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-semibold"><input type="color" value={value} disabled={disabled} onChange={e=>onChange(e.target.value)} className="h-10 w-12 cursor-pointer rounded border-0 bg-transparent"/><span className="min-w-0 flex-1">{label}</span><code className="text-xs text-slate-500">{value}</code></label>}
