import {useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import {usePlatformBrand} from '@/components/brand/PlatformBrandProvider'
import {getPublicMarketingData,type PublicMarketingData,type PublicMarketingPlan} from './marketingService'

export function MarketingPage(){
  const {app_name,mainLogoUrl}=usePlatformBrand();const [data,setData]=useState<PublicMarketingData>({whatsapp_number:null,plans:[]})
  useEffect(()=>{void getPublicMarketingData().then(setData).catch(()=>{})},[])
  const whatsapp=useMemo(()=>{const n=(data.whatsapp_number??'').replace(/\D/g,'');return n?`https://wa.me/${n}?text=${encodeURIComponent(`Olá! Quero conhecer os planos do ${app_name} e contratar acesso.`)}`:null},[data.whatsapp_number,app_name])
  return <main className="marketing-page min-h-dvh bg-[#090c11] text-white">
    <header className="marketing-nav"><a href="#inicio" className="marketing-brand"><img src={mainLogoUrl} alt={app_name}/></a><nav><a href="#recursos">Recursos</a><a href="#como-funciona">Como funciona</a><a href="#planos">Planos</a></nav><div className="marketing-actions"><Link to="/entrar" className="marketing-btn secondary">Entrar</Link><Link to="/criar-conta" className="marketing-btn primary">Começar agora</Link></div></header>
    <section id="inicio" className="marketing-hero"><div className="marketing-hero-copy"><span className="marketing-kicker">BINGO PROFISSIONAL · SIMPLES DE OPERAR</span><h1>Seu bingo inteiro em um só sistema.</h1><p>Crie cartelas, organize vendas, acompanhe vendedores, opere o sorteio na TV, confira ganhadores e mantenha tudo registrado — do primeiro lote ao último prêmio.</p><div className="marketing-cta"><Link to="/criar-conta" className="marketing-btn primary large">Criar minha conta</Link>{whatsapp&&<a href={whatsapp} target="_blank" rel="noreferrer" className="marketing-btn whatsapp large">Falar no WhatsApp</a>}</div><small>Cadastro rápido. A liberação comercial é feita pela nossa equipe.</small></div><div className="marketing-hero-panel"><div className="marketing-live"><span>AO VIVO</span><b>43</b><small>Último número sorteado</small></div><div className="marketing-mini-grid">{['Cartelas prontas para impressão','Vendas por equipe','Sorteio automático ou manual','Conferência de ganhadores'].map(x=><div key={x}>✓ {x}</div>)}</div></div></section>
    <section id="recursos" className="marketing-section"><div className="marketing-section-head"><span>DO INÍCIO AO FIM</span><h2>Tudo que você precisa para realizar o evento.</h2><p>Uma operação organizada para o responsável pelo bingo, para a equipe e também para o comprador.</p></div><div className="marketing-feature-grid"><Feature title="Cartelas profissionais" text="Crie lotes, personalize arte, grade, coringa e gere PDF otimizado para impressão."/><Feature title="Vendedores conectados" text="Convide vendedores e controle exatamente em quais eventos cada pessoa pode vender."/><Feature title="Operadores de sorteio" text="Delegue o sorteio sem entregar acesso administrativo ao seu evento ou à sua conta."/><Feature title="Painel público para TV" text="Tela própria para projetor ou televisão, com temas, números chamados, rodada e premiação."/><Feature title="Conferência automática" text="Somente cartelas vendidas participam. O sistema interrompe o sorteio quando encontra um possível ganhador."/><Feature title="Comprador digital" text="O comprador acompanha suas cartelas, o sorteio e os prêmios diretamente pela própria conta."/></div></section>
    <section id="como-funciona" className="marketing-section alt"><div className="marketing-section-head"><span>FLUXO SIMPLES</span><h2>Do planejamento ao prêmio em poucos passos.</h2></div><div className="marketing-steps"><Step n="01" title="Crie o evento" text="Configure o bingo, a identidade visual e as regras que serão usadas."/><Step n="02" title="Gere e venda" text="Produza as cartelas, imprima ou venda digitalmente e acompanhe a distribuição."/><Step n="03" title="Faça o sorteio" text="Use modo automático ou manual, acompanhe a TV pública e deixe a conferência trabalhar junto com você."/><Step n="04" title="Registre os ganhadores" text="Confirme os prêmios, guarde dados para entrega e mantenha o histórico do evento."/></div></section>
    <section className="marketing-proof"><div><b>1 conta</b><span>para organizar seus eventos</span></div><div><b>Vários acessos</b><span>vendedores e operadores independentes</span></div><div><b>75 bolas</b><span>com controle de repetição e auditoria</span></div><div><b>100% online</b><span>PC, celular, tablet e TV</span></div></section>
    <section id="planos" className="marketing-section"><div className="marketing-section-head"><span>ESCOLHA SEU ACESSO</span><h2>Planos para quem faz um evento ou vários.</h2><p>Você cria a conta e nossa equipe libera o plano escolhido manualmente.</p></div><div className="marketing-plan-grid">{data.plans.length?data.plans.map((p,i)=><Plan key={p.code} plan={p} featured={i===Math.min(1,data.plans.length-1)} whatsapp={whatsapp}/>):<><Fallback name="Evento avulso" text="Acesso completo para realizar um evento."/><Fallback name="Pacote de eventos" text="Ideal para quem organiza bingos durante o ano."/><Fallback name="Ilimitado" text="Para operações que realizam eventos continuamente."/></>}</div></section>
    <section className="marketing-final"><span>PRONTO PARA ORGANIZAR SEU PRÓXIMO BINGO?</span><h2>Crie sua conta e fale com nossa equipe para liberar o acesso.</h2><div className="marketing-cta"><Link to="/criar-conta" className="marketing-btn primary large">Criar conta</Link>{whatsapp&&<a href={whatsapp} target="_blank" rel="noreferrer" className="marketing-btn whatsapp large">Quero contratar</a>}</div></section>
    <footer className="marketing-footer"><img src={mainLogoUrl} alt={app_name}/><p>Plataforma de gestão e operação de bingo computadorizado.</p><div><Link to="/entrar">Entrar</Link><Link to="/criar-conta">Criar conta</Link></div></footer>
  </main>
}
function Feature({title,text}:{title:string;text:string}){return <article className="marketing-feature"><span>●</span><h3>{title}</h3><p>{text}</p></article>}
function Step({n,title,text}:{n:string;title:string;text:string}){return <article className="marketing-step"><b>{n}</b><div><h3>{title}</h3><p>{text}</p></div></article>}
function Plan({plan,featured,whatsapp}:{plan:PublicMarketingPlan;featured:boolean;whatsapp:string|null}){return <article className={`marketing-plan ${featured?'featured':''}`}><span>{featured?'MAIS ESCOLHIDO':'PLANO'}</span><h3>{plan.name}</h3><p>{plan.description||'Acesso ao BINGOUP para sua operação.'}</p><strong>{plan.price_cents==null?'Consulte':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(plan.price_cents/100)}</strong><small>{plan.billing_label|| (plan.event_limit==null?'sem limite':`${plan.event_limit} evento(s)`)}</small>{whatsapp?<a href={whatsapp} target="_blank" rel="noreferrer" className="marketing-btn primary">Quero este plano</a>:<Link to="/criar-conta" className="marketing-btn primary">Solicitar acesso</Link>}</article>}
function Fallback({name,text}:{name:string;text:string}){return <article className="marketing-plan"><span>PLANO</span><h3>{name}</h3><p>{text}</p><strong>Consulte</strong><small>liberação manual</small><Link to="/criar-conta" className="marketing-btn primary">Solicitar acesso</Link></article>}
