import {useCallback,useEffect,useMemo,useState} from 'react'
import {useWorkspace} from '@/app/providers/WorkspaceProvider'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {Input} from '@/components/ui/Input'
import {StatusBadge} from '@/components/ui/StatusBadge'
import {createSellerInvitation,listPendingSellerInvitations,listSellerTeam,listWorkspaceEvents,setSellerAssignments,setSellerStatus,type PendingSellerInvitation,type SellerEventOption,type SellerTeamRow} from './sellerService'

export function SellersPage(){
 const{currentWorkspace}=useWorkspace();const[events,setEvents]=useState<SellerEventOption[]>([]),[sellers,setSellers]=useState<SellerTeamRow[]>([]),[pending,setPending]=useState<PendingSellerInvitation[]>([]),[email,setEmail]=useState(''),[selectedEvents,setSelectedEvents]=useState<string[]>([]),[editing,setEditing]=useState<string|null>(null),[editEvents,setEditEvents]=useState<string[]>([]),[notice,setNotice]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false)
 const canManage=currentWorkspace?.membership.role==='organizer_owner'||currentWorkspace?.membership.role==='organizer_admin'
 const load=useCallback(async()=>{if(!currentWorkspace||!canManage)return;setError(null);try{const[ev,team,invites]=await Promise.all([listWorkspaceEvents(currentWorkspace.id),listSellerTeam(currentWorkspace.id),listPendingSellerInvitations(currentWorkspace.id)]);setEvents(ev);setSellers(team);setPending(invites)}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar os vendedores.')}},[currentWorkspace,canManage])
 useEffect(()=>{void load()},[load]);const activeCount=useMemo(()=>sellers.filter(s=>s.status==='active').length,[sellers])
 function toggle(id:string,values:string[],setValues:(value:string[])=>void){setValues(values.includes(id)?values.filter(x=>x!==id):[...values,id])}
 async function invite(){if(!currentWorkspace||!email.trim())return;setBusy(true);setError(null);setNotice(null);try{const token=await createSellerInvitation(currentWorkspace.id,email,selectedEvents),link=`${window.location.origin}/convites/vendedor/${token}`;await navigator.clipboard.writeText(link).catch(()=>undefined);setNotice(`Convite criado e exibido abaixo. Link copiado: ${link}`);setEmail('');setSelectedEvents([]);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar o convite.')}finally{setBusy(false)}}
 async function copyLink(token:string){const link=`${window.location.origin}/convites/vendedor/${token}`;await navigator.clipboard.writeText(link).catch(()=>undefined);setNotice(`Link do convite: ${link}`)}
 async function copySellerCenter(){const link=`${window.location.origin}/venda`;await navigator.clipboard.writeText(link).catch(()=>undefined);setNotice(`Central do vendedor: ${link}`)}
 async function saveAssignments(userId:string){if(!currentWorkspace)return;setBusy(true);try{await setSellerAssignments(currentWorkspace.id,userId,editEvents);setEditing(null);setNotice('Eventos do vendedor atualizados.');await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar os eventos.')}finally{setBusy(false)}}
 async function changeStatus(userId:string,status:'active'|'suspended'|'revoked'){if(!currentWorkspace||!window.confirm(`Deseja ${status==='active'?'reativar':status==='suspended'?'suspender':'revogar'} este vendedor?`))return;setBusy(true);try{await setSellerStatus(currentWorkspace.id,userId,status);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível alterar o vendedor.')}finally{setBusy(false)}}
 if(!currentWorkspace)return null;if(!canManage)return <Card><h1 className="text-xl font-black text-white">Vendedores</h1><p className="mt-2 text-sm text-slate-400">Somente proprietário ou administrador pode gerenciar vendedores.</p></Card>
 return <div className="space-y-6"><header><p className="text-sm font-semibold text-red-400">Equipe comercial</p><h1 className="mt-1 text-3xl font-black text-white">Vendedores</h1><p className="mt-2 text-sm text-slate-400">Confira convites pendentes, vendedores cadastrados e os eventos liberados para cada pessoa.</p></header>{notice&&<div className="rounded-2xl border border-emerald-800/60 bg-emerald-950/30 p-4 text-sm text-emerald-300">{notice}</div>}{error&&<div role="alert" className="rounded-2xl border border-red-900/60 bg-red-950/30 p-4 text-sm text-red-300">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Cadastrados" value={sellers.length}/><Metric label="Ativos" value={activeCount}/><Metric label="Aguardando aceite" value={pending.filter(i=>i.status==='pending').length}/><Metric label="Vendas da equipe" value={sellers.reduce((a,s)=>a+s.completed_sales,0)}/></div>
 <Card><h2 className="text-lg font-black text-white">Convidar vendedor</h2><p className="mt-1 text-sm text-slate-400">Escolha os eventos agora. O acesso é ativado depois que o vendedor aceitar o convite usando o mesmo e-mail.</p><div className="mt-4 grid gap-4 lg:grid-cols-[minmax(260px,.7fr)_1.3fr]"><label className="text-sm font-semibold text-slate-200">E-mail<Input className="mt-1" type="email" value={email} placeholder="vendedor@email.com" onChange={e=>setEmail(e.target.value)}/></label><EventPicker events={events} selected={selectedEvents} onToggle={id=>toggle(id,selectedEvents,setSelectedEvents)}/></div><div className="mt-4 flex flex-wrap gap-2"><Button disabled={busy||!email.trim()} onClick={()=>void invite()}>{busy?'Criando…':'Criar convite e copiar link'}</Button><Button variant="secondary" onClick={()=>void copySellerCenter()}>Copiar link da área do vendedor</Button></div><p className="mt-3 text-xs text-slate-500">Use o link do convite na primeira entrada. Depois do aceite, o vendedor acessa a Central do vendedor.</p></Card>
 {pending.length>0&&<Card><h2 className="text-lg font-black text-white">Convites aguardando aceite</h2><div className="mt-4 space-y-3">{pending.map(i=><div key={i.id} className="flex flex-col justify-between gap-3 rounded-2xl border border-amber-800/60 bg-amber-950/20 p-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-white">{i.email}</strong><StatusBadge tone={i.status==='pending'?'warning':'neutral'}>{i.status==='pending'?'Aguardando aceite':'Expirado'}</StatusBadge></div><p className="mt-2 text-sm text-slate-300">Eventos: {eventNames(i.event_ids,events)}</p><p className="mt-1 text-xs text-slate-500">Expira em {new Date(i.expires_at).toLocaleString('pt-BR')}</p></div><Button variant="secondary" onClick={()=>void copyLink(i.token)}>Copiar convite</Button></div>)}</div></Card>}
 <Card><div className="flex items-end justify-between gap-3"><div><h2 className="text-lg font-black text-white">Equipe cadastrada</h2><p className="text-sm text-slate-400">Todos os vendedores deste organizador e suas liberações.</p></div><Button variant="secondary" onClick={()=>void load()}>Atualizar</Button></div><div className="mt-4 space-y-3">{sellers.map(s=><SellerRow key={s.user_id} seller={s} events={events} editing={editing===s.user_id} editEvents={editEvents} busy={busy} onEdit={()=>{setEditing(s.user_id);setEditEvents(s.event_ids)}} onToggle={id=>toggle(id,editEvents,setEditEvents)} onSave={()=>void saveAssignments(s.user_id)} onCancel={()=>setEditing(null)} onStatus={status=>void changeStatus(s.user_id,status)}/>)}{!sellers.length&&<p className="rounded-xl border border-slate-800 p-4 text-sm text-slate-500">Nenhum vendedor aceitou o convite ainda.</p>}</div></Card></div>
}
function SellerRow({seller:s,events,editing,editEvents,busy,onEdit,onToggle,onSave,onCancel,onStatus}:{seller:SellerTeamRow;events:SellerEventOption[];editing:boolean;editEvents:string[];busy:boolean;onEdit:()=>void;onToggle:(id:string)=>void;onSave:()=>void;onCancel:()=>void;onStatus:(s:'active'|'suspended'|'revoked')=>void}){return <div className="rounded-2xl border border-slate-700 bg-slate-950/30 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-white">{s.display_name||s.email||'Vendedor'}</strong><StatusBadge tone={s.status==='active'?'success':s.status==='suspended'?'warning':'neutral'}>{s.status==='active'?'Ativo':s.status==='suspended'?'Suspenso':'Revogado'}</StatusBadge></div><p className="mt-1 text-xs text-slate-500">{s.email}</p><p className="mt-2 text-sm text-slate-300">{s.completed_sales} venda(s) · {money(s.completed_amount)}</p><p className="mt-1 text-sm text-slate-300">Eventos liberados: {eventNames(s.event_ids,events)}</p></div><div className="flex flex-wrap gap-2">{s.status==='active'?<Button variant="secondary" onClick={()=>onStatus('suspended')}>Suspender</Button>:<Button variant="secondary" onClick={()=>onStatus('active')}>Reativar</Button>}<Button variant="secondary" onClick={onEdit}>Editar eventos</Button>{s.status!=='revoked'&&<Button variant="secondary" onClick={()=>onStatus('revoked')}>Revogar</Button>}</div></div>{editing&&<div className="mt-4 border-t border-slate-800 pt-4"><EventPicker events={events} selected={editEvents} onToggle={onToggle}/><div className="mt-3 flex gap-2"><Button disabled={busy} onClick={onSave}>Salvar eventos</Button><Button variant="secondary" onClick={onCancel}>Cancelar</Button></div></div>}</div>}
function EventPicker({events,selected,onToggle}:{events:SellerEventOption[];selected:string[];onToggle:(id:string)=>void}){return <div><p className="text-sm font-semibold text-slate-200">Eventos permitidos</p><div className="mt-2 flex flex-wrap gap-2">{events.map(e=><label key={e.id} className={`cursor-pointer rounded-xl border px-3 py-2 text-sm ${selected.includes(e.id)?'border-red-500 bg-red-950/30 text-white':'border-slate-700 text-slate-300'}`}><input className="mr-2" type="checkbox" checked={selected.includes(e.id)} onChange={()=>onToggle(e.id)}/>{e.name}</label>)}{!events.length&&<span className="text-sm text-slate-500">Nenhum evento disponível.</span>}</div></div>}
function eventNames(ids:string[],events:SellerEventOption[]){return ids.length?ids.map(id=>events.find(e=>e.id===id)?.name||'Evento indisponível').join(', '):'nenhum'}
function Metric({label,value}:{label:string;value:string|number}){return <Card><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-white">{value}</p></Card>}
function money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value)}
