import {useCallback,useEffect,useMemo,useState} from 'react'
import {useWorkspace} from '@/app/providers/WorkspaceProvider'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {Input} from '@/components/ui/Input'
import {StatusBadge} from '@/components/ui/StatusBadge'
import {createSellerInvitation,listSellerTeam,listWorkspaceEvents,setSellerAssignments,setSellerStatus,type SellerEventOption,type SellerTeamRow} from './sellerService'

export function SellersPage(){
  const {currentWorkspace}=useWorkspace();const [events,setEvents]=useState<SellerEventOption[]>([]);const [sellers,setSellers]=useState<SellerTeamRow[]>([]);const [email,setEmail]=useState('');const [selectedEvents,setSelectedEvents]=useState<string[]>([]);const [editing,setEditing]=useState<string|null>(null);const [editEvents,setEditEvents]=useState<string[]>([]);const [notice,setNotice]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false)
  const canManage=currentWorkspace?.membership.role==='organizer_owner'||currentWorkspace?.membership.role==='organizer_admin'
  const load=useCallback(async()=>{if(!currentWorkspace||!canManage)return;setError(null);try{const [ev,team]=await Promise.all([listWorkspaceEvents(currentWorkspace.id),listSellerTeam(currentWorkspace.id)]);setEvents(ev);setSellers(team)}catch(e:any){setError(e?.message||'Não foi possível carregar os vendedores.')}},[currentWorkspace,canManage])
  useEffect(()=>{void load()},[load])
  const activeCount=useMemo(()=>sellers.filter(s=>s.status==='active').length,[sellers])
  function toggleInviteEvent(id:string){setSelectedEvents(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
  function toggleEditEvent(id:string){setEditEvents(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
  async function invite(){if(!currentWorkspace||!email.trim())return;setBusy(true);setError(null);setNotice(null);try{const token=await createSellerInvitation(currentWorkspace.id,email,selectedEvents);const link=`${window.location.origin}/convites/vendedor/${token}`;await navigator.clipboard.writeText(link).catch(()=>undefined);setNotice(`Convite criado. Link copiado: ${link}`);setEmail('');setSelectedEvents([])}catch(e:any){setError(e?.message||'Não foi possível criar o convite.')}finally{setBusy(false)}}
  async function saveAssignments(userId:string){if(!currentWorkspace)return;setBusy(true);try{await setSellerAssignments(currentWorkspace.id,userId,editEvents);setEditing(null);setNotice('Eventos do vendedor atualizados.');await load()}catch(e:any){setError(e?.message||'Não foi possível atualizar os eventos.')}finally{setBusy(false)}}
  async function changeStatus(userId:string,status:'active'|'suspended'|'revoked'){if(!currentWorkspace)return;const label=status==='active'?'reativar':status==='suspended'?'suspender':'revogar';if(!window.confirm(`Deseja ${label} este vendedor?`))return;setBusy(true);try{await setSellerStatus(currentWorkspace.id,userId,status);await load()}catch(e:any){setError(e?.message||'Não foi possível alterar o vendedor.')}finally{setBusy(false)}}
  if(!currentWorkspace)return null
  if(!canManage)return <Card><h1 className="text-xl font-black text-white">Vendedores</h1><p className="mt-2 text-sm text-slate-400">Somente o proprietário ou administrador do organizador pode gerenciar vendedores.</p></Card>
  return <div className="space-y-6"><div><p className="text-sm font-semibold text-red-400">Equipe comercial</p><h1 className="mt-1 text-3xl font-black text-white">Vendedores</h1><p className="mt-2 text-sm text-slate-400">Convide vendedores, defina em quais eventos podem vender e acompanhe o total registrado por cada um.</p></div>{notice&&<div className="rounded-2xl border border-emerald-800/60 bg-emerald-950/30 p-4 text-sm text-emerald-300">{notice}</div>}{error&&<div className="rounded-2xl border border-red-900/60 bg-red-950/30 p-4 text-sm text-red-300">{error}</div>}
  <div className="grid gap-4 sm:grid-cols-3"><Metric label="Vendedores" value={sellers.length}/><Metric label="Ativos" value={activeCount}/><Metric label="Vendas da equipe" value={sellers.reduce((a,s)=>a+s.completed_sales,0)}/></div>
  <Card><h2 className="text-lg font-black text-white">Convidar vendedor</h2><p className="mt-1 text-sm text-slate-400">O vendedor entra com a própria conta e só recebe acesso aos eventos selecionados.</p><div className="mt-4 grid gap-4 lg:grid-cols-[minmax(260px,.7fr)_1.3fr]"><label className="text-sm font-semibold text-slate-200">E-mail<Input className="mt-1" type="email" value={email} placeholder="vendedor@email.com" onChange={e=>setEmail(e.target.value)}/></label><div><p className="text-sm font-semibold text-slate-200">Eventos permitidos</p><div className="mt-2 flex flex-wrap gap-2">{events.map(ev=><label key={ev.id} className={`cursor-pointer rounded-xl border px-3 py-2 text-sm ${selectedEvents.includes(ev.id)?'border-red-500 bg-red-950/30 text-white':'border-slate-700 text-slate-300'}`}><input className="mr-2" type="checkbox" checked={selectedEvents.includes(ev.id)} onChange={()=>toggleInviteEvent(ev.id)}/>{ev.name}</label>)}{events.length===0&&<span className="text-sm text-slate-500">Nenhum evento disponível.</span>}</div></div></div><Button className="mt-4" disabled={busy||!email.trim()} onClick={()=>void invite()}>Criar convite e copiar link</Button></Card>
  <Card><div className="flex items-end justify-between gap-3"><div><h2 className="text-lg font-black text-white">Equipe cadastrada</h2><p className="text-sm text-slate-400">Cada vendedor só pode operar nos eventos atribuídos.</p></div><Button variant="secondary" onClick={()=>void load()}>Atualizar</Button></div><div className="mt-4 space-y-3">{sellers.map(s=><div key={s.user_id} className="rounded-2xl border border-slate-700 bg-slate-950/30 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-white">{s.display_name||s.email||'Vendedor'}</strong><StatusBadge tone={s.status==='active'?'success':s.status==='suspended'?'warning':'neutral'}>{s.status==='active'?'Ativo':s.status==='suspended'?'Suspenso':'Revogado'}</StatusBadge></div><p className="mt-1 text-xs text-slate-500">{s.email}</p><p className="mt-2 text-sm text-slate-300">{s.completed_sales} venda(s) · {money(s.completed_amount)}</p><p className="mt-1 text-xs text-slate-500">Eventos: {s.event_ids.length?s.event_ids.map(id=>events.find(e=>e.id===id)?.name||'Evento').join(', '):'nenhum'}</p></div><div className="flex flex-wrap gap-2">{s.status==='active'?<Button variant="secondary" onClick={()=>void changeStatus(s.user_id,'suspended')}>Suspender</Button>:<Button variant="secondary" onClick={()=>void changeStatus(s.user_id,'active')}>Reativar</Button>}<Button variant="secondary" onClick={()=>{setEditing(s.user_id);setEditEvents(s.event_ids)}}>Eventos</Button>{s.status!=='revoked'&&<Button variant="secondary" onClick={()=>void changeStatus(s.user_id,'revoked')}>Revogar</Button>}</div></div>{editing===s.user_id&&<div className="mt-4 border-t border-slate-800 pt-4"><p className="text-sm font-bold text-slate-200">Eventos autorizados</p><div className="mt-2 flex flex-wrap gap-2">{events.map(ev=><label key={ev.id} className={`cursor-pointer rounded-xl border px-3 py-2 text-sm ${editEvents.includes(ev.id)?'border-red-500 bg-red-950/30 text-white':'border-slate-700 text-slate-300'}`}><input className="mr-2" type="checkbox" checked={editEvents.includes(ev.id)} onChange={()=>toggleEditEvent(ev.id)}/>{ev.name}</label>)}</div><div className="mt-3 flex gap-2"><Button disabled={busy} onClick={()=>void saveAssignments(s.user_id)}>Salvar eventos</Button><Button variant="secondary" onClick={()=>setEditing(null)}>Cancelar</Button></div></div>}</div>)}{sellers.length===0&&<p className="rounded-xl border border-slate-800 p-4 text-sm text-slate-500">Nenhum vendedor cadastrado ainda.</p>}</div></Card></div>
}
function Metric({label,value}:{label:string;value:string|number}){return <Card><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-white">{value}</p></Card>}
function money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value)}
