import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { useWorkspace } from '@/app/providers/WorkspaceProvider'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { Select } from '@/components/ui/Select'
import { StatusBadge } from '@/components/ui/StatusBadge'
import { CardTemplatePreview } from '@/components/cards/CardTemplatePreview'
import { getEvent } from '@/features/events/eventService'
import { slugify } from '@/utils/slug'
import { formatBigInt, physicalCardsWithoutGameReuse, uniqueGameCapacity, type ColumnDefinition } from '@/domain/cards/capacity'
import { getCardLayoutPreset, layoutsForFormat } from '@/domain/cards/layouts'
import { downloadLayoutGuidePng, optimizeArtwork, optimizeWildcard } from '@/domain/cards/artwork'
import { type ArtworkQuality, type CardTemplateOptions, type WildcardKind } from '@/domain/cards/templateOptions'
import { createCardTemplate, createRuleSet, ensureCardConfigDefaults, listCardTemplates, listRuleSets, setDefaultRule, setDefaultTemplate, toggleRule, toggleTemplate } from './cardConfigService'
import type { BingoEvent, BingoRuleSet, CardTemplate, EventWithSettings } from '@/types/database'

type Tab='rules'|'templates'
const STANDARD_COLUMNS:ColumnDefinition[]=[{label:'B',min:1,max:15,count:5},{label:'I',min:16,max:30,count:5},{label:'N',min:31,max:45,count:4},{label:'G',min:46,max:60,count:5},{label:'O',min:61,max:75,count:5}]
const DEFAULT_PATTERNS=[{code:'one_line',name:'1 linha',kind:'line'},{code:'two_lines',name:'2 linhas',kind:'two_lines'},{code:'full_card',name:'Cartela cheia',kind:'full_card'}]

export function CardConfigurationPage(){
 const {eventId}=useParams(); const [searchParams]=useSearchParams(); const {currentWorkspace}=useWorkspace(); const [event,setEvent]=useState<EventWithSettings|null>(null); const [rules,setRules]=useState<BingoRuleSet[]>([]); const [templates,setTemplates]=useState<CardTemplate[]>([]); const [tab,setTab]=useState<Tab>(searchParams.get('aba')==='layouts'?'templates':'rules'); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null)
 const load=useCallback(async()=>{if(!currentWorkspace||!eventId)return;setLoading(true);setError(null);try{await ensureCardConfigDefaults(eventId);const [ev,rs,ts]=await Promise.all([getEvent(currentWorkspace.id,eventId),listRuleSets(currentWorkspace.id,eventId),listCardTemplates(currentWorkspace.id,eventId)]);setEvent(ev);setRules(rs);setTemplates(ts)}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a configuração.')}finally{setLoading(false)}},[currentWorkspace,eventId])
 useEffect(()=>{void load()},[load])
 if(loading)return <Card>Carregando regras e templates…</Card>
 if(!event||!currentWorkspace||!eventId)return <Card><p className="text-red-700">{error??'Evento não encontrado.'}</p></Card>
 return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-bold text-emerald-700">Cartelas · configuração</p><h1 className="mt-1 text-3xl font-black">{event.name}</h1><p className="mt-2 text-sm text-slate-600">Defina a matemática do bingo e os layouts físicos antes da geração.</p></div><Link to={`/eventos/${eventId}`}><Button variant="secondary">Voltar ao evento</Button></Link></div>
 {notice&&<div className="rounded-2xl bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{notice}</div>}{error&&<div className="rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
 <div className="flex gap-2 rounded-2xl bg-slate-100 p-1"><button onClick={()=>setTab('rules')} className={`flex-1 rounded-xl px-4 py-2 text-sm font-bold ${tab==='rules'?'bg-white shadow-sm':'text-slate-600'}`}>Regras do bingo</button><button onClick={()=>setTab('templates')} className={`flex-1 rounded-xl px-4 py-2 text-sm font-bold ${tab==='templates'?'bg-white shadow-sm':'text-slate-600'}`}>Layouts das cartelas</button></div>
 {tab==='rules'?<RulesSection rules={rules} workspaceId={currentWorkspace.id} eventId={eventId} reload={load} notify={setNotice} fail={setError}/>:<TemplatesSection templates={templates} workspaceId={currentWorkspace.id} eventId={eventId} event={event} reload={load} notify={setNotice} fail={setError}/>}</div>
}

function RulesSection({rules,workspaceId,eventId,reload,notify,fail}:{rules:BingoRuleSet[];workspaceId:string;eventId:string;reload:()=>Promise<void>;notify:(s:string|null)=>void;fail:(s:string|null)=>void}){
 const [show,setShow]=useState(false)
 return <div className="space-y-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">Regras disponíveis</h2><p className="text-sm text-slate-600">A regra padrão será usada pelo gerador na próxima fase.</p></div><Button onClick={()=>setShow(v=>!v)}>{show?'Fechar':'Nova regra'}</Button></div>{show&&<RuleForm workspaceId={workspaceId} eventId={eventId} onDone={async()=>{setShow(false);notify('Regra criada.');await reload()}} fail={fail}/>}<div className="grid gap-4 lg:grid-cols-2">{rules.map(rule=><RuleCard key={rule.id} rule={rule} workspaceId={workspaceId} reload={reload} notify={notify} fail={fail}/>)}</div></div>
}
function RuleCard({rule,workspaceId,reload,notify,fail}:{rule:BingoRuleSet;workspaceId:string;reload:()=>Promise<void>;notify:(s:string|null)=>void;fail:(s:string|null)=>void}){
 const cap=uniqueGameCapacity({totalBalls:rule.total_balls,numbersPerGame:rule.numbers_per_game,distributionMode:rule.distribution_mode,columns:rule.column_definitions})
 return <Card><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2">{rule.is_default&&<StatusBadge tone="success">Padrão</StatusBadge>}<StatusBadge tone={rule.is_active?'neutral':'warning'}>{rule.is_active?'Ativa':'Inativa'}</StatusBadge></div><h3 className="mt-2 text-lg font-black">{rule.name}</h3><p className="text-sm text-slate-500">{rule.total_balls} bolas · grade {rule.grid_rows}×{rule.grid_columns} · {rule.numbers_per_game} números</p></div></div><div className="mt-4 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Jogos únicos possíveis</p><p className="mt-1 break-all text-xl font-black">{formatBigInt(cap)}</p><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><Capacity label="1 em 1" value={physicalCardsWithoutGameReuse(cap,1)}/><Capacity label="2 em 1" value={physicalCardsWithoutGameReuse(cap,2)}/><Capacity label="3 em 1" value={physicalCardsWithoutGameReuse(cap,3)}/></div><p className="mt-3 text-xs text-slate-500">Os limites acima não reutilizam nenhum jogo interno. Repetição controlada só será oferecida pelo gerador após esse limite.</p></div><div className="mt-4 flex flex-wrap gap-2">{!rule.is_default&&<Button variant="secondary" onClick={()=>void action(async()=>setDefaultRule(rule.id),'Regra definida como padrão.',reload,notify,fail)}>Definir padrão</Button>}<Button variant="secondary" onClick={()=>void action(async()=>toggleRule(workspaceId,rule.id,!rule.is_active),rule.is_active?'Regra desativada.':'Regra ativada.',reload,notify,fail)}>{rule.is_active?'Desativar':'Ativar'}</Button></div></Card>
}
function Capacity({label,value}:{label:string;value:bigint}){return <div className="rounded-xl bg-white p-2"><p className="font-bold">{label}</p><p className="mt-1 truncate text-slate-600" title={formatBigInt(value)}>{formatBigInt(value)}</p></div>}

function RuleForm({workspaceId,eventId,onDone,fail}:{workspaceId:string;eventId:string;onDone:()=>Promise<void>;fail:(s:string|null)=>void}){
 const [preset,setPreset]=useState<'75'|'custom'>('75'); const [name,setName]=useState('Bingo 75 bolas personalizado'); const [total,setTotal]=useState(75);const [rows,setRows]=useState(5);const [cols,setCols]=useState(5);const [free,setFree]=useState(true);const [mode,setMode]=useState<'any'|'column_ranges'>('column_ranges');const [columns,setColumns]=useState<ColumnDefinition[]>(STANDARD_COLUMNS);const [saving,setSaving]=useState(false)
 const numbers=rows*cols-(free?1:0); const capacity=useMemo(()=>uniqueGameCapacity({totalBalls:total,numbersPerGame:numbers,distributionMode:mode,columns}),[total,numbers,mode,columns])
 function choose(v:'75'|'custom'){setPreset(v);if(v==='75'){setName('Bingo 75 bolas personalizado');setTotal(75);setRows(5);setCols(5);setFree(true);setMode('column_ranges');setColumns(STANDARD_COLUMNS)}else{setName('Regra personalizada');setMode('any');setColumns([])}}
 async function submit(){setSaving(true);fail(null);try{await createRuleSet(workspaceId,eventId,{name,code:`${slugify(name).replaceAll('-','_')}_${Date.now().toString().slice(-5)}`,totalBalls:total,gridRows:rows,gridColumns:cols,numbersPerGame:numbers,freeCenter:free,distributionMode:mode,columns:mode==='column_ranges'?columns:[],winPatterns:DEFAULT_PATTERNS,isDefault:false});await onDone()}catch(e){fail(e instanceof Error?e.message:'Não foi possível criar a regra.')}finally{setSaving(false)}}
 return <Card className="border-emerald-200"><h3 className="text-lg font-black">Nova regra</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Base<Select className="mt-1" value={preset} onChange={e=>choose(e.target.value as '75'|'custom')}><option value="75">75 bolas, grade 5×5</option><option value="custom">Personalizada</option></Select></label><label className="text-sm font-semibold">Nome<Input className="mt-1" value={name} onChange={e=>setName(e.target.value)}/></label><NumberField label="Total de bolas" value={total} set={setTotal}/><NumberField label="Linhas" value={rows} set={setRows}/><NumberField label="Colunas" value={cols} set={setCols}/><label className="flex items-center gap-3 rounded-2xl border border-slate-200 p-3 text-sm font-semibold"><input type="checkbox" checked={free} onChange={e=>setFree(e.target.checked)}/>Casa livre central</label><label className="text-sm font-semibold sm:col-span-2">Distribuição<Select className="mt-1" value={mode} onChange={e=>{const v=e.target.value as 'any'|'column_ranges';setMode(v);if(v==='column_ranges'&&columns.length!==cols)setColumns(Array.from({length:cols},(_,i)=>({label:String(i+1),min:1,max:total,count:Math.floor(numbers/cols)+(i<numbers%cols?1:0)})))}}><option value="any">Qualquer combinação do universo</option><option value="column_ranges">Faixas por coluna</option></Select></label></div>{mode==='column_ranges'&&<ColumnEditor columns={columns} setColumns={setColumns}/>}<div className="mt-4 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-500">Capacidade calculada</p><p className="mt-1 text-lg font-black">{formatBigInt(capacity)} jogos únicos</p><p className="mt-1 text-xs text-slate-500">{numbers} números por jogo.</p></div><div className="mt-4 flex justify-end"><Button disabled={saving||!name.trim()} onClick={()=>void submit()}>{saving?'Salvando…':'Criar regra'}</Button></div></Card>
}
function NumberField({label,value,set}:{label:string;value:number;set:(n:number)=>void}){return <label className="text-sm font-semibold">{label}<Input className="mt-1" type="number" min={1} value={value} onChange={e=>set(Number(e.target.value))}/></label>}
function ColumnEditor({columns,setColumns}:{columns:ColumnDefinition[];setColumns:(v:ColumnDefinition[])=>void}){
 function patchLabel(i:number,value:string){setColumns(columns.map((c,index)=>index===i?{...c,label:value}:c))}
 function patchNumber(i:number,key:'min'|'max'|'count',value:number){setColumns(columns.map((c,index)=>index===i?{...c,[key]:value}:c))}
 return <div className="mt-4"><p className="text-sm font-black">Faixas por coluna</p><p className="mt-1 text-xs text-slate-500">As faixas não podem se sobrepor, para que a capacidade calculada permaneça exata.</p><div className="mt-2 grid gap-2">{columns.map((c,i)=><div key={i} className="grid grid-cols-4 gap-2"><Input aria-label="Letra" value={c.label} onChange={e=>patchLabel(i,e.target.value)}/><Input aria-label="Mínimo" type="number" value={c.min} onChange={e=>patchNumber(i,'min',Number(e.target.value))}/><Input aria-label="Máximo" type="number" value={c.max} onChange={e=>patchNumber(i,'max',Number(e.target.value))}/><Input aria-label="Quantidade" type="number" value={c.count} onChange={e=>patchNumber(i,'count',Number(e.target.value))}/></div>)}</div></div>
}

function TemplatesSection({templates,workspaceId,eventId,event,reload,notify,fail}:{templates:CardTemplate[];workspaceId:string;eventId:string;event:BingoEvent;reload:()=>Promise<void>;notify:(s:string|null)=>void;fail:(s:string|null)=>void}){
 const [show,setShow]=useState(false);return <div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black">Layouts físicos</h2><p className="text-sm text-slate-600">Escolha a posição dos jogos, baixe o gabarito, crie a arte e importe o fundo pronto.</p></div><Button onClick={()=>setShow(v=>!v)}>{show?'Fechar':'Novo layout'}</Button></div>{show&&<TemplateForm workspaceId={workspaceId} eventId={eventId} event={event} onDone={async()=>{setShow(false);notify('Layout criado com sucesso.');await reload()}} fail={fail}/>}<div className="grid gap-4 xl:grid-cols-2">{templates.map(t=><Card key={t.id}><div className="flex items-start justify-between gap-2"><div><div className="flex flex-wrap gap-2">{t.is_default&&<StatusBadge tone="success">Padrão</StatusBadge>}<StatusBadge tone={t.is_active?'neutral':'warning'}>{`${t.physical_format} em 1`}</StatusBadge></div><h3 className="mt-2 text-lg font-black">{t.name}</h3></div></div><div className="mt-4"><CardTemplatePreview format={Math.min(3,t.physical_format) as 1|2|3} layoutKey={t.layout_key} eventName={event.name} template={t}/></div><div className="mt-4 flex flex-wrap gap-2">{!t.is_default&&<Button variant="secondary" onClick={()=>void action(async()=>setDefaultTemplate(t.id),'Layout definido como padrão.',reload,notify,fail)}>Definir padrão</Button>}<Button variant="secondary" onClick={()=>void action(async()=>toggleTemplate(workspaceId,t.id,!t.is_active),t.is_active?'Layout desativado.':'Layout ativado.',reload,notify,fail)}>{t.is_active?'Desativar':'Ativar'}</Button></div></Card>)}</div></div>
}
function TemplateForm({workspaceId,eventId,event,onDone,fail}:{workspaceId:string;eventId:string;event:BingoEvent;onDone:()=>Promise<void>;fail:(s:string|null)=>void}){
 const [format,setFormat]=useState<1|2|3>(1);const firstPreset=layoutsForFormat(1)[0];const [layout,setLayout]=useState(firstPreset?.key??'single_showcase');const [name,setName]=useState(firstPreset?.name??'1 em 1 · Destaque');const [saving,setSaving]=useState(false);const [artFile,setArtFile]=useState<File|null>(null);const [artUrl,setArtUrl]=useState<string|null>(null);const [quality,setQuality]=useState<ArtworkQuality>('standard');const [zoom,setZoom]=useState(1);const [offsetX,setOffsetX]=useState(0);const [offsetY,setOffsetY]=useState(0);const [wildcard,setWildcard]=useState<WildcardKind>('star');const [wildScale,setWildScale]=useState(1);const [wildFile,setWildFile]=useState<File|null>(null);const [wildUrl,setWildUrl]=useState<string|null>(null);const presets=layoutsForFormat(format);const selected=getCardLayoutPreset(layout,format)
 useEffect(()=>()=>{if(artUrl)URL.revokeObjectURL(artUrl)},[artUrl])
 useEffect(()=>()=>{if(wildUrl)URL.revokeObjectURL(wildUrl)},[wildUrl])
 function changeFormat(v:1|2|3){setFormat(v);const first=layoutsForFormat(v)[0];if(first){setLayout(first.key);setName(first.name)}}
 function chooseArt(file:File|null){if(artUrl)URL.revokeObjectURL(artUrl);setArtFile(file);setArtUrl(file?URL.createObjectURL(file):null)}
 function chooseWildcard(file:File|null){if(wildUrl)URL.revokeObjectURL(wildUrl);setWildFile(file);setWildUrl(file?URL.createObjectURL(file):null);if(file)setWildcard('custom')}
 async function submit(){if(!selected)return;setSaving(true);fail(null);try{const options:CardTemplateOptions={version:1,artwork:artFile?{path:'pending',zoom,offsetX,offsetY,quality}:undefined,wildcard:{kind:wildcard,scale:wildScale}};const optimizedArt=artFile?await optimizeArtwork(artFile,quality):undefined;const optimizedWildcard=wildcard==='custom'&&wildFile?await optimizeWildcard(wildFile):undefined;await createCardTemplate(workspaceId,eventId,{name,format,layoutKey:layout,orientation:'portrait',pageSize:'A4',bannerPosition:'none',bannerHeightMm:0,isDefault:false,options,artworkFile:optimizedArt,wildcardFile:optimizedWildcard});await onDone()}catch(e){fail(e instanceof Error?e.message:'Não foi possível criar o layout.')}finally{setSaving(false)}}
 const previewOptions:CardTemplateOptions={version:1,artwork:artFile?{path:'',zoom,offsetX,offsetY,quality}:undefined,wildcard:{kind:wildcard,scale:wildScale}}
 return <Card className="border-red-900/40"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-lg font-black">Novo layout de cartela</h3><p className="mt-1 text-sm text-slate-500">A cartela usa proporção A4. O gabarito mostra somente onde cada jogo será impresso.</p></div>{selected&&<Button variant="secondary" onClick={()=>downloadLayoutGuidePng(selected.key,format,selected.gameAreas)}>Baixar gabarito PNG</Button>}</div>
 <div className="mt-5 grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(330px,.8fr)]"><div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Formato<Select className="mt-1" value={format} onChange={e=>changeFormat(Number(e.target.value) as 1|2|3)}><option value={1}>1 em 1</option><option value={2}>2 em 1</option><option value={3}>3 em 1</option></Select></label><label className="text-sm font-semibold">Nome<Input className="mt-1" value={name} onChange={e=>setName(e.target.value)}/></label><label className="text-sm font-semibold sm:col-span-2">Modelo<Select className="mt-1" value={layout} onChange={e=>{setLayout(e.target.value);const p=presets.find(x=>x.key===e.target.value);if(p)setName(p.name)}}>{presets.map(p=><option key={p.key} value={p.key}>{p.name} — {p.description}</option>)}</Select></label></div>
 <div className="rounded-2xl border border-slate-700 p-4"><h4 className="font-black">1. Arte de fundo</h4><p className="mt-1 text-xs text-slate-500">Crie a arte usando o gabarito e importe JPG, PNG ou WebP. O arquivo será otimizado antes do envio.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Imagem<input className="mt-1 block w-full text-xs" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseArt(e.target.files?.[0]??null)}/></label><label className="text-sm font-semibold">Qualidade<Select className="mt-1" value={quality} onChange={e=>setQuality(e.target.value as ArtworkQuality)}><option value="light">Arquivo leve</option><option value="standard">Impressão padrão</option><option value="high">Alta qualidade</option></Select></label></div>{artFile&&<div className="mt-4 grid gap-3 sm:grid-cols-3"><Range label={`Zoom ${zoom.toFixed(2)}×`} min={.6} max={2.5} step={.05} value={zoom} set={setZoom}/><Range label={`Horizontal ${offsetX}%`} min={-45} max={45} step={1} value={offsetX} set={setOffsetX}/><Range label={`Vertical ${offsetY}%`} min={-45} max={45} step={1} value={offsetY} set={setOffsetY}/></div>}</div>
 <div className="rounded-2xl border border-slate-700 p-4"><h4 className="font-black">2. Símbolo coringa</h4><p className="mt-1 text-xs text-slate-500">Escolha o desenho da casa livre central. O símbolo fica por cima da arte.</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Símbolo<Select className="mt-1" value={wildcard} onChange={e=>setWildcard(e.target.value as WildcardKind)}><option value="star">Estrela</option><option value="circle">Bola</option><option value="heart">Coração</option><option value="cross">Símbolo</option><option value="fire">Fogueira</option><option value="soccer">Bola de futebol</option><option value="none">Sem símbolo</option><option value="custom">Imagem personalizada</option></Select></label>{wildcard==='custom'&&<label className="text-sm font-semibold">Imagem do coringa<input className="mt-1 block w-full text-xs" type="file" accept="image/*" onChange={e=>chooseWildcard(e.target.files?.[0]??null)}/></label>}</div><div className="mt-3"><Range label={`Tamanho ${wildScale.toFixed(2)}×`} min={.4} max={1.6} step={.05} value={wildScale} set={setWildScale}/></div></div>
 <div className="flex justify-end"><Button disabled={saving||!name.trim()||(wildcard==='custom'&&!wildFile)} onClick={()=>void submit()}>{saving?'Otimizando e salvando…':'Criar layout'}</Button></div></div>
 <div className="xl:sticky xl:top-24 xl:self-start"><p className="mb-2 text-xs font-black uppercase tracking-[.16em] text-red-400">Prévia em tempo real</p><CardTemplatePreview format={format} layoutKey={layout} eventName={event.name} previewOptions={previewOptions} localArtworkUrl={artUrl} localWildcardUrl={wildUrl}/><p className="mt-2 text-xs text-slate-500">A imagem inteira é sua arte. O BINGOUP adiciona somente os jogos de números e o coringa.</p></div></div></Card>
}
function Range({label,min,max,step,value,set}:{label:string;min:number;max:number;step:number;value:number;set:(v:number)=>void}){return <label className="block text-xs font-semibold text-slate-400">{label}<input className="mt-2 w-full accent-red-600" type="range" min={min} max={max} step={step} value={value} onChange={e=>set(Number(e.target.value))}/></label>}
async function action(fn:()=>Promise<void>,message:string,reload:()=>Promise<void>,notify:(s:string|null)=>void,fail:(s:string|null)=>void){fail(null);try{await fn();notify(message);await reload()}catch(e){fail(e instanceof Error?e.message:'Não foi possível concluir a ação.')}}
