import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {useAuth} from '@/app/providers/AuthProvider'
import {usePlatformBrand} from '@/components/brand/PlatformBrandProvider'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {listMyAccessCenters,type AccessCenters} from './accessService'

export function AccessCenterPage(){const {signOut}=useAuth();const {mainLogoUrl,app_name}=usePlatformBrand();const [data,setData]=useState<AccessCenters|null>(null);const [error,setError]=useState<string|null>(null)
useEffect(()=>{void listMyAccessCenters().then(setData).catch(e=>setError(e instanceof Error?e.message:'Não foi possível carregar seus acessos.'))},[])
return <main className="bingoup-app min-h-dvh p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><img src={mainLogoUrl} alt={app_name} className="h-14 max-w-[230px] object-contain"/><Button variant="secondary" onClick={()=>void signOut()}>Sair</Button></header><div><p className="text-sm font-black uppercase tracking-[.18em] text-red-400">Minha conta</p><h1 className="mt-1 text-3xl font-black text-white">Escolha como deseja acessar</h1><p className="mt-2 text-sm text-slate-400">A mesma conta pode ser organizador, vendedor, operador e comprador em eventos diferentes.</p></div>{error&&<div className="rounded-2xl border border-red-900/60 bg-red-950/30 p-4 text-sm text-red-300">{error}</div>}{!data&&!error?<Card>Carregando seus acessos…</Card>:data&&<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{data.organizers.length>0&&<AccessCard title="Organizador" text={`${data.organizers.length} espaço(s) disponível(is)`} to="/organizador" button="Gerenciar meus bingos"/>}{data.seller_events.length>0&&<AccessCard title="Vendedor" text={`${data.seller_events.length} evento(s) para venda`} to="/venda" button="Ir para vendas"/>}{data.operator_events.length>0&&<AccessCard title="Operador" text={`${data.operator_events.length} evento(s) para operar`} to="/operador" button="Ir para operação"/>}{data.buyer_events.length>0&&<AccessCard title="Minhas cartelas" text={`${data.buyer_events.reduce((n,e)=>n+Number(e.cards||0),0)} cartela(s) comprada(s)`} to="/cliente" button="Ver minhas cartelas"/>}{data.is_master&&<AccessCard title="Master" text="Controle da plataforma" to="/master" button="Abrir Master"/>}</div>}{data&&data.organizers.length===0&&data.seller_events.length===0&&data.operator_events.length===0&&data.buyer_events.length===0&&!data.is_master&&<Card><h2 className="text-xl font-black text-white">Nenhum acesso ativo ainda</h2><p className="mt-2 text-sm text-slate-400">Se você recebeu um convite, abra novamente o link do convite. Se deseja organizar seus próprios eventos, aguarde a liberação comercial.</p><Link to="/" className="mt-4 inline-block"><Button>Ver situação do acesso</Button></Link></Card>}</div></main>}
function AccessCard({title,text,to,button}:{title:string;text:string;to:string;button:string}){return <Card className="flex min-h-52 flex-col"><h2 className="text-xl font-black text-white">{title}</h2><p className="mt-2 flex-1 text-sm text-slate-400">{text}</p><Link to={to}><Button className="mt-5 w-full">{button}</Button></Link></Card>}
