import {useCallback,useEffect,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {getMyBuyerEvent,type BuyerEventState} from './accessService'
import {RoleShell} from './SellerCenterPage'

export function BuyerEventPage(){
 const {eventId=''}=useParams();const [state,setState]=useState<BuyerEventState|null>(null);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{try{setState(await getMyBuyerEvent(eventId));setError(null)}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar suas cartelas.')}},[eventId])
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(),2500);return()=>window.clearInterval(id)},[load])
 return <RoleShell title={state?.event.name??'Minhas cartelas'} subtitle="Suas cartelas, sorteio ao vivo e prêmios confirmados em um só lugar." error={error}>
  {state?.latest_win&&<div className="rounded-2xl border border-emerald-500 bg-emerald-950/40 p-5 text-emerald-100"><p className="text-sm font-black uppercase tracking-[.15em] text-emerald-400">Prêmio confirmado</p><h2 className="mt-1 text-2xl font-black">Você{state.latest_win.buyer_name?`, ${state.latest_win.buyer_name}`:''}, foi ganhador!</h2><p className="mt-2 text-sm"><strong>{state.latest_win.prize}</strong>. {state.latest_win.total_winners>state.latest_win.my_winners?`Você ganhou junto com outras ${state.latest_win.total_winners-state.latest_win.my_winners} pessoa(s).`:'Sua vitória foi confirmada pelo organizador.'}</p></div>}
  <div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><Card><h2 className="text-lg font-black text-white">Sorteio do evento</h2>{state?.public_session_token?<><p className="mt-1 text-sm text-slate-400">Acompanhe a mesma tela exibida no painel público, atualizada pelo evento.</p><a href={`/painel-publico/${state.public_session_token}`} target="_blank" rel="noreferrer"><Button className="mt-4">Assistir sorteio ao vivo</Button></a></>:<p className="mt-2 text-sm text-slate-400">Nenhum sorteio disponível neste momento.</p>}</Card><Card><h2 className="text-lg font-black text-white">Resumo</h2><div className="mt-3 grid grid-cols-2 gap-3"><Stat label="Cartelas" value={state?.cards.length??0}/><Stat label="Prêmios" value={state?.winner_count??0}/></div></Card></div>
  {(state?.wins?.length??0)>0&&<Card><h2 className="text-lg font-black text-white">Meus prêmios</h2><div className="mt-3 grid gap-2">{state!.wins.map(w=><div key={w.winner_id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-slate-800 bg-slate-950/50 p-3"><div><p className="font-black text-white">{w.prize}</p><p className="text-xs text-slate-400">{w.round_name} · Cartela {w.card_code} · Jogo {w.game_position}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${w.delivered?'bg-emerald-950 text-emerald-300':'bg-amber-950 text-amber-300'}`}>{w.delivered?'PRÊMIO ENTREGUE':'AGUARDANDO ENTREGA'}</span></div>)}</div></Card>}
  <div><h2 className="text-xl font-black text-white">Minhas cartelas</h2><p className="mt-1 text-sm text-slate-400">Abra no celular para acompanhar as marcações ou use a opção de impressão.</p></div>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{state?.cards.map(c=><Card key={c.id} className={c.is_winner?'border-emerald-500/50':''}><div className="flex items-start justify-between gap-2"><div><h3 className="text-lg font-black text-white">Cartela {c.code}</h3><p className="mt-1 text-xs text-slate-500">{c.physical_format} em 1</p></div>{c.is_winner&&<span className="rounded-full bg-emerald-950 px-2 py-1 text-[10px] font-black text-emerald-300">PREMIADA</span>}</div><div className="mt-4 grid gap-2"><Link to={`/c/${c.public_token}`}><Button className="w-full">Abrir cartela digital</Button></Link><a href={`/c/${c.public_token}?imprimir=1`} target="_blank" rel="noreferrer"><Button variant="secondary" className="w-full">Abrir para imprimir</Button></a></div></Card>)}</div>
  <Link to="/cliente"><Button variant="secondary">Voltar às minhas compras</Button></Link>
 </RoleShell>
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-slate-950/60 p-3"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-white">{value}</p></div>}
