import {useCallback,useEffect,useMemo,useRef,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {Button} from '@/components/ui/Button'
import {getMyBuyerDigitalCard,type BuyerDigitalCardState,type BuyerDigitalGame} from './accessService'
import {markedNumbers,normalizeCalledNumbers} from '@/domain/cards/publicDigitalCard'

export function BuyerCardPage(){
  const {eventId='',cardId=''}=useParams();const [state,setState]=useState<BuyerDigitalCardState|null>(null);const [error,setError]=useState<string|null>(null);const busy=useRef(false)
  const load=useCallback(async()=>{if(!eventId||!cardId||busy.current)return;busy.current=true;try{setState(await getMyBuyerDigitalCard(eventId,cardId));setError(null)}catch(e){setError(e instanceof Error?e.message:'Não foi possível sincronizar a cartela agora.')}finally{busy.current=false}},[eventId,cardId])
  useEffect(()=>{void load();const id=window.setInterval(()=>{if(document.visibilityState==='visible')void load()},2000);const sync=()=>{if(document.visibilityState==='visible')void load()};document.addEventListener('visibilitychange',sync);window.addEventListener('online',sync);return()=>{window.clearInterval(id);document.removeEventListener('visibilitychange',sync);window.removeEventListener('online',sync)}},[load])
  useEffect(()=>{if(state?.card?.id&&new URLSearchParams(window.location.search).get('imprimir')==='1'){const id=window.setTimeout(()=>window.print(),700);return()=>window.clearTimeout(id)}},[state?.card?.id])
  const called=useMemo(()=>normalizeCalledNumbers(state?.draw?.called_numbers),[state?.draw?.called_numbers])
  if(!state&&!error)return <Shell><p className="text-center text-slate-300">Carregando sua cartela…</p></Shell>
  if(!state?.card||!state.event||!state.rule)return <Shell><p className="text-center text-red-300">{error??'Cartela indisponível.'}</p><div className="mt-4 text-center"><Link to={`/cliente/${eventId}`}><Button variant="secondary">Voltar às minhas cartelas</Button></Link></div></Shell>
  return <main className="min-h-dvh bg-slate-950 text-white"><div className="mx-auto max-w-5xl p-3 sm:p-5">
    <header className="sticky top-0 z-20 rounded-2xl border border-slate-800 bg-slate-950/95 p-4 shadow-xl backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.22em] text-emerald-400">Minha cartela · {state.event.name}</p><h1 className="mt-1 text-2xl font-black">{state.card.code}</h1><p className="text-xs text-slate-400">Série {state.card.series_code} · {state.card.physical_format} em 1</p></div><div className="text-right"><p className="text-xs font-bold uppercase text-slate-500">Última bola</p><div className="mt-1 inline-grid h-14 min-w-14 place-items-center rounded-full border-2 border-red-500 bg-red-600 px-3 text-2xl font-black">{state.draw?.last_called_number??'—'}</div></div></div>
      {state.draw&&<div className="mt-3 flex flex-wrap gap-2 text-xs"><Badge>{state.draw.name}</Badge><Badge>{state.draw.called_count} bolas chamadas</Badge>{state.draw.status==='paused'&&<Badge tone="warning">Pausado para conferência</Badge>}{state.draw.is_winner&&<Badge tone="success">Você tem jogo vencedor confirmado nesta cartela</Badge>}</div>}
    </header>
    {error&&state&&<div className="mt-3 rounded-xl border border-amber-700/50 bg-amber-950/30 p-3 text-sm text-amber-200">Sincronização momentaneamente indisponível. Mantendo os últimos dados recebidos.</div>}
    <section className="mt-4 grid gap-4 md:grid-cols-2">{(state.games??[]).map(game=><GameCard key={game.position} game={game} cols={state.rule!.grid_columns} labels={(state.rule!.column_definitions??[]).map(c=>c.label??'')} called={called}/>)}</section>
    <section className="mt-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><p className="text-xs font-black uppercase tracking-[.18em] text-slate-500">Números chamados</p><div className="mt-3 flex flex-wrap gap-2">{Array.from(called).sort((a,b)=>a-b).map(n=><span key={n} className="grid h-9 min-w-9 place-items-center rounded-full bg-emerald-500 px-2 text-sm font-black text-slate-950">{n}</span>)}{called.size===0&&<span className="text-sm text-slate-400">O sorteio ainda não começou.</span>}</div></section>
    <div className="flex flex-wrap justify-center gap-2 py-5 print:hidden"><Button onClick={()=>window.print()}>Imprimir minha cartela</Button><Link to={`/cliente/${eventId}`}><Button variant="secondary">Voltar às minhas cartelas</Button></Link></div>
  </div></main>
}
function GameCard({game,cols,labels,called}:{game:BuyerDigitalGame;cols:number;labels:string[];called:Set<number>}){const rows=Math.ceil(game.cells.length/cols);return <article className="rounded-2xl border border-slate-700 bg-slate-900 p-3 shadow-lg"><div className="mb-2 flex items-center justify-between"><h2 className="font-black">Jogo {game.position}</h2><span className="text-xs font-bold text-emerald-400">{markedNumbers(game.cells,called)}/{game.cells.length} marcados</span></div><div className="grid overflow-hidden rounded-xl border border-slate-700 bg-slate-800" style={{gridTemplateColumns:`repeat(${cols},minmax(0,1fr))`}}>{labels.slice(0,cols).map((label,i)=><div key={`${label}-${i}`} className="grid min-h-10 place-items-center bg-red-600 text-lg font-black">{label}</div>)}{game.cells.map((value,index)=>{const marked=value===null||called.has(value);return <div key={index} className={`grid aspect-square place-items-center border border-slate-700 text-lg font-black sm:text-xl ${marked?'bg-emerald-500 text-slate-950':'bg-white text-slate-950'}`}>{value===null?'★':String(value).padStart(2,'0')}</div>})}</div><p className="mt-2 text-right text-[10px] text-slate-500">{cols} × {rows}</p></article>}
function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:'neutral'|'warning'|'success'}){const cls=tone==='warning'?'border-amber-700 bg-amber-950/40 text-amber-300':tone==='success'?'border-emerald-700 bg-emerald-950/40 text-emerald-300':'border-slate-700 bg-slate-900 text-slate-300';return <span className={`rounded-full border px-2.5 py-1 font-bold ${cls}`}>{children}</span>}
function Shell({children}:{children:React.ReactNode}){return <main className="grid min-h-dvh place-items-center bg-slate-950 p-5 text-white"><div className="w-full max-w-md rounded-3xl border border-slate-800 bg-slate-900/70 p-6">{children}</div></main>}
