import {useCallback,useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {Button} from '@/components/ui/Button'
import {Card} from '@/components/ui/Card'
import {acceptSellerInvitation,listMyPendingSellerInvitations,type MyPendingSellerInvitation} from '@/features/sellers/sellerService'
import {listMyAccessCenters,type AccessEvent} from './accessService'

export function SellerCenterPage(){
 const[items,setItems]=useState<AccessEvent[]>([]),[invites,setInvites]=useState<MyPendingSellerInvitation[]>([]),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[busyToken,setBusyToken]=useState<string|null>(null)
 const load=useCallback(async()=>{const[centers,pending]=await Promise.allSettled([listMyAccessCenters(),listMyPendingSellerInvitations()]);if(centers.status==='fulfilled')setItems(centers.value.seller_events);if(pending.status==='fulfilled')setInvites(pending.value);const failure=centers.status==='rejected'?centers.reason:pending.status==='rejected'?pending.reason:null;setError(failure instanceof Error?failure.message:failure?'Falha ao carregar parte da área do vendedor.':null)},[])
 useEffect(()=>{void load()},[load])
 async function accept(invite:MyPendingSellerInvitation){setBusyToken(invite.token);setError(null);try{await acceptSellerInvitation(invite.token);setNotice(`Convite de ${invite.workspace_name} aceito. Os eventos já foram liberados.`);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível aceitar o convite.')}finally{setBusyToken(null)}}
 return <RoleShell title="Central do vendedor" subtitle="Aceite convites e acesse somente os eventos liberados para você." error={error}>{notice&&<div className="rounded-xl border border-emerald-800 bg-emerald-950/30 p-4 text-sm text-emerald-300">{notice}</div>}{invites.length>0&&<section><h2 className="text-xl font-black text-white">Convites para aceitar</h2><p className="mt-1 text-sm text-slate-400">Estes convites foram enviados para o e-mail da sua conta.</p><div className="mt-3 grid gap-4 md:grid-cols-2">{invites.map(i=><Card key={i.token} className="border-amber-700/60"><p className="text-xs font-black uppercase tracking-wide text-amber-300">Aguardando seu aceite</p><h3 className="mt-1 text-xl font-black text-white">{i.workspace_name}</h3><p className="mt-3 text-sm text-slate-300">Eventos liberados: {i.event_names.length?i.event_names.join(', '):'nenhum evento selecionado'}</p><p className="mt-1 text-xs text-slate-500">Válido até {new Date(i.expires_at).toLocaleString('pt-BR')}</p><Button className="mt-4 w-full" disabled={busyToken===i.token} onClick={()=>void accept(i)}>{busyToken===i.token?'Aceitando…':'Aceitar convite'}</Button></Card>)}</div></section>}{items.length?<section><h2 className="text-xl font-black text-white">Eventos liberados</h2><div className="mt-3 grid gap-4 md:grid-cols-2">{items.map(i=><Card key={i.event_id}><p className="text-xs font-bold uppercase text-slate-500">{i.workspace_name} · {modeLabel(i.game_mode)}</p><h3 className="mt-1 text-xl font-black text-white">{i.event_name}</h3><p className="mt-2 text-sm text-slate-400">{i.starts_at?new Date(i.starts_at).toLocaleString('pt-BR'):'Data não informada'}</p><Link to={`/venda/${i.event_id}`}><Button className="mt-4 w-full">{i.game_mode==='raffle'?'Vender números':i.game_mode==='symbol_bingo'?'Vender cartelas temáticas':'Abrir vendas'}</Button></Link></Card>)}</div></section>:!invites.length&&<Card>Nenhum evento ou convite disponível para este e-mail.</Card>}</RoleShell>
}
function modeLabel(mode:AccessEvent['game_mode']){return mode==='raffle'?'Rifa':mode==='symbol_bingo'?'Bingo de símbolos':'Bingo tradicional'}
export function RoleShell({title,subtitle,error,children}:{title:string;subtitle:string;error:string|null;children:React.ReactNode}){return <main className="bingoup-app min-h-dvh p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-black uppercase tracking-[.16em] text-red-400">BINGOUP</p><h1 className="mt-1 text-3xl font-black text-white">{title}</h1><p className="mt-2 text-sm text-slate-400">{subtitle}</p></div><Link to="/acessos"><Button variant="secondary">Trocar área</Button></Link></div>{error&&<div role="alert" className="rounded-xl border border-red-900 bg-red-950/30 p-3 text-red-300">{error}</div>}{children}</div></main>}
