import {useCallback,useEffect,useMemo,useState} from 'react'
import {Card} from '@/components/ui/Card'
import {getMySpecialGameEvent,type SpecialBuyerState} from './accessService'

export function SpecialBuyerEventPage({eventId}:{eventId:string}){
 const[state,setState]=useState<SpecialBuyerState|null>(null),[error,setError]=useState('')
 const load=useCallback(async()=>{try{setState(await getMySpecialGameEvent(eventId));setError('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar sua compra.')}},[eventId])
 useEffect(()=>{void load();const id=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(id)},[load])
 const itemMap=useMemo(()=>new Map(state?.items.map(i=>[i.id,i])??[]),[state?.items]);const called=new Set(state?.draws.map(d=>d.item_id).filter(Boolean)??[])
 if(error)return <p role="alert" className="rounded-xl border border-red-900 bg-red-950/30 p-3 text-red-300">{error}</p>;if(!state)return <Card>Carregando suas compras…</Card>
 if(state.event.game_mode==='raffle'){const winners=new Set(state.draws.map(d=>d.number));return <div className="space-y-5"><Card><h2 className="text-xl font-black text-white">Meus números</h2><p className="mt-1 text-sm text-slate-400">{state.config?.prize_description||'Rifa vinculada à sua conta.'}</p><div className="mt-4 flex flex-wrap gap-3">{state.purchases.map(p=><div key={p.id} className={`grid size-20 place-items-center rounded-2xl border text-3xl font-black ${winners.has(p.number??-1)?'border-emerald-500 bg-emerald-950 text-emerald-200':'border-slate-700 bg-slate-950 text-white'}`}>{p.number}</div>)}</div></Card><Card><h2 className="text-lg font-black text-white">Resultados</h2>{state.draws.length?<div className="mt-3 flex flex-wrap gap-2">{state.draws.map(d=><span key={d.draw_order} className="rounded-full bg-emerald-950 px-4 py-2 font-black text-emerald-200">{d.number}</span>)}</div>:<p className="mt-2 text-sm text-slate-400">O sorteio ainda não começou.</p>}</Card></div>}
 const grid=state.config?.grid_size??4;return <div className="space-y-5"><Card><h2 className="text-xl font-black text-white">Minhas cartelas temáticas</h2><p className="mt-1 text-sm text-slate-400">Tema: {state.config?.theme_name}. Os símbolos sorteados ficam destacados automaticamente.</p></Card><div className="grid gap-4 lg:grid-cols-2">{state.purchases.map(card=><Card key={card.id}><h3 className="font-black text-white">Cartela {card.code}</h3><div className="mt-3 grid" style={{gridTemplateColumns:`repeat(${grid},minmax(0,1fr))`}}>{card.cells.map((id,index)=>{const item=itemMap.get(id);return <div key={`${id}-${index}`} className={`grid min-h-24 place-items-center border border-slate-700 p-2 text-center ${called.has(id)?'bg-emerald-950 text-emerald-100':'bg-slate-950 text-white'}`}><span><span className="block text-3xl" aria-hidden="true">{item?.symbol}</span><b className="text-xs">{item?.label}</b></span></div>})}</div></Card>)}</div><Card><h2 className="text-lg font-black text-white">Símbolos sorteados</h2>{state.draws.length?<div className="mt-3 flex flex-wrap gap-2">{state.draws.map(d=>{const item=d.item_id?itemMap.get(d.item_id):null;return <span key={d.draw_order} className="rounded-xl bg-violet-950 px-3 py-2 text-violet-100">{item?.symbol} {item?.label}</span>})}</div>:<p className="mt-2 text-sm text-slate-400">O sorteio ainda não começou.</p>}</Card></div>
}
