import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { useWorkspace } from '@/app/providers/WorkspaceProvider'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { Input } from '@/components/ui/Input'
import { Select } from '@/components/ui/Select'
import { Textarea } from '@/components/ui/Textarea'
import { StatusBadge } from '@/components/ui/StatusBadge'
import { normalizeMoneyInput, validateBuyer } from '@/domain/sales/validation'
import { cancelSale, completeReservedSale, createCardSale, getSalesSummary, listEventSales, listSaleableCards, listSalesEvents, type SaleView, type SalesEventOption, type SalesSummary } from './salesService'
import type { PhysicalCard, SaleStatus } from '@/types/database'
const saleStatusLabel:Record<SaleStatus,string>={reserved:'Reservada',completed:'Concluída',canceled:'Cancelada'}

export function SalesPage(){
  const {eventId:paramEventId}=useParams();const [searchParams,setSearchParams]=useSearchParams();const {currentWorkspace}=useWorkspace()
  const [events,setEvents]=useState<SalesEventOption[]>([]);const [eventId,setEventId]=useState(paramEventId||searchParams.get('evento')||'')
  const [cards,setCards]=useState<PhysicalCard[]>([]);const [selected,setSelected]=useState<string[]>([]);const [sales,setSales]=useState<SaleView[]>([]);const [summary,setSummary]=useState<SalesSummary|null>(null)
  const [search,setSearch]=useState('');const [fromSequence,setFromSequence]=useState('');const [toSequence,setToSequence]=useState('');const [statusFilter,setStatusFilter]=useState<''|SaleStatus>('')
  const [buyer,setBuyer]=useState({name:'',phone:'',email:'',notes:''});const [price,setPrice]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null)
  const currentEvent=events.find(e=>e.id===eventId)

  const loadEvents=useCallback(async()=>{if(!currentWorkspace)return;const data=await listSalesEvents(currentWorkspace.id);setEvents(data);setEventId(v=>v||data[0]?.id||'')},[currentWorkspace])
  const loadEventData=useCallback(async()=>{if(!currentWorkspace||!eventId)return;setLoading(true);setError(null);try{const [cs,ss,sum]=await Promise.all([listSaleableCards(currentWorkspace.id,eventId,{search,fromSequence:fromSequence?Number(fromSequence):undefined,toSequence:toSequence?Number(toSequence):undefined}),listEventSales(currentWorkspace.id,eventId,statusFilter||undefined),getSalesSummary(currentWorkspace.id,eventId)]);setCards(cs);setSelected(current=>current.filter(id=>cs.some(card=>card.id===id)));setSales(ss);setSummary(sum)}catch(e:any){setError(e?.message||'Não foi possível carregar as vendas.')}finally{setLoading(false)}},[currentWorkspace,eventId,search,fromSequence,toSequence,statusFilter])
  useEffect(()=>{void loadEvents().catch(()=>setError('Não foi possível carregar os eventos.'))},[loadEvents])
  useEffect(()=>{if(eventId){if(!paramEventId)setSearchParams({evento:eventId},{replace:true});void loadEventData()}},[eventId,paramEventId,setSearchParams,loadEventData])
  useEffect(()=>{if(currentEvent)setPrice(String(currentEvent.settings.default_card_price).replace('.',','))},[currentEvent])

  const selectedCards=useMemo(()=>cards.filter(c=>selected.includes(c.id)),[cards,selected]);const numericPrice=normalizeMoneyInput(price);const total=(numericPrice??0)*selected.length
  function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
  function selectVisible(){setSelected(cards.map(c=>c.id))}
  function clearSelection(){setSelected([])}
  async function submit(reserveOnly:boolean){if(!currentEvent)return;setError(null);setNotice(null);if(!selected.length){setError('Selecione ao menos uma cartela.');return}const buyerError=validateBuyer({requireName:currentEvent.settings.require_buyer_name,requirePhone:currentEvent.settings.require_buyer_phone,requireEmail:currentEvent.settings.require_buyer_email},{name:buyer.name,phone:buyer.phone,email:buyer.email});if(buyerError){setError(buyerError);return}if(numericPrice==null){setError('Informe um valor válido por cartela.');return}setSaving(true);try{await createCardSale({eventId,cardIds:selected,buyerName:buyer.name,buyerPhone:buyer.phone,buyerEmail:buyer.email,buyerNotes:buyer.notes,unitPrice:numericPrice,reserveOnly});setNotice(reserveOnly?'Reserva registrada com sucesso.':'Venda registrada com sucesso.');setSelected([]);setBuyer({name:'',phone:'',email:'',notes:''});await loadEventData()}catch(e:any){setError(e?.message||'Não foi possível registrar a operação.')}finally{setSaving(false)}}
  async function finalize(saleId:string){setSaving(true);setError(null);try{await completeReservedSale(saleId);setNotice('Reserva convertida em venda.');await loadEventData()}catch(e:any){setError(e?.message||'Não foi possível concluir a reserva.')}finally{setSaving(false)}}
  async function cancel(saleId:string){const reason=window.prompt('Motivo do cancelamento (opcional):')??undefined;if(reason===undefined)return;setSaving(true);setError(null);try{await cancelSale(saleId,reason);setNotice('Operação cancelada e cartelas liberadas quando permitido.');await loadEventData()}catch(e:any){setError(e?.message||'Não foi possível cancelar.')}finally{setSaving(false)}}

  if(!currentWorkspace)return null
  return <div className="space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-emerald-700">Operação</p><h1 className="mt-1 text-3xl font-black tracking-tight">Vendas</h1><p className="mt-2 text-sm text-slate-600">Venda ou reserve cartelas sem risco de duas pessoas registrarem a mesma unidade.</p></div>{paramEventId&&<Link to={`/eventos/${paramEventId}`}><Button variant="secondary">Voltar ao evento</Button></Link>}</div>
    {notice&&<div className="rounded-2xl bg-emerald-50 p-4 text-sm font-medium text-emerald-800">{notice}</div>}{error&&<div className="rounded-2xl bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}
    <Card><div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_auto]"><label className="text-sm font-semibold text-slate-700">Evento<Select className="mt-1" value={eventId} disabled={Boolean(paramEventId)} onChange={e=>{setEventId(e.target.value);setSelected([]);setPrice('')}}><option value="">Selecione…</option>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</Select></label>{currentEvent&&<div className="self-end text-sm text-slate-500">Preço padrão: <strong>{money(currentEvent.settings.default_card_price,currentEvent.settings.currency)}</strong></div>}</div></Card>
    {!eventId?<Card>Crie ou selecione um evento para começar.</Card>:<>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Disponíveis" value={summary?.available??0}/><Metric label="Reservadas" value={summary?.reserved??0}/><Metric label="Vendidas" value={summary?.sold??0}/><Metric label="Vendas concluídas" value={summary?.completedSales??0}/><Metric label="Total vendido" value={money(summary?.completedAmount??0,currentEvent?.settings.currency||'BRL')}/></div>
      <div className="grid gap-5 xl:grid-cols-[minmax(0,1.2fr)_minmax(360px,.8fr)]">
        <Card><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-lg font-black">Cartelas disponíveis</h2><p className="text-sm text-slate-500">Selecione uma ou várias cartelas para a mesma venda.</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={selectVisible} disabled={!cards.length}>Selecionar visíveis</Button><Button variant="secondary" onClick={clearSelection} disabled={!selected.length}>Limpar</Button></div></div>
          <div className="mt-4 grid gap-3 sm:grid-cols-3"><Input placeholder="Buscar código" value={search} onChange={e=>setSearch(e.target.value)}/><Input type="number" min="1" placeholder="Sequência inicial" value={fromSequence} onChange={e=>setFromSequence(e.target.value)}/><Input type="number" min="1" placeholder="Sequência final" value={toSequence} onChange={e=>setToSequence(e.target.value)}/></div>
          {loading?<p className="mt-5 text-sm text-slate-500">Carregando…</p>:cards.length?<div className="mt-5 grid max-h-[520px] gap-2 overflow-auto pr-1 sm:grid-cols-2 lg:grid-cols-3">{cards.map(c=><label key={c.id} className={`flex cursor-pointer items-center gap-3 rounded-2xl border p-3 ${selected.includes(c.id)?'border-emerald-500 bg-emerald-50':'border-slate-200 bg-white'}`}><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>toggle(c.id)}/><span className="min-w-0"><strong className="block break-words">{c.code}</strong><span className="text-xs text-slate-500">#{c.sequence_number}</span></span></label>)}</div>:<p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">Nenhuma cartela disponível para esse filtro.</p>}
        </Card>
        <Card><h2 className="text-lg font-black">Registrar operação</h2><p className="mt-1 text-sm text-slate-500">{selected.length} cartela(s) selecionada(s).</p><div className="mt-4 space-y-3"><Input placeholder={currentEvent?.settings.require_buyer_name?'Nome do comprador *':'Nome do comprador'} value={buyer.name} onChange={e=>setBuyer(v=>({...v,name:e.target.value}))}/><Input placeholder={currentEvent?.settings.require_buyer_phone?'Telefone *':'Telefone'} value={buyer.phone} onChange={e=>setBuyer(v=>({...v,phone:e.target.value}))}/><Input type="email" placeholder={currentEvent?.settings.require_buyer_email?'E-mail *':'E-mail'} value={buyer.email} onChange={e=>setBuyer(v=>({...v,email:e.target.value}))}/><Input inputMode="decimal" placeholder="Valor por cartela" value={price} onChange={e=>setPrice(e.target.value)}/><Textarea placeholder="Observação opcional" value={buyer.notes} onChange={e=>setBuyer(v=>({...v,notes:e.target.value}))}/></div><div className="mt-4 rounded-2xl bg-slate-50 p-4"><div className="flex justify-between text-sm"><span>Total</span><strong>{money(total,currentEvent?.settings.currency||'BRL')}</strong></div>{selectedCards.length>0&&<p className="mt-2 text-xs text-slate-500">{selectedCards.slice(0,6).map(c=>c.code).join(', ')}{selectedCards.length>6?'…':''}</p>}</div><div className="mt-4 grid gap-2"><Button onClick={()=>void submit(false)} disabled={saving||!selected.length}>Confirmar venda</Button>{currentEvent?.settings.allow_reservations&&<Button variant="secondary" onClick={()=>void submit(true)} disabled={saving||!selected.length}>Reservar por {currentEvent.settings.reservation_minutes} min</Button>}</div></Card>
      </div>
      <Card><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-lg font-black">Histórico de vendas</h2><p className="text-sm text-slate-500">Cancelamentos preservam o histórico e liberam a cartela somente quando a rodada ainda não começou.</p></div><label className="text-sm font-semibold">Status<Select className="mt-1" value={statusFilter} onChange={e=>setStatusFilter(e.target.value as ''|SaleStatus)}><option value="">Todos</option><option value="completed">Concluídas</option><option value="reserved">Reservadas</option><option value="canceled">Canceladas</option></Select></label></div>
        <div className="mt-4 space-y-3">{sales.length?sales.map(s=><div key={s.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><StatusBadge tone={s.status==='completed'?'success':s.status==='reserved'?'warning':'neutral'}>{saleStatusLabel[s.status]}</StatusBadge><span className="text-xs text-slate-500">{new Date(s.created_at).toLocaleString('pt-BR')}</span></div><p className="mt-2 font-bold">{s.buyer_name||'Comprador não informado'}</p><p className="break-words text-sm text-slate-600">{s.items.filter(i=>i.status==='active').map(i=>i.card.code).join(', ')||'Itens cancelados'}</p><p className="mt-1 text-sm font-semibold">{money(Number(s.total_amount),s.currency)}</p>{s.reservation_expires_at&&s.status==='reserved'&&<p className="mt-1 text-xs text-amber-700">Reserva até {new Date(s.reservation_expires_at).toLocaleString('pt-BR')}</p>}{s.cancel_reason&&<p className="mt-1 text-xs text-slate-500">Motivo: {s.cancel_reason}</p>}</div>{s.status!=='canceled'&&<div className="flex flex-wrap gap-2">{s.status==='reserved'&&<Button onClick={()=>void finalize(s.id)} disabled={saving}>Concluir venda</Button>}<Button variant="secondary" onClick={()=>void cancel(s.id)} disabled={saving}>Cancelar</Button></div>}</div></div>):<p className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-500">Nenhuma operação registrada.</p>}</div>
      </Card>
    </>}
  </div>
}
function Metric({label,value}:{label:string;value:string|number}){return <Card><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></Card>}
function money(value:number,currency:string){try{return new Intl.NumberFormat('pt-BR',{style:'currency',currency}).format(value)}catch{return `R$ ${value.toFixed(2).replace('.',',')}`}}
