import { useCallback,useEffect,useMemo,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import { useWorkspace } from '@/app/providers/WorkspaceProvider'
import { Button } from '@/components/ui/Button'
import { Card } from '@/components/ui/Card'
import { Input } from '@/components/ui/Input'
import { Select } from '@/components/ui/Select'
import { PrintableCard } from '@/components/cards/PrintableCard'
import { getEvent } from '@/features/events/eventService'
import { allowedCardsPerSheet,bestGrid,chunk,paperSpec,type PrintOrientation,type PrintPaper } from '@/domain/cards/imposition'
import { getCardBatch,listBatchCardsForPrint,registerPrint,type PhysicalCardView } from './cardService'
import type { CardBatch,EventWithSettings } from '@/types/database'

export function BatchPrintPage(){const {eventId,batchId}=useParams();const {currentWorkspace}=useWorkspace();const nav=useNavigate();const [event,setEvent]=useState<EventWithSettings|null>(null);const [batch,setBatch]=useState<CardBatch|null>(null);const [cards,setCards]=useState<PhysicalCardView[]>([]);const [paper,setPaper]=useState<PrintPaper>('A4');const [orientation,setOrientation]=useState<PrintOrientation>('portrait');const [perSheet,setPerSheet]=useState(2);const [sheetsPerPdf,setSheetsPerPdf]=useState(25);const [part,setPart]=useState(1);const [loading,setLoading]=useState(true);const [preparing,setPreparing]=useState(false);const [error,setError]=useState<string|null>(null)
 const allowed=useMemo(()=>allowedCardsPerSheet(paper,orientation),[paper,orientation]);useEffect(()=>{if(!allowed.includes(perSheet))setPerSheet(allowed.at(-1)??1)},[allowed,perSheet]);useEffect(()=>setPart(1),[paper,orientation,perSheet,sheetsPerPdf])
 const loadHeader=useCallback(async()=>{if(!currentWorkspace||!eventId||!batchId)return;setLoading(true);try{const [e,b]=await Promise.all([getEvent(currentWorkspace.id,eventId),getCardBatch(currentWorkspace.id,eventId,batchId)]);setEvent(e);setBatch(b)}catch{setError('Não foi possível preparar o lote para impressão.')}finally{setLoading(false)}},[currentWorkspace,eventId,batchId]);useEffect(()=>{void loadHeader()},[loadHeader])
 const totalCards=batch?.generated_cards??0,totalSheets=Math.ceil(totalCards/perSheet),totalParts=Math.max(1,Math.ceil(totalSheets/Math.max(1,sheetsPerPdf))),cardsPerPart=perSheet*Math.max(1,sheetsPerPdf),offset=(part-1)*cardsPerPart
 const grid=bestGrid(perSheet,paper,orientation),spec=paperSpec(paper,orientation),sheets=chunk(cards,perSheet)
 async function prepare(){if(!currentWorkspace||!eventId||!batchId)return;setPreparing(true);setError(null);try{setCards(await listBatchCardsForPrint(currentWorkspace.id,eventId,batchId,offset,Math.min(cardsPerPart,500)))}catch{setError('Não foi possível carregar este bloco de cartelas.')}finally{setPreparing(false)}}
 async function print(){if(!batchId||!cards.length)return;try{await registerPrint(batchId,cards.map(c=>c.id))}catch{setError('O PDF pode ser salvo, mas o histórico de impressão não pôde ser atualizado.')}window.print()}
 if(loading)return <Card>Preparando impressão…</Card>;if(error&&!batch)return <Card>{error}</Card>;if(!event||!batch)return <Card>Lote indisponível.</Card>
 const style=`@media print{@page{size:${spec.width}mm ${spec.height}mm;margin:0}html,body{background:#fff!important}.imposition-page{width:${spec.width}mm!important;height:${spec.height}mm!important;padding:6mm!important;grid-template-columns:repeat(${grid.cols},${grid.cardWidth}mm)!important;grid-auto-rows:${grid.cardHeight}mm!important;gap:3mm!important;align-content:start;justify-content:center}}`
 return <div className="space-y-5"><style>{style}</style><div className="no-print"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-sm font-semibold text-red-400">Impressão inteligente</p><h1 className="text-3xl font-black">Preparar PDF</h1><p className="mt-1 max-w-3xl text-sm text-slate-500">O BINGOUP carrega somente o bloco do PDF atual para economizar memória e deixar o arquivo mais leve.</p></div><Button variant="secondary" onClick={()=>nav(-1)}>Voltar</Button></div>
 <Card className="mt-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><label className="text-sm font-semibold">Tamanho da folha<Select className="mt-1" value={paper} onChange={e=>setPaper(e.target.value as PrintPaper)}><option value="A5">A5</option><option value="A4">A4</option><option value="A3">A3</option><option value="letter">Carta</option><option value="legal">Ofício / Legal</option></Select></label><label className="text-sm font-semibold">Orientação<Select className="mt-1" value={orientation} onChange={e=>setOrientation(e.target.value as PrintOrientation)}><option value="portrait">Retrato</option><option value="landscape">Paisagem</option></Select></label><label className="text-sm font-semibold">Cartelas por folha<Select className="mt-1" value={perSheet} onChange={e=>setPerSheet(Number(e.target.value))}>{allowed.map(v=><option key={v} value={v}>{v} por folha</option>)}</Select></label><label className="text-sm font-semibold">Folhas por PDF<Input className="mt-1" type="number" min={1} max={50} value={sheetsPerPdf} onChange={e=>setSheetsPerPdf(Math.max(1,Math.min(50,Number(e.target.value))))}/></label><label className="text-sm font-semibold">Arquivo<Select className="mt-1" value={part} onChange={e=>setPart(Number(e.target.value))}>{Array.from({length:totalParts},(_,i)=><option key={i+1} value={i+1}>PDF {i+1} de {totalParts}</option>)}</Select></label></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Cartelas" value={totalCards.toLocaleString('pt-BR')}/><Metric label="Folhas" value={totalSheets.toLocaleString('pt-BR')}/><Metric label="Arquivos PDF" value={totalParts.toLocaleString('pt-BR')}/><Metric label="Cartela aproximada" value={`${grid.cardWidth.toFixed(0)} × ${grid.cardHeight.toFixed(0)} mm`}/></div>
 <div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">Cada PDF terá no máximo {sheetsPerPdf} folha(s). O fundo otimizado é reutilizado em todas as cartelas do bloco.</p><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={preparing} onClick={()=>void prepare()}>{preparing?'Carregando…':'Preparar este PDF'}</Button><Button disabled={!cards.length} onClick={()=>void print()}>Gerar / Imprimir PDF</Button></div></div></Card>{error&&<div className="mt-3 rounded-xl bg-red-950/40 p-3 text-sm text-red-300">{error}</div>}</div>
 {cards.length?<div className="print-area space-y-4">{sheets.map((sheet,index)=><section key={index} className="imposition-page" style={{width:`${spec.width}mm`,height:`${spec.height}mm`,gridTemplateColumns:`repeat(${grid.cols},minmax(0,${grid.cardWidth}mm))`,gridAutoRows:`${grid.cardHeight}mm`}}>{sheet.map(card=><PrintableCard key={card.id} card={card} event={event}/>)}</section>)}</div>:<Card className="no-print"><p className="text-sm text-slate-500">Escolha as opções acima e clique em <b>Preparar este PDF</b>. Nada pesado é carregado antes disso.</p></Card>}</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-950/50 p-3"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 font-black text-slate-100">{value}</p></div>}
