import { useCallback,useEffect,useMemo,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import { useWorkspace } from '@/app/providers/WorkspaceProvider'
import { Card } from '@/components/ui/Card';import { Button } from '@/components/ui/Button';import { Input } from '@/components/ui/Input';import { Select } from '@/components/ui/Select';import { StatusBadge } from '@/components/ui/StatusBadge'
import { listCardBatches } from '@/features/card-generator/cardGenerationService';import { listEventCards } from './cardService';import type { CardBatch,PhysicalCardStatus } from '@/types/database'
const labels:Record<PhysicalCardStatus,string>={available:'Disponível',reserved:'Reservada',sold:'Vendida',canceled:'Cancelada',void:'Anulada'}
export function CardsPage(){const {eventId}=useParams();const {currentWorkspace}=useWorkspace();const [batches,setBatches]=useState<CardBatch[]>([]);const [cards,setCards]=useState<any[]>([]);const [batchId,setBatchId]=useState('');const [status,setStatus]=useState('');const [search,setSearch]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null)
 const load=useCallback(async()=>{if(!currentWorkspace||!eventId)return;setLoading(true);setError(null);try{const [b,c]=await Promise.all([listCardBatches(currentWorkspace.id,eventId),listEventCards(currentWorkspace.id,eventId,{batchId:batchId||undefined,status:(status||undefined) as PhysicalCardStatus|undefined,search:search||undefined})]);setBatches(b);setCards(c)}catch{setError('Não foi possível carregar as cartelas.')}finally{setLoading(false)}},[currentWorkspace,eventId,batchId,status,search]);useEffect(()=>{void load()},[load]);const counts=useMemo(()=>cards.reduce((a,c)=>(a[c.status]=(a[c.status]??0)+1,a),{} as Record<string,number>),[cards])
 return <div className="space-y-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-emerald-700">Cartelas</p><h1 className="text-3xl font-black">Cartelas emitidas</h1><p className="mt-1 text-sm text-slate-600">Consulte, visualize e imprima sem alterar os números gerados.</p></div><div className="flex gap-2"><Link to={`/eventos/${eventId}/cartelas/gerar`}><Button>Gerar lote</Button></Link>{batchId&&<Link to={`/eventos/${eventId}/cartelas/lote/${batchId}/imprimir`}><Button variant="secondary">Imprimir lote</Button></Link>}</div></div>
 <div className="grid gap-3 sm:grid-cols-4"><Metric t="Exibidas" v={cards.length}/><Metric t="Disponíveis" v={counts.available??0}/><Metric t="Vendidas" v={counts.sold??0}/><Metric t="Anuladas" v={counts.void??0}/></div>
 <Card><div className="grid gap-3 md:grid-cols-3"><label className="text-sm font-semibold">Buscar código<Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ex.: A-000125" className="mt-1"/></label><label className="text-sm font-semibold">Lote<Select value={batchId} onChange={e=>setBatchId(e.target.value)} className="mt-1"><option value="">Todos</option>{batches.filter(b=>b.status==='completed').map(b=><option key={b.id} value={b.id}>{b.series_code} · {b.generated_cards} cartelas</option>)}</Select></label><label className="text-sm font-semibold">Status<Select value={status} onChange={e=>setStatus(e.target.value)} className="mt-1"><option value="">Todos</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select></label></div></Card>
 {error&&<div className="rounded-2xl bg-red-50 p-4 text-red-700">{error}</div>}{loading?<Card>Carregando…</Card>:cards.length===0?<Card>Nenhuma cartela encontrada.</Card>:<div className="grid gap-3">{cards.map(c=><Link key={c.id} to={`/eventos/${eventId}/cartelas/${c.id}`} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:border-emerald-300"><div className="flex items-center justify-between gap-3"><div><p className="text-lg font-black">{c.code}</p><p className="text-xs text-slate-500">{c.physical_format} em 1 · Série {c.batch.series_code}</p></div><StatusBadge tone={c.status==='available'?'success':c.status==='sold'?'info':c.status==='void'?'danger':'neutral'}>{labels[c.status as PhysicalCardStatus]}</StatusBadge></div></Link>)}</div>}</div>}
function Metric({t,v}:{t:string;v:number}){return <Card><p className="text-xs font-bold uppercase text-slate-500">{t}</p><p className="mt-1 text-2xl font-black">{v}</p></Card>}
