import { useCallback,useEffect,useState } from 'react';import { Link,useNavigate,useParams } from 'react-router-dom';import { useWorkspace } from '@/app/providers/WorkspaceProvider';import { Card } from '@/components/ui/Card';import { Button } from '@/components/ui/Button';import { StatusBadge } from '@/components/ui/StatusBadge';import { PrintableCard } from '@/components/cards/PrintableCard';import { getEvent } from '@/features/events/eventService';import { getPhysicalCard,voidPhysicalCard,type PhysicalCardView } from './cardService';import type { EventWithSettings } from '@/types/database'
const statusLabel={available:'Disponível',reserved:'Reservada',sold:'Vendida',canceled:'Cancelada',void:'Anulada'} as const
export function CardDetailPage(){const {eventId,cardId}=useParams();const {currentWorkspace}=useWorkspace();const nav=useNavigate();const [card,setCard]=useState<PhysicalCardView|null>(null);const [event,setEvent]=useState<EventWithSettings|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false)
 const load=useCallback(async()=>{if(!currentWorkspace||!eventId||!cardId)return;try{const [c,e]=await Promise.all([getPhysicalCard(currentWorkspace.id,eventId,cardId),getEvent(currentWorkspace.id,eventId)]);setCard(c);setEvent(e)}catch{setError('Cartela não encontrada ou acesso negado.')}},[currentWorkspace,eventId,cardId]);useEffect(()=>{void load()},[load]);async function voidCard(){if(!card||!confirm(`Anular ${card.code}? Esta ação preserva o histórico e impede uso futuro.`))return;setBusy(true);try{await voidPhysicalCard(card.id,'Anulada pelo organizador');await load()}catch{setError('Só cartelas disponíveis e ainda não usadas podem ser anuladas.')}finally{setBusy(false)}}
 if(error&&!card)return <Card>{error}</Card>;if(!card||!event)return <Card>Carregando…</Card>
 const sale=card.sale
 return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-red-400">Cartela física</p><div className="mt-1 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-black text-white">{card.code}</h1><StatusBadge tone={card.status==='available'?'success':card.status==='sold'?'info':card.status==='reserved'?'warning':card.status==='void'?'danger':'neutral'}>{statusLabel[card.status]}</StatusBadge></div><p className="text-sm text-slate-500">{card.physical_format} em 1 · Série {card.batch.series_code} · sequência #{card.sequence_number}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>nav(-1)}>Voltar</Button><Button variant="secondary" onClick={()=>window.print()}>Imprimir</Button>{card.status==='available'&&<Button variant="danger" disabled={busy} onClick={()=>void voidCard()}>Anular</Button>}</div></div>{error&&<div className="rounded-xl border border-red-900/60 bg-red-950/30 p-3 text-red-300">{error}</div>}<div className="print-area"><PrintableCard card={card} event={event}/></div>
 {sale&&<Card><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Rastreabilidade da venda</p><h2 className="mt-1 text-lg font-black text-white">{sale.buyer_name||'Comprador não informado'}</h2><p className="mt-1 text-sm text-slate-400">{[sale.buyer_phone,sale.buyer_email].filter(Boolean).join(' · ')||'Sem contato informado'}</p></div><StatusBadge tone={sale.status==='completed'?'success':sale.status==='reserved'?'warning':'neutral'}>{sale.status==='completed'?'Venda concluída':sale.status==='reserved'?'Reservada':'Cancelada'}</StatusBadge></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Info label="Valor da operação" value={money(Number(sale.total_amount),sale.currency)}/><Info label="Registrada em" value={new Date(sale.created_at).toLocaleString('pt-BR')}/><Info label="Canal" value={sale.channel==='organizer'?'Organizador':sale.channel}/></div>{sale.reservation_expires_at&&sale.status==='reserved'&&<p className="mt-3 text-sm text-amber-400">Reserva válida até {new Date(sale.reservation_expires_at).toLocaleString('pt-BR')}.</p>}{sale.buyer_notes&&<p className="mt-3 text-sm text-slate-400">Observação: {sale.buyer_notes}</p>}</Card>}
 <Card><p className="font-bold text-white">Integridade do lote</p><p className="mt-2 text-sm text-slate-400">Os números e a configuração visual desta emissão pertencem ao lote gerado. Para criar uma versão diferente, gere um novo lote.</p><Link to={`/eventos/${eventId}/cartelas/lote/${card.batch_id}/imprimir`} className="mt-3 inline-block text-sm font-bold text-red-400">Abrir impressão do lote</Link></Card></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-slate-800 bg-slate-950/30 p-3"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-sm font-semibold text-white">{value}</p></div>}
function money(value:number,currency:string){try{return new Intl.NumberFormat('pt-BR',{style:'currency',currency}).format(value)}catch{return `R$ ${value.toFixed(2).replace('.',',')}`}}
