-- Central do comprador: histórico de prêmios e indicação de cartelas premiadas.
create or replace function public.get_my_buyer_event(target_event_id uuid)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare my_email text; draw_token uuid; event_row public.events%rowtype; win_count int; latest_session_id uuid; latest_prize text; my_latest_winners int:=0; total_latest_winners int:=0; buyer_label text;
begin
 if auth.uid() is null then raise exception 'authentication required'; end if;
 select lower(email) into my_email from auth.users where id=auth.uid();
 if my_email is null then raise exception 'buyer email unavailable'; end if;
 if not exists(select 1 from public.sales s join public.sale_items si on si.sale_id=s.id and si.status='active' join public.physical_cards pc on pc.id=si.physical_card_id and pc.status='sold' where s.event_id=target_event_id and s.status='completed' and lower(trim(coalesce(s.buyer_email,'')))=trim(my_email)) then raise exception 'buyer access denied'; end if;
 select * into event_row from public.events where id=target_event_id;
 select ds.public_token into draw_token from public.draw_sessions ds where ds.event_id=target_event_id order by case when ds.status in ('active','paused') then 0 else 1 end,ds.session_number desc limit 1;
 select count(*) into win_count from public.winners wi join public.sale_items si on si.physical_card_id=wi.physical_card_id and si.status='active' join public.sales s on s.id=si.sale_id and s.status='completed' where wi.event_id=target_event_id and lower(trim(coalesce(s.buyer_email,'')))=trim(my_email);
 select wi.session_id,coalesce(nullif(trim(ds.name),''),'Rodada '||ds.session_number::text) into latest_session_id,latest_prize from public.winners wi join public.draw_sessions ds on ds.id=wi.session_id join public.sale_items si on si.physical_card_id=wi.physical_card_id and si.status='active' join public.sales s on s.id=si.sale_id and s.status='completed' where wi.event_id=target_event_id and lower(trim(coalesce(s.buyer_email,'')))=trim(my_email) order by wi.confirmed_at desc limit 1;
 if latest_session_id is not null then select count(*) into total_latest_winners from public.winners where session_id=latest_session_id; select count(*) into my_latest_winners from public.winners wi join public.sale_items si on si.physical_card_id=wi.physical_card_id and si.status='active' join public.sales s on s.id=si.sale_id and s.status='completed' where wi.session_id=latest_session_id and lower(trim(coalesce(s.buyer_email,'')))=trim(my_email); end if;
 select nullif(trim(s.buyer_name),'') into buyer_label from public.sales s where s.event_id=target_event_id and s.status='completed' and lower(trim(coalesce(s.buyer_email,'')))=trim(my_email) and nullif(trim(s.buyer_name),'') is not null order by s.completed_at desc nulls last limit 1;
 return jsonb_build_object(
 'event',jsonb_build_object('id',event_row.id,'name',event_row.name,'status',event_row.status),'public_session_token',draw_token,'winner_count',win_count,'winner_prizes','[]'::jsonb,
 'latest_win',case when latest_session_id is null then null else jsonb_build_object('prize',latest_prize,'my_winners',my_latest_winners,'total_winners',total_latest_winners,'buyer_name',buyer_label) end,
 'wins',coalesce((select jsonb_agg(jsonb_build_object('winner_id',wi.id,'prize',coalesce(nullif(ds.win_pattern_snapshot->>'name',''),ds.win_pattern_code),'round_name',coalesce(nullif(trim(ds.name),''),'Rodada '||ds.session_number::text),'card_code',pc.code,'game_position',cg.position,'confirmed_at',wi.confirmed_at,'delivered',coalesce(pd.delivered,false)) order by wi.confirmed_at desc) from public.winners wi join public.draw_sessions ds on ds.id=wi.session_id join public.physical_cards pc on pc.id=wi.physical_card_id join public.card_games cg on cg.id=wi.card_game_id join public.sale_items si on si.physical_card_id=pc.id and si.status='active' join public.sales s on s.id=si.sale_id and s.status='completed' left join public.winner_prize_deliveries pd on pd.winner_id=wi.id where wi.event_id=target_event_id and lower(trim(coalesce(s.buyer_email,'')))=trim(my_email)),'[]'::jsonb),
 'cards',coalesce((select jsonb_agg(jsonb_build_object('id',pc.id,'code',pc.code,'public_token',pc.public_token,'physical_format',pc.physical_format,'buyer_name',s.buyer_name,'is_winner',exists(select 1 from public.winners wi where wi.event_id=target_event_id and wi.physical_card_id=pc.id)) order by pc.sequence_number) from public.sales s join public.sale_items si on si.sale_id=s.id and si.status='active' join public.physical_cards pc on pc.id=si.physical_card_id and pc.status='sold' where s.event_id=target_event_id and s.status='completed' and lower(trim(coalesce(s.buyer_email,'')))=trim(my_email)),'[]'::jsonb));
end; $$;
revoke all on function public.get_my_buyer_event(uuid) from public; grant execute on function public.get_my_buyer_event(uuid) to authenticated;
