export type SymbolItem={symbol:string;label:string;riddle:string}
export type SymbolTheme={id:string;name:string;items:SymbolItem[]}

const make=(rows:Array<[string,string,string]>):SymbolItem[]=>rows.map(([symbol,label,riddle])=>({symbol,label,riddle}))
export const SYMBOL_THEMES:SymbolTheme[]=[
 {id:'festa-junina',name:'Festa junina',items:make([
 ['🔥','Fogueira','Ilumino o arraial e aqueço a noite. Quem sou?'],['🌽','Milho','Viro pipoca, pamonha e curau. Quem sou?'],['🎈','Balão','Sou colorido e enfeito o céu, mas não devo ser solto.'],['🤠','Chapéu','Fico na cabeça do caipira.'],['🏳️','Bandeirinha','Em fileiras coloridas, enfeito o arraial.'],['💃','Quadrilha','Tem casamento, passos e muita dança.'],['🍿','Pipoca','Sou pequena, branca e pulo na panela.'],['🥜','Amendoim','Sou grão e viro paçoca.'],['🍎','Maçã do amor','Sou fruta vermelha coberta de doce.'],['🎵','Sanfona','Abro e fecho para animar o forró.'],['🌭','Cachorro-quente','Vou no pão com molho e festa.'],['🧁','Bolo','Sou servido em fatias na mesa.'],['🌾','Palha','Visto espantalhos e enfeito a roça.'],['🎣','Pescaria','Tenho peixinhos numerados e vara.'],['💌','Correio elegante','Levo um recado carinhoso no arraial.'],['👰','Noiva','Sou personagem do casamento caipira.'],['🫘','Feijão','Sou grão comum na roça e no prato.'],['☕','Quentão','Sou bebida quente e perfumada da festa.'],['🪗','Forró','Meu ritmo faz todo mundo dançar.'],['🌟','Estrela','Brilho na decoração e no céu.'],['🐓','Galo','Canto cedo no terreiro.'],['🚜','Trator','Ajudo no trabalho da roça.'],['🌻','Girassol','Minha flor parece acompanhar o sol.'],['🎊','Arraial','Sou o lugar de toda essa festa.'],['🥮','Paçoca','Sou doce feito principalmente de amendoim.']])},
 {id:'casamento',name:'Casamento',items:make([
 ['💍','Aliança','Sou um círculo que representa uma promessa.'],['💐','Buquê','Sou um conjunto de flores carregado pela noiva.'],['👰','Noiva','Uso vestido especial e caminho até o altar.'],['🤵','Noivo','Espero minha pessoa amada no altar.'],['🎂','Bolo','Tenho camadas e sou cortado na festa.'],['🥂','Brinde','Erguemos as taças para celebrar.'],['💌','Convite','Conto data e local da celebração.'],['📸','Fotografia','Guardo para sempre um instante do grande dia.'],['🎵','Música','Embalo a entrada e a dança.'],['💃','Dança','Os recém-casados costumam me abrir no salão.'],['🌹','Rosa','Sou flor clássica do romance.'],['🕯️','Vela','Trago luz e clima acolhedor.'],['🎁','Presente','Chego embrulhado para o casal.'],['🏛️','Altar','É diante de mim que as promessas são feitas.'],['❤️','Amor','Sou o principal motivo desta união.'],['🕊️','Paz','Sou desejo para a nova família.'],['🍾','Espumante','Minha rolha pode estourar na comemoração.'],['👗','Vestido','Sou a roupa mais esperada da cerimônia.'],['🤝','Compromisso','Sou uma escolha renovada a cada dia.'],['🏠','Lar','Sou construído pelo casal, além das paredes.'],['🌸','Flor','Decoro mesas, caminho e buquê.'],['🚗','Carro','Levo o casal e às vezes ganho enfeites.'],['📖','Votos','Sou palavras de promessa ditas na cerimônia.'],['✨','Felicidade','Sou o desejo de todos para os noivos.'],['🔔','Sino','Meu som anuncia uma celebração.']])},
 {id:'religioso',name:'Bíblico / religioso',items:make([
 ['✝️','Cruz','Nela Jesus demonstrou seu amor por nós.'],['📖','Bíblia','Sou uma biblioteca de livros e a Palavra de Deus.'],['🕊️','Pomba','Sou símbolo de paz e do Espírito Santo.'],['🐟','Peixe','Fui sinal usado pelos primeiros cristãos.'],['🍞','Pão','Jesus disse que eu representava seu corpo.'],['🍇','Uva','Meu fruto lembra a videira e produz vinho.'],['🐑','Ovelha','Conheço a voz do meu pastor.'],['🛡️','Escudo','Na fé, apago os dardos do inimigo.'],['👑','Coroa','Represento realeza e recompensa.'],['🌈','Arco-íris','Fui sinal da aliança depois do dilúvio.'],['⛵','Arca','Protegi uma família e muitos animais.'],['🪨','Pedra','Cinco de mim foram escolhidas por Davi.'],['🎺','Trombeta','Meu som aparece em grandes anúncios bíblicos.'],['🕯️','Luz','Jesus disse que seus seguidores são do mundo.'],['🌱','Semente','Mesmo pequena, posso crescer e dar frutos.'],['🫶','Amor','Sou paciente, bondoso e não invejo.'],['🙏','Oração','Por mim conversamos com Deus.'],['💧','Água','No batismo, simbolizo uma nova vida.'],['⭐','Estrela','Guiei visitantes até Jesus menino.'],['🔥','Fogo','Apareci sobre os discípulos em Pentecostes.'],['🪔','Lâmpada','Com azeite, iluminei uma parábola de espera.'],['🐋','Grande peixe','Recebi Jonas por três dias.'],['🦁','Leão','Daniel ficou em uma cova cheia de nós.'],['🌿','Palmeira','Meus ramos receberam Jesus em Jerusalém.'],['🍎','Fruto','Uma árvore boa é conhecida por mim.']])},
]
export const getTheme=(id:string):SymbolTheme=>SYMBOL_THEMES.find(t=>t.id===id)??SYMBOL_THEMES[0]!

export function generateSymbolCards(items:SymbolItem[],gridSize:number,quantity:number,seed=1){
 const needed=gridSize*gridSize; if(items.length<needed)throw new Error(`Cadastre pelo menos ${needed} símbolos.`)
 return Array.from({length:quantity},(_,card)=>items.map((item,index)=>({item,key:((index+1)*1103515245+(card+seed)*12345)>>>0})).sort((a,b)=>a.key-b.key).slice(0,needed).map(v=>v.item))
}
