import {useCallback,useEffect,useMemo,useRef,useState,type CSSProperties} from 'react'
import {useParams} from 'react-router-dom'
import {buildPublicBoardColumns,recentCalledNumbers} from '@/domain/draw/publicBoard'
import {DEFAULT_PUBLIC_PANEL_APPEARANCE,normalizePublicPanelAppearance,type PublicPanelAppearance,type PublicPanelTheme} from '@/domain/draw/publicPanelAppearance'
import {getPublicPanelState,type PublicPanelState} from './publicPanelService'

type ScreenMode='portrait'|'landscape'|'wide'
type ThemeTokens={bg:string;panel:string;panel2:string;accent:string;accent2:string;text:string;muted:string;line:string;hot:string;calledText:string}
const THEMES:Record<PublicPanelTheme,ThemeTokens>={
  classic:{bg:'#080808',panel:'#111318',panel2:'#171a21',accent:'#ef1b24',accent2:'#ff5a62',text:'#fff',muted:'#8e939c',line:'rgba(255,255,255,.11)',hot:'#fbbf24',calledText:'#fff'},
  neon:{bg:'#03040b',panel:'#080d18',panel2:'#0a1322',accent:'#00f0ff',accent2:'#ff2bd6',text:'#ecfeff',muted:'#79a8b2',line:'rgba(0,240,255,.22)',hot:'#faff00',calledText:'#001013'},
  gold:{bg:'#080604',panel:'#151008',panel2:'#21180c',accent:'#dcae35',accent2:'#fff0a8',text:'#fff9e9',muted:'#ae9d72',line:'rgba(220,174,53,.25)',hot:'#ffd75a',calledText:'#201500'},
  party:{bg:'#090512',panel:'#151023',panel2:'#201433',accent:'#ff3d9a',accent2:'#7c5cff',text:'#fff',muted:'#bba7cf',line:'rgba(255,61,154,.22)',hot:'#ffe24a',calledText:'#fff'},
  elegant:{bg:'#090b0f',panel:'#14171c',panel2:'#1a1f25',accent:'#c4a77d',accent2:'#e8dcc7',text:'#f4efe8',muted:'#99938b',line:'rgba(196,167,125,.2)',hot:'#d9bd8c',calledText:'#15120e'},
  minimal:{bg:'#f3f4f6',panel:'#ffffff',panel2:'#f8fafc',accent:'#111827',accent2:'#374151',text:'#111827',muted:'#6b7280',line:'rgba(17,24,39,.12)',hot:'#b45309',calledText:'#fff'},
  led:{bg:'#020503',panel:'#051009',panel2:'#07160c',accent:'#32ff72',accent2:'#a8ffc1',text:'#ddffe6',muted:'#5a9770',line:'rgba(50,255,114,.18)',hot:'#ffe34d',calledText:'#001707'},
  colorful:{bg:'#080b16',panel:'#11182b',panel2:'#17233e',accent:'#5ee7ff',accent2:'#ff6bb5',text:'#fff',muted:'#9fb0d1',line:'rgba(94,231,255,.18)',hot:'#ffd75a',calledText:'#08111f'},
}
function getScreenMode():ScreenMode{const ratio=window.innerWidth/Math.max(1,window.innerHeight);if(ratio<.9)return'portrait';if(ratio>1.7)return'wide';return'landscape'}
function themeStyle(theme:PublicPanelTheme):CSSProperties{const t=THEMES[theme];return {'--tv-bg':t.bg,'--tv-panel':t.panel,'--tv-panel2':t.panel2,'--tv-accent':t.accent,'--tv-accent2':t.accent2,'--tv-text':t.text,'--tv-muted':t.muted,'--tv-line':t.line,'--tv-hot':t.hot,'--tv-called-text':t.calledText} as CSSProperties}

export function PublicPanelPage(){
  const {publicSessionId}=useParams();const [state,setState]=useState<PublicPanelState|null>(null);const [error,setError]=useState<string|null>(null);const [connected,setConnected]=useState(true);const [screenMode,setScreenMode]=useState<ScreenMode>(()=>getScreenMode());const [fullscreen,setFullscreen]=useState(()=>Boolean(document.fullscreenElement));const explicitFullscreenExit=useRef(false);const [fullscreenWanted,setFullscreenWanted]=useState(()=>sessionStorage.getItem('bingoup:tv-fullscreen-wanted')==='1');const loadingRef=useRef(false);const hasStateRef=useRef(false)
  const load=useCallback(async()=>{if(!publicSessionId||loadingRef.current)return;loadingRef.current=true;try{const next=await getPublicPanelState(publicSessionId);setState(current=>{hasStateRef.current=true;if(!current)return next;if(next.session_number<current.session_number)return current;return next});setError(null);setConnected(true)}catch{setConnected(false);if(!hasStateRef.current)setError('Este painel não está disponível ou o link é inválido.')}finally{loadingRef.current=false}},[publicSessionId])
  useEffect(()=>{void load()},[load]);useEffect(()=>{const refresh=()=>void load();const id=window.setInterval(refresh,800);window.addEventListener('online',refresh);window.addEventListener('focus',refresh);return()=>{window.clearInterval(id);window.removeEventListener('online',refresh);window.removeEventListener('focus',refresh)}},[load])
  useEffect(()=>{const resize=()=>setScreenMode(getScreenMode());window.addEventListener('resize',resize);window.addEventListener('orientationchange',resize);return()=>{window.removeEventListener('resize',resize);window.removeEventListener('orientationchange',resize)}},[])
  useEffect(()=>{const changed=()=>{const active=Boolean(document.fullscreenElement);setFullscreen(active);if(active){setFullscreenWanted(true);sessionStorage.setItem('bingoup:tv-fullscreen-wanted','1')}else if(explicitFullscreenExit.current){explicitFullscreenExit.current=false;setFullscreenWanted(false);sessionStorage.removeItem('bingoup:tv-fullscreen-wanted')}};document.addEventListener('fullscreenchange',changed);return()=>document.removeEventListener('fullscreenchange',changed)},[])
  const appearance=normalizePublicPanelAppearance(state?.appearance??DEFAULT_PUBLIC_PANEL_APPEARANCE);const called=useMemo(()=>new Set(state?.called_numbers??[]),[state?.called_numbers]);const columns=useMemo(()=>buildPublicBoardColumns(state?.total_balls??75),[state?.total_balls]);const recent=useMemo(()=>recentCalledNumbers(state?.called_numbers??[],screenMode==='portrait'?5:8),[state?.called_numbers,screenMode])
  async function toggleFullscreen(){if(document.fullscreenElement){explicitFullscreenExit.current=true;await document.exitFullscreen?.()}else{setFullscreenWanted(true);sessionStorage.setItem('bingoup:tv-fullscreen-wanted','1');await document.documentElement.requestFullscreen?.()}}
  if(error&&!state)return <main className="grid h-[100dvh] place-items-center overflow-hidden bg-[#080808] p-8 text-white"><div className="max-w-xl text-center"><p className="text-3xl font-black">Painel indisponível</p><p className="mt-3 text-white/55">{error}</p></div></main>
  if(!state)return <main className="grid h-[100dvh] place-items-center overflow-hidden bg-[#080808] text-white"><p className="text-xl font-bold">Carregando painel…</p></main>
  const statusLabel=state.status==='active'?'Sorteio em andamento':state.status==='paused'?'Sorteio pausado':state.status==='finished'?'Rodada encerrada':'Rodada cancelada';const compact=screenMode==='portrait'
  return <main className={`tv-public-root h-[100dvh] overflow-hidden ${appearance.animated_frame?'tv-animated-frame':''}`} style={themeStyle(appearance.theme)}>
    <div className={`mx-auto flex h-full w-full max-w-[2560px] flex-col ${compact?'p-2':'p-3 sm:p-4 xl:p-5'}`}>
      {fullscreenWanted&&!fullscreen&&<div className="mb-2 flex shrink-0 items-center justify-between gap-3 rounded-xl border border-amber-400/30 bg-amber-400/10 px-3 py-2 text-xs text-amber-100"><span>O navegador saiu do modo tela cheia. O BINGOUP não altera isso automaticamente entre rodadas.</span><button type="button" onClick={()=>void toggleFullscreen()} className="shrink-0 rounded-lg bg-amber-300 px-3 py-1.5 font-black text-black">Restaurar tela cheia</button></div>}
      <header className={`flex shrink-0 items-center justify-between gap-2 border-b ${compact?'pb-2':'pb-3'}`} style={{borderColor:'var(--tv-line)'}}><div className="min-w-0"><p className="truncate text-[10px] font-black uppercase tracking-[.24em] sm:text-xs" style={{color:'var(--tv-accent)'}}>BINGOUP · {state.event_name}</p>{appearance.show_round_name&&<h1 className={`mt-0.5 truncate font-black ${compact?'text-lg':'text-xl sm:text-2xl xl:text-3xl'}`}>{state.round_name}</h1>}</div><div className="flex shrink-0 items-center gap-2"><div className="hidden text-right sm:block"><p className="text-xs font-black uppercase tracking-wide opacity-80">{statusLabel}</p>{appearance.show_prize&&<p className="text-[11px] opacity-45">Prêmio: {state.win_pattern_name}</p>}</div><span className={`size-2.5 rounded-full ${connected?'bg-emerald-400':'bg-amber-400'}`}/><button type="button" onClick={()=>void toggleFullscreen()} className="rounded-xl border px-3 py-2 text-xs font-bold" style={{borderColor:'var(--tv-line)',background:'var(--tv-panel2)'}}>{fullscreen?'Sair da tela cheia':'Tela cheia'}</button></div></header>
      {state.confirmed_bingo?<PublicWinner state={state} appearance={appearance}/>:state.possible_bingo?<PossibleWinner appearance={appearance}/>:compact?<PortraitPanel state={state} called={called} columns={columns} recent={recent} appearance={appearance}/>:<LandscapePanel state={state} called={called} columns={columns} recent={recent} wide={screenMode==='wide'} appearance={appearance}/>}
      <footer className="flex shrink-0 items-center justify-between border-t pt-1.5 text-[9px] font-semibold uppercase tracking-wider opacity-30 sm:text-[10px]" style={{borderColor:'var(--tv-line)'}}><span>BINGOUP · Tela pública</span><span>{screenMode==='portrait'?'Vertical':screenMode==='wide'?'Panorâmica':'Horizontal'} · {connected?'Ao vivo':'Reconectando…'}</span></footer>
    </div>
  </main>
}
function LandscapePanel({state,called,columns,recent,wide,appearance}:{state:PublicPanelState;called:Set<number>;columns:ReturnType<typeof buildPublicBoardColumns>;recent:number[];wide:boolean;appearance:PublicPanelAppearance}){return <div className={`grid min-h-0 flex-1 gap-3 py-2 ${wide?'grid-cols-[minmax(220px,.48fr)_minmax(0,1.52fr)]':'grid-cols-[minmax(210px,.58fr)_minmax(0,1.42fr)]'}`}><section className="flex min-h-0 flex-col gap-2"><Panel><div className="grid h-full place-items-center p-2 text-center"><div><p className="text-xs font-black uppercase tracking-[.26em] opacity-45">Último número</p><AnimatedLastNumber number={state.last_called_number} animation={appearance.ball_animation}/></div></div></Panel>{appearance.show_recent_numbers&&recent.length>0&&<RecentNumbers recent={recent}/>} {appearance.show_counters&&<div className="grid grid-cols-2 gap-2"><Metric value={state.called_count} label={`de ${state.total_balls}`}/><Metric value={state.total_balls-state.called_count} label="restantes"/></div>}{state.show_near_winners&&<div className="grid grid-cols-2 gap-2"><NearCard value={state.one_away??0} label="Falta 1" hot/><NearCard value={state.two_away??0} label="Faltam 2"/></div>}</section><Board columns={columns} called={called} style={appearance.board_style}/></div>}
function PortraitPanel({state,called,columns,recent,appearance}:{state:PublicPanelState;called:Set<number>;columns:ReturnType<typeof buildPublicBoardColumns>;recent:number[];appearance:PublicPanelAppearance}){return <div className="grid min-h-0 flex-1 grid-rows-[auto_minmax(0,1fr)] gap-2 py-2"><section className="grid grid-cols-[1.15fr_.85fr_.85fr] gap-2"><Panel><div className="grid h-full place-items-center p-2 text-center"><div><p className="text-[9px] font-black uppercase tracking-[.18em] opacity-45">Último</p><AnimatedLastNumber number={state.last_called_number} animation={appearance.ball_animation} compact/></div></div></Panel><div className="grid gap-2">{appearance.show_counters&&<><Metric value={state.called_count} label="sorteados"/><Metric value={state.total_balls-state.called_count} label="restantes"/></>}</div><div className="grid gap-2">{state.show_near_winners?<><NearCard value={state.one_away??0} label="Falta 1" hot/><NearCard value={state.two_away??0} label="Faltam 2"/></>:appearance.show_recent_numbers?<RecentNumbers recent={recent}/>:null}</div></section><Board columns={columns} called={called} compact style={appearance.board_style}/></div>}
function AnimatedLastNumber({number,animation,compact=false}:{number:number|null;animation:PublicPanelAppearance['ball_animation'];compact?:boolean}){return <p key={number??'empty'} className={`tv-last-number tv-ball-${animation} font-black leading-[.78] tracking-tighter ${compact?'text-[clamp(3.6rem,11vh,6.5rem)]':'text-[clamp(5rem,20vh,13rem)]'}`} style={{color:'var(--tv-accent)',textShadow:'0 0 28px color-mix(in srgb,var(--tv-accent) 35%, transparent)'}}>{number??'—'}</p>}
function Board({columns,called,compact=false,style}:{columns:ReturnType<typeof buildPublicBoardColumns>;called:Set<number>;compact?:boolean;style:PublicPanelAppearance['board_style']}){return <Panel className="min-h-0 overflow-hidden"><div className="flex h-full min-h-0 flex-col p-2 sm:p-3"><div className="flex shrink-0 items-center justify-between gap-2 pb-2"><h2 className={`${compact?'text-sm':'text-base sm:text-lg'} font-black`}>Números sorteados</h2><span className="text-[9px] font-bold opacity-35 sm:text-[10px]">Atualização automática</span></div><div className={`tv-board tv-board-${style} grid min-h-0 flex-1 grid-cols-5 gap-1 sm:gap-1.5`}>{columns.map(column=><div key={column.label} className="grid min-h-0 grid-rows-[auto_minmax(0,1fr)] gap-1"><div className={`grid place-items-center font-black ${compact?'h-7 text-sm':'h-8 text-base sm:h-9 sm:text-lg'}`} style={{background:'var(--tv-accent)',color:'var(--tv-called-text)',borderRadius:style==='balls'?'999px':'10px'}}>{column.label}</div><div className="grid min-h-0 gap-0.5 sm:gap-1" style={{gridTemplateRows:`repeat(${Math.max(1,column.numbers.length)},minmax(0,1fr))`}}>{column.numbers.map(n=><div key={n} style={{fontSize:style==='giant'?'clamp(.7rem,1.9vmin,1.55rem)':'clamp(.55rem,1.55vmin,1.35rem)',borderColor:called.has(n)?'var(--tv-accent)':'var(--tv-line)',background:called.has(n)?'var(--tv-accent)':'color-mix(in srgb,var(--tv-panel2) 88%, transparent)',color:called.has(n)?'var(--tv-called-text)':'color-mix(in srgb,var(--tv-text) 28%, transparent)',borderRadius:style==='balls'?'999px':style==='cards'?'14px':style==='led'?'4px':'7px',boxShadow:called.has(n)&&style==='led'?'0 0 15px var(--tv-accent)':undefined}} className="grid min-h-0 place-items-center border font-black leading-none">{n}</div>)}</div></div>)}</div></div></Panel>}
function Panel({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`rounded-3xl border ${className}`} style={{borderColor:'var(--tv-line)',background:'var(--tv-panel)'}}>{children}</section>}
function RecentNumbers({recent}:{recent:number[]}){return <Panel><div className="p-2"><p className="text-center text-[9px] font-black uppercase tracking-[.18em] opacity-40">Últimos</p><div className="mt-1 flex flex-wrap justify-center gap-1.5">{recent.map((number,index)=><span key={`${number}-${index}`} className="grid size-8 place-items-center rounded-full border text-xs font-black" style={{borderColor:index===0?'var(--tv-accent)':'var(--tv-line)',background:index===0?'var(--tv-accent)':'var(--tv-panel2)',color:index===0?'var(--tv-called-text)':'var(--tv-text)'}}>{number}</span>)}</div></div></Panel>}
function Metric({value,label}:{value:number;label:string}){return <Panel><div className="grid h-full place-items-center p-2 text-center"><div><p className="text-2xl font-black sm:text-3xl">{value}</p><p className="text-[9px] font-bold uppercase tracking-wide opacity-40 sm:text-[10px]">{label}</p></div></div></Panel>}
function NearCard({value,label,hot=false}:{value:number;label:string;hot?:boolean}){return <section className="grid place-items-center rounded-2xl border p-2 text-center" style={{borderColor:hot?'var(--tv-hot)':'var(--tv-line)',background:hot?'color-mix(in srgb,var(--tv-hot) 10%, var(--tv-panel))':'var(--tv-panel)'}}><div><p className="text-2xl font-black sm:text-3xl" style={{color:hot?'var(--tv-hot)':'var(--tv-text)'}}>{value}</p><p className="text-[9px] font-bold uppercase tracking-wider opacity-45 sm:text-[10px]">{label}</p></div></section>}
function PossibleWinner({appearance}:{appearance:PublicPanelAppearance}){return <section className="grid min-h-0 flex-1 place-items-center py-4 text-center"><div className={`tv-possible tv-ball-${appearance.ball_animation}`}><p className="text-[clamp(3rem,10vmin,8rem)]">🏆</p><h2 className="text-[clamp(2.5rem,7vmin,7rem)] font-black leading-none tracking-tight" style={{color:'var(--tv-hot)'}}>POSSÍVEL BINGO</h2><p className="mt-4 text-[clamp(1rem,2vmin,1.8rem)] font-bold opacity-75">Sorteio pausado. Aguarde a conferência da organização.</p></div></section>}
function PublicWinner({state,appearance}:{state:PublicPanelState;appearance:PublicPanelAppearance}){return <section className="relative grid min-h-0 flex-1 place-items-center overflow-hidden py-4 text-center"><VictoryFx type={appearance.victory_animation} intensity={appearance.animation_intensity}/><div className="relative z-10 tv-winner-card"><p className="text-[clamp(3rem,10vmin,8rem)]">🏆</p><h2 className="text-[clamp(3rem,8vmin,8rem)] font-black leading-none tracking-tight" style={{color:'var(--tv-accent)'}}>GANHADOR!</h2><p className="mt-4 text-[clamp(1rem,2.2vmin,2rem)] font-bold">{state.confirmed_winners>1?`${state.confirmed_winners} vencedores confirmados`:'Vencedor confirmado'}</p>{state.winner_labels?.length>0&&<p className="mx-auto mt-3 max-w-4xl text-[clamp(.9rem,1.6vmin,1.35rem)] font-black">{state.winner_labels.join(' · ')}</p>}<p className="mt-2 text-[clamp(.85rem,1.4vmin,1.2rem)] font-semibold opacity-55">{state.win_pattern_name}</p></div></section>}
function VictoryFx({type,intensity}:{type:PublicPanelAppearance['victory_animation'];intensity:PublicPanelAppearance['animation_intensity']}){if(type==='none'||type==='elegant')return type==='elegant'?<div className="tv-elegant-glow absolute inset-[8%] rounded-[4rem]"/>:null;const count=intensity==='subtle'?18:intensity==='party'?54:34;return <div className={`tv-victory-fx tv-victory-${type} pointer-events-none absolute inset-0 overflow-hidden`}>{Array.from({length:count},(_,i)=><i key={i} style={{'--i':i,'--x':`${(i*37)%100}%`,'--delay':`${-(i%13)*.17}s`,'--dur':`${1.8+(i%7)*.19}s`} as CSSProperties}>{type==='stars'?'★':type==='fireworks'?'✦':''}</i>)}</div>}
