import {useCallback,useEffect,useMemo,useRef,useState,type CSSProperties} from 'react'
import {useParams} from 'react-router-dom'
import {buildPublicBoardColumns,recentCalledNumbers} from '@/domain/draw/publicBoard'
import {DEFAULT_PUBLIC_PANEL_APPEARANCE,normalizePublicPanelAppearance,PUBLIC_PANEL_THEME_PALETTES,type PublicPanelAppearance} from '@/domain/draw/publicPanelAppearance'
import {getPublicPanelState,type PublicPanelState} from './publicPanelService'
import {usePlatformBrand} from '@/components/brand/PlatformBrandProvider'

type ScreenMode='portrait'|'landscape'|'wide'
type PanelProps={state:PublicPanelState;called:Set<number>;columns:ReturnType<typeof buildPublicBoardColumns>;recent:number[];appearance:PublicPanelAppearance;wide?:boolean}
function getScreenMode():ScreenMode{const ratio=window.innerWidth/Math.max(1,window.innerHeight);if(ratio<.9)return'portrait';if(ratio>1.7)return'wide';return'landscape'}
function themeStyle(appearance:PublicPanelAppearance):CSSProperties{const base=PUBLIC_PANEL_THEME_PALETTES[appearance.theme];const c=appearance.use_custom_colors?{...base,...appearance.custom_colors}:base;return {'--tv-bg':c.background,'--tv-panel':c.panel,'--tv-panel2':c.panel_alt,'--tv-accent':c.accent,'--tv-accent2':c.accent_secondary,'--tv-text':c.text,'--tv-line':c.line,'--tv-hot':c.hot,'--tv-called-text':c.called_text} as CSSProperties}

export function PublicPanelPage(){
  const {publicPanelLogoUrl}=usePlatformBrand();
  const {publicSessionId}=useParams();const [state,setState]=useState<PublicPanelState|null>(null);const [error,setError]=useState<string|null>(null);const [connected,setConnected]=useState(true);const [screenMode,setScreenMode]=useState<ScreenMode>(()=>getScreenMode());const [fullscreen,setFullscreen]=useState(()=>Boolean(document.fullscreenElement));const explicitFullscreenExit=useRef(false);const [fullscreenWanted,setFullscreenWanted]=useState(()=>sessionStorage.getItem('bingoup:tv-fullscreen-wanted')==='1');const loadingRef=useRef(false);const hasStateRef=useRef(false)
  const load=useCallback(async()=>{if(!publicSessionId||loadingRef.current)return;loadingRef.current=true;try{const next=await getPublicPanelState(publicSessionId);setState(current=>{hasStateRef.current=true;if(!current)return next;if(next.session_number<current.session_number)return current;return next});setError(null);setConnected(true)}catch{setConnected(false);if(!hasStateRef.current)setError('Este painel não está disponível ou o link é inválido.')}finally{loadingRef.current=false}},[publicSessionId])
  useEffect(()=>{void load()},[load]);useEffect(()=>{const refresh=()=>void load();const id=window.setInterval(refresh,800);window.addEventListener('online',refresh);window.addEventListener('focus',refresh);return()=>{window.clearInterval(id);window.removeEventListener('online',refresh);window.removeEventListener('focus',refresh)}},[load])
  useEffect(()=>{const resize=()=>setScreenMode(getScreenMode());window.addEventListener('resize',resize);window.addEventListener('orientationchange',resize);return()=>{window.removeEventListener('resize',resize);window.removeEventListener('orientationchange',resize)}},[])
  useEffect(()=>{const changed=()=>{const active=Boolean(document.fullscreenElement);setFullscreen(active);if(active){setFullscreenWanted(true);sessionStorage.setItem('bingoup:tv-fullscreen-wanted','1')}else if(explicitFullscreenExit.current){explicitFullscreenExit.current=false;setFullscreenWanted(false);sessionStorage.removeItem('bingoup:tv-fullscreen-wanted')}};document.addEventListener('fullscreenchange',changed);return()=>document.removeEventListener('fullscreenchange',changed)},[])
  const appearance=normalizePublicPanelAppearance(state?.appearance??DEFAULT_PUBLIC_PANEL_APPEARANCE);const called=useMemo(()=>new Set(state?.called_numbers??[]),[state?.called_numbers]);const columns=useMemo(()=>buildPublicBoardColumns(state?.total_balls??75),[state?.total_balls]);const recent=useMemo(()=>recentCalledNumbers(state?.called_numbers??[],screenMode==='portrait'?5:8),[state?.called_numbers,screenMode])
  async function toggleFullscreen(){if(document.fullscreenElement){explicitFullscreenExit.current=true;await document.exitFullscreen?.()}else{setFullscreenWanted(true);sessionStorage.setItem('bingoup:tv-fullscreen-wanted','1');await document.documentElement.requestFullscreen?.()}}
  if(error&&!state)return <main className="grid h-[100dvh] place-items-center overflow-hidden bg-[#080808] p-8 text-white"><div className="max-w-xl text-center"><p className="text-3xl font-black">Painel indisponível</p><p className="mt-3 text-white/55">{error}</p></div></main>
  if(!state)return <main className="grid h-[100dvh] place-items-center overflow-hidden bg-[#080808] text-white"><p className="text-xl font-bold">Carregando painel…</p></main>
  const statusLabel=state.status==='active'?'Sorteio em andamento':state.status==='paused'?'Sorteio pausado':state.status==='finished'?'Rodada encerrada':'Rodada cancelada';const compact=screenMode==='portrait'
  return <main className={`tv-public-root tv-theme-${appearance.theme} h-[100dvh] overflow-hidden ${appearance.animated_frame?'tv-animated-frame':''}`} style={themeStyle(appearance)}>
    <div className={`tv-public-shell mx-auto flex h-full w-full max-w-[2560px] flex-col ${compact?'p-2':'p-3 sm:p-4 xl:p-5'}`}>
      {fullscreenWanted&&!fullscreen&&<div className="mb-2 flex shrink-0 items-center justify-between gap-3 rounded-xl border border-amber-400/30 bg-amber-400/10 px-3 py-2 text-xs text-amber-100"><span>O navegador saiu do modo tela cheia. O BINGOUP não altera isso automaticamente entre rodadas.</span><button type="button" onClick={()=>void toggleFullscreen()} className="shrink-0 rounded-lg bg-amber-300 px-3 py-1.5 font-black text-black">Restaurar tela cheia</button></div>}
      <header className={`tv-public-header grid shrink-0 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b ${compact?'pb-2':'pb-3'}`} style={{borderColor:'var(--tv-line)'}}><div className="flex items-center"><img src={publicPanelLogoUrl} alt="BINGOUP" className={`${compact?'h-9 max-w-[108px]':'h-[3.15rem] sm:h-[3.6rem] xl:h-[4.5rem] max-w-[198px] xl:max-w-[252px]'} w-auto shrink-0 object-contain`}/></div><div className="min-w-0 px-2 text-center"><p className="truncate text-[10px] font-black uppercase tracking-[.2em] opacity-50 sm:text-xs">EVENTO</p><p className={`${compact?'text-sm':'text-base sm:text-lg xl:text-xl'} truncate font-black`}>{state.event_name}</p>{appearance.event_contact&&<p className="mt-0.5 truncate text-[10px] font-bold sm:text-xs" style={{color:'var(--tv-accent)'}}><span className="mr-1 opacity-60">CONTATO DO EVENTO:</span>{appearance.event_contact}</p>}{appearance.show_round_name&&<h1 className={`tv-round-title mt-0.5 truncate font-black ${compact?'text-lg':'text-xl sm:text-2xl xl:text-3xl'}`}>{state.round_name?.trim()||`Rodada ${state.session_number}`}</h1>}</div><div className="flex shrink-0 items-center gap-2"><div className="hidden text-right sm:block"><p className="text-xs font-black uppercase tracking-wide opacity-80">{statusLabel}</p>{appearance.show_prize&&<p className="text-[11px] opacity-45">Prêmio: {state.win_pattern_name}</p>}</div><span className={`size-2.5 rounded-full ${connected?'bg-emerald-400':'bg-amber-400'}`}/><button type="button" onClick={()=>void toggleFullscreen()} className="tv-fullscreen-button rounded-xl border px-3 py-2 text-xs font-bold" style={{borderColor:'var(--tv-line)',background:'var(--tv-panel2)'}}>{fullscreen?'Sair da tela cheia':'Tela cheia'}</button></div></header>
      {state.confirmed_bingo?<PublicWinner state={state} appearance={appearance}/>:state.possible_bingo?<PossibleWinner appearance={appearance}/>:compact?<PortraitPanel state={state} called={called} columns={columns} recent={recent} appearance={appearance}/>:<ThemePanel state={state} called={called} columns={columns} recent={recent} appearance={appearance} wide={screenMode==='wide'}/>}
      <footer className="tv-public-footer flex shrink-0 items-center justify-between border-t pt-1.5 text-[9px] font-semibold uppercase tracking-wider opacity-30 sm:text-[10px]" style={{borderColor:'var(--tv-line)'}}><span>Tela pública do evento</span><span>{screenMode==='portrait'?'Vertical':screenMode==='wide'?'Panorâmica':'Horizontal'} · {connected?'Ao vivo':'Reconectando…'}</span></footer>
    </div>
  </main>
}

function ThemePanel(props:PanelProps){switch(props.appearance.theme){case'neon':return <NeonPanel {...props}/>;case'gold':return <GoldPanel {...props}/>;case'party':return <PartyPanel {...props}/>;case'elegant':return <ElegantPanel {...props}/>;case'minimal':return <MinimalPanel {...props}/>;case'led':return <LedPanel {...props}/>;case'colorful':return <ColorfulPanel {...props}/>;default:return <ClassicPanel {...props}/>}}
function ClassicPanel({state,called,columns,recent,wide,appearance}:PanelProps){return <div className={`tv-theme-layout tv-layout-classic grid min-h-0 flex-1 gap-3 py-2 ${wide?'grid-cols-[minmax(220px,.48fr)_minmax(0,1.52fr)]':'grid-cols-[minmax(210px,.58fr)_minmax(0,1.42fr)]'}`}><SideInfo state={state} recent={recent} appearance={appearance}/><Board columns={columns} called={called} style={appearance.board_style}/></div>}
function NeonPanel({state,called,columns,recent,appearance}:PanelProps){return <div className="tv-theme-layout tv-layout-neon grid min-h-0 flex-1 grid-cols-[minmax(0,1.55fr)_minmax(220px,.45fr)] gap-3 py-2"><Board columns={columns} called={called} style={appearance.board_style}/><section className="grid min-h-0 grid-rows-[minmax(0,1fr)_auto_auto] gap-2"><LastNumberPanel state={state} appearance={appearance}/>{appearance.show_recent_numbers&&<RecentNumbers recent={recent}/>}<MetricsRow state={state} appearance={appearance}/></section></div>}
function GoldPanel({state,called,columns,recent,appearance}:PanelProps){return <div className="tv-theme-layout tv-layout-gold grid min-h-0 flex-1 grid-rows-[auto_minmax(0,1fr)] gap-3 py-2"><section className="grid grid-cols-[1fr_1.4fr_1fr] items-stretch gap-3">{appearance.show_counters?<Metric value={state.called_count} label="sorteados"/>:<div/>}<LastNumberPanel state={state} appearance={appearance}/>{appearance.show_counters?<Metric value={state.total_balls-state.called_count} label="restantes"/>:<div/>}</section><div className="grid min-h-0 grid-cols-[minmax(0,1fr)_220px] gap-3"><Board columns={columns} called={called} style={appearance.board_style}/><section className="flex min-h-0 flex-col gap-2">{appearance.show_recent_numbers&&<RecentNumbers recent={recent}/>} {state.show_near_winners&&<><NearCard value={state.one_away??0} label="Falta 1" hot/><NearCard value={state.two_away??0} label="Faltam 2"/></>}</section></div></div>}
function PartyPanel({state,called,columns,recent,appearance}:PanelProps){return <div className="tv-theme-layout tv-layout-party grid min-h-0 flex-1 grid-rows-[auto_minmax(0,1fr)] gap-3 py-2"><section className="grid grid-cols-[1.15fr_.85fr_.85fr_1.15fr] gap-2"><LastNumberPanel state={state} appearance={appearance}/>{appearance.show_counters&&<Metric value={state.called_count} label="sorteados"/>}{state.show_near_winners&&<NearCard value={state.one_away??0} label="Falta 1" hot/>}{appearance.show_recent_numbers&&<RecentNumbers recent={recent}/>}</section><Board columns={columns} called={called} style={appearance.board_style}/></div>}
function ElegantPanel({state,called,columns,recent,appearance}:PanelProps){return <div className="tv-theme-layout tv-layout-elegant grid min-h-0 flex-1 grid-cols-[minmax(0,1.65fr)_minmax(240px,.35fr)] gap-6 py-4"><Board columns={columns} called={called} style={appearance.board_style}/><aside className="flex min-h-0 flex-col justify-center gap-4"><LastNumberPanel state={state} appearance={appearance}/>{appearance.show_recent_numbers&&<RecentNumbers recent={recent}/>}<MetricsRow state={state} appearance={appearance}/></aside></div>}
function MinimalPanel({state,called,columns,recent,appearance}:PanelProps){return <div className="tv-theme-layout tv-layout-minimal grid min-h-0 flex-1 grid-rows-[auto_minmax(0,1fr)] gap-2 py-2"><section className="flex items-center gap-3"><LastNumberPanel state={state} appearance={appearance}/><div className="grid flex-1 grid-cols-2 gap-2">{appearance.show_counters&&<><Metric value={state.called_count} label="sorteados"/><Metric value={state.total_balls-state.called_count} label="restantes"/></>}{state.show_near_winners&&<><NearCard value={state.one_away??0} label="Falta 1" hot/><NearCard value={state.two_away??0} label="Faltam 2"/></>}</div>{appearance.show_recent_numbers&&<div className="w-[28%]"><RecentNumbers recent={recent}/></div>}</section><Board columns={columns} called={called} style={appearance.board_style}/></div>}
function LedPanel({state,called,columns,recent,appearance}:PanelProps){return <div className="tv-theme-layout tv-layout-led grid min-h-0 flex-1 grid-rows-[auto_minmax(0,1fr)_auto] gap-2 py-2"><section className="tv-led-ticker grid grid-cols-[1fr_auto_1fr] items-center gap-3 border px-4 py-2" style={{borderColor:'var(--tv-line)',background:'var(--tv-panel)'}}><span className="text-xs font-black uppercase tracking-[.25em] opacity-60">Última bola</span><AnimatedLastNumber number={state.last_called_number} animation={appearance.ball_animation} compact/><span className="text-right text-xs font-black uppercase tracking-[.2em] opacity-60">{state.called_count}/{state.total_balls}</span></section><Board columns={columns} called={called} style={appearance.board_style}/><section className="grid grid-cols-[1fr_1fr_2fr] gap-2">{state.show_near_winners&&<><NearCard value={state.one_away??0} label="Falta 1" hot/><NearCard value={state.two_away??0} label="Faltam 2"/></>}{appearance.show_recent_numbers&&<RecentNumbers recent={recent}/>}</section></div>}
function ColorfulPanel({state,called,columns,recent,appearance}:PanelProps){return <div className="tv-theme-layout tv-layout-colorful grid min-h-0 flex-1 grid-cols-[minmax(210px,.38fr)_minmax(0,1.25fr)_minmax(190px,.37fr)] gap-3 py-2"><section className="flex min-h-0 flex-col gap-3"><LastNumberPanel state={state} appearance={appearance}/>{appearance.show_counters&&<Metric value={state.called_count} label="sorteados"/>}</section><Board columns={columns} called={called} style={appearance.board_style}/><section className="flex min-h-0 flex-col gap-3">{appearance.show_recent_numbers&&<RecentNumbers recent={recent}/>} {state.show_near_winners&&<><NearCard value={state.one_away??0} label="Falta 1" hot/><NearCard value={state.two_away??0} label="Faltam 2"/></>}{appearance.show_counters&&<Metric value={state.total_balls-state.called_count} label="restantes"/>}</section></div>}
function PortraitPanel({state,called,columns,recent,appearance}:PanelProps){return <div className="tv-theme-layout tv-layout-portrait grid min-h-0 flex-1 grid-rows-[auto_minmax(0,1fr)] gap-2 py-2"><section className="grid grid-cols-[1.15fr_.85fr_.85fr] gap-2"><LastNumberPanel state={state} appearance={appearance} compact/><div className="grid gap-2">{appearance.show_counters&&<><Metric value={state.called_count} label="sorteados"/><Metric value={state.total_balls-state.called_count} label="restantes"/></>}</div><div className="grid gap-2">{state.show_near_winners?<><NearCard value={state.one_away??0} label="Falta 1" hot/><NearCard value={state.two_away??0} label="Faltam 2"/></>:appearance.show_recent_numbers?<RecentNumbers recent={recent}/>:null}</div></section><Board columns={columns} called={called} compact style={appearance.board_style}/></div>}
function SideInfo({state,recent,appearance}:{state:PublicPanelState;recent:number[];appearance:PublicPanelAppearance}){return <section className="flex min-h-0 flex-col gap-2"><LastNumberPanel state={state} appearance={appearance}/>{appearance.show_recent_numbers&&recent.length>0&&<RecentNumbers recent={recent}/>}<MetricsRow state={state} appearance={appearance}/></section>}
function LastNumberPanel({state,appearance,compact=false}:{state:PublicPanelState;appearance:PublicPanelAppearance;compact?:boolean}){return <Panel className="tv-last-panel min-h-0 flex-1"><div className="grid h-full place-items-center p-2 text-center"><div><p className="tv-last-label text-[10px] font-black uppercase tracking-[.24em] opacity-45 sm:text-xs">Último número</p><AnimatedLastNumber number={state.last_called_number} animation={appearance.ball_animation} compact={compact}/></div></div></Panel>}
function MetricsRow({state,appearance}:{state:PublicPanelState;appearance:PublicPanelAppearance}){return <>{appearance.show_counters&&<div className="grid grid-cols-2 gap-2"><Metric value={state.called_count} label={`de ${state.total_balls}`}/><Metric value={state.total_balls-state.called_count} label="restantes"/></div>}{state.show_near_winners&&<div className="grid grid-cols-2 gap-2"><NearCard value={state.one_away??0} label="Falta 1" hot/><NearCard value={state.two_away??0} label="Faltam 2"/></div>}</>}
function AnimatedLastNumber({number,animation,compact=false}:{number:number|null;animation:PublicPanelAppearance['ball_animation'];compact?:boolean}){return <p key={number??'empty'} className={`tv-last-number tv-ball-${animation} font-black leading-[.78] tracking-tighter ${compact?'text-[clamp(3rem,9vh,5.5rem)]':'text-[clamp(5rem,20vh,13rem)]'}`} style={{color:'var(--tv-accent)',textShadow:'0 0 28px color-mix(in srgb,var(--tv-accent) 35%, transparent)'}}>{number??'—'}</p>}
function Board({columns,called,compact=false,style}:{columns:ReturnType<typeof buildPublicBoardColumns>;called:Set<number>;compact?:boolean;style:PublicPanelAppearance['board_style']}){return <Panel className="tv-board-panel min-h-0 overflow-hidden"><div className="flex h-full min-h-0 flex-col p-2 sm:p-3"><div className="tv-board-heading flex shrink-0 items-center justify-between gap-2 pb-2"><h2 className={`${compact?'text-sm':'text-base sm:text-lg'} font-black`}>Números sorteados</h2><span className="text-[9px] font-bold opacity-35 sm:text-[10px]">Atualização automática</span></div><div className={`tv-board tv-board-${style} grid min-h-0 flex-1 grid-cols-5 gap-1 sm:gap-1.5`}>{columns.map(column=><div key={column.label} className="tv-board-column grid min-h-0 grid-rows-[auto_minmax(0,1fr)] gap-1"><div className={`tv-board-letter grid place-items-center font-black ${compact?'h-7 text-sm':'h-8 text-base sm:h-9 sm:text-lg'}`} style={{background:'var(--tv-accent)',color:'var(--tv-called-text)',borderRadius:style==='balls'?'999px':'var(--tv-cell-radius,10px)'}}>{column.label}</div><div className="grid min-h-0 gap-0.5 sm:gap-1" style={{gridTemplateRows:`repeat(${Math.max(1,column.numbers.length)},minmax(0,1fr))`}}>{column.numbers.map(n=><div key={n} style={{fontSize:style==='giant'?'clamp(.7rem,1.9vmin,1.55rem)':'clamp(.55rem,1.55vmin,1.35rem)',borderColor:called.has(n)?'var(--tv-accent)':'var(--tv-line)',background:called.has(n)?'var(--tv-accent)':'color-mix(in srgb,var(--tv-panel2) 88%, transparent)',color:called.has(n)?'var(--tv-called-text)':'color-mix(in srgb,var(--tv-text) 36%, transparent)',borderRadius:style==='balls'?'999px':style==='cards'?'14px':style==='led'?'4px':'var(--tv-cell-radius,7px)',boxShadow:called.has(n)&&style==='led'?'0 0 15px var(--tv-accent)':undefined}} className="tv-board-number grid min-h-0 place-items-center border font-black leading-none">{n}</div>)}</div></div>)}</div></div></Panel>}
function Panel({children,className=''}:{children:React.ReactNode;className?:string}){return <section className={`tv-panel border ${className}`} style={{borderColor:'var(--tv-line)',background:'var(--tv-panel)'}}>{children}</section>}
function RecentNumbers({recent}:{recent:number[]}){return <Panel className="tv-recent-panel"><div className="p-2"><p className="text-center text-[9px] font-black uppercase tracking-[.18em] opacity-40">Últimos</p><div className="mt-1 flex flex-wrap justify-center gap-1.5">{recent.map((number,index)=><span key={`${number}-${index}`} className="tv-recent-number grid size-8 place-items-center rounded-full border text-xs font-black" style={{borderColor:index===0?'var(--tv-accent)':'var(--tv-line)',background:index===0?'var(--tv-accent)':'var(--tv-panel2)',color:index===0?'var(--tv-called-text)':'var(--tv-text)'}}>{number}</span>)}</div></div></Panel>}
function Metric({value,label}:{value:number;label:string}){return <Panel className="tv-metric"><div className="grid h-full place-items-center p-2 text-center"><div><p className="text-2xl font-black sm:text-3xl">{value}</p><p className="text-[9px] font-bold uppercase tracking-wide opacity-40 sm:text-[10px]">{label}</p></div></div></Panel>}
function NearCard({value,label,hot=false}:{value:number;label:string;hot?:boolean}){return <section className="tv-near-card grid place-items-center border p-2 text-center" style={{borderColor:hot?'var(--tv-hot)':'var(--tv-line)',background:hot?'color-mix(in srgb,var(--tv-hot) 10%, var(--tv-panel))':'var(--tv-panel)'}}><div><p className="text-2xl font-black sm:text-3xl" style={{color:hot?'var(--tv-hot)':'var(--tv-text)'}}>{value}</p><p className="text-[9px] font-bold uppercase tracking-wider opacity-45 sm:text-[10px]">{label}</p></div></section>}
function PossibleWinner({appearance}:{appearance:PublicPanelAppearance}){return <section className="grid min-h-0 flex-1 place-items-center py-4 text-center"><div className={`tv-possible tv-ball-${appearance.ball_animation}`}><p className="text-[clamp(3rem,10vmin,8rem)]">🏆</p><h2 className="text-[clamp(2.5rem,7vmin,7rem)] font-black leading-none tracking-tight" style={{color:'var(--tv-hot)'}}>POSSÍVEL BINGO</h2><p className="mt-4 text-[clamp(1rem,2vmin,1.8rem)] font-bold opacity-75">Sorteio pausado. Aguarde a conferência da organização.</p></div></section>}
function PublicWinner({state,appearance}:{state:PublicPanelState;appearance:PublicPanelAppearance}){return <section className="relative grid min-h-0 flex-1 place-items-center overflow-hidden py-4 text-center"><VictoryFx type={appearance.victory_animation} intensity={appearance.animation_intensity}/><div className="relative z-10 tv-winner-card"><p className="text-[clamp(3rem,10vmin,8rem)]">🏆</p><h2 className="text-[clamp(3rem,8vmin,8rem)] font-black leading-none tracking-tight" style={{color:'var(--tv-accent)'}}>GANHADOR!</h2><p className="mt-4 text-[clamp(1rem,2.2vmin,2rem)] font-bold">{state.confirmed_winners>1?`${state.confirmed_winners} vencedores confirmados`:'Vencedor confirmado'}</p>{state.winner_labels?.length>0&&<p className="mx-auto mt-3 max-w-4xl text-[clamp(.9rem,1.6vmin,1.35rem)] font-black">{state.winner_labels.join(' · ')}</p>}<p className="mt-2 text-[clamp(.85rem,1.4vmin,1.2rem)] font-semibold opacity-55">{state.win_pattern_name}</p></div></section>}
function VictoryFx({type,intensity}:{type:PublicPanelAppearance['victory_animation'];intensity:PublicPanelAppearance['animation_intensity']}){if(type==='none'||type==='elegant')return type==='elegant'?<div className="tv-elegant-glow absolute inset-[8%] rounded-[4rem]"/>:null;const count=intensity==='subtle'?18:intensity==='party'?54:34;return <div className={`tv-victory-fx tv-victory-${type} pointer-events-none absolute inset-0 overflow-hidden`}>{Array.from({length:count},(_,i)=><i key={i} style={{'--i':i,'--x':`${(i*37)%100}%`,'--delay':`${-(i%13)*.17}s`,'--dur':`${1.8+(i%7)*.19}s`} as CSSProperties}>{type==='stars'?'★':type==='fireworks'?'✦':''}</i>)}</div>}
